[package]
name = "hello"
version = "0.0.1"
edition = "2021"

[dependencies.windows]
features = [
    "alloc",
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_System_LibraryLoader",
    "Win32_UI_WindowsAndMessaging",
]
