/*
 * DirectX 12 Compute Shader Harmonograph - JScript.NET
 *
 * This file uses JScript.NET to compile and run embedded C# code at runtime.
 * The embedded C# code implements a harmonograph visualizer using DirectX 12
 * compute shaders to calculate 100,000 vertices in parallel.
 *
 * Requirements:
 *   - hello.hlsl must be in the same directory as this script
 *   - .NET Framework 4.x
 *   - DirectX 12 capable GPU (Windows 10+)
 *
 * Build:
 *   jsc /out:Harmonograph.exe Harmonograph.js
 *
 * Run:
 *   Harmonograph.exe
 */

import System;
import System.CodeDom.Compiler;
import Microsoft.CSharp;
import System.Reflection;

// ─── JScript.NET entry point ─────────────────────────────────────────────────

function Main() {
    Console.WriteLine("Compiling embedded C# DirectX 12 Harmonograph code...");

    var provider = new CSharpCodeProvider();
    var parameters = new CompilerParameters();

    parameters.GenerateInMemory    = true;
    parameters.GenerateExecutable  = false;
    parameters.CompilerOptions     = "/unsafe";

    // Required assemblies  Emscorlib is always added automatically
    parameters.ReferencedAssemblies.Add("System.dll");

    var results = provider.CompileAssemblyFromSource(parameters, csharpSource);

    if (results.Errors.HasErrors) {
        Console.WriteLine("Compilation failed:");
        for (var i = 0; i < results.Errors.Count; i++) {
            Console.WriteLine(results.Errors[i].ErrorText);
        }
        return;
    }

    Console.WriteLine("Compilation successful. Starting application...");
    try {
        var assembly    = results.CompiledAssembly;
        var programType = assembly.GetType("Harmonograph");
        var mainMethod  = programType.GetMethod("Main");
        var invokeArgs = new Object[1];
        invokeArgs[0] = new String[0];
        mainMethod.Invoke(null, invokeArgs);
    } catch (e) {
        Console.WriteLine("Runtime Error: " + e.ToString());
    }
}

// ─── Embedded C# source ──────────────────────────────────────────────────────
// All C# 7 features (inline out-var, discards, string interpolation) are
// converted to C# 5 compatible syntax so that CSharpCodeProvider can compile
// without /langversion flags.

var csharpSource = [

    // ── Usings ────────────────────────────────────────────────────────────────
    "using System;",
    "using System.Runtime.InteropServices;",
    "",

    // ── Class declaration ─────────────────────────────────────────────────────
    "public class Harmonograph",
    "{",

    // ── Win32 / DXGI / D3D12 structs ─────────────────────────────────────────
    "    [StructLayout(LayoutKind.Sequential)] struct POINT { public int X, Y; }",

    "    [StructLayout(LayoutKind.Sequential)]",
    "    struct MSG { public IntPtr hwnd; public uint message; public IntPtr wParam, lParam; public uint time; public POINT pt; }",

    "    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Auto)]",
    "    struct WNDCLASSEX {",
    "        public uint cbSize, style;",
    "        public WndProcDelegate lpfnWndProc;",
    "        public int cbClsExtra, cbWndExtra;",
    "        public IntPtr hInstance, hIcon, hCursor, hbrBackground;",
    "        public string lpszMenuName, lpszClassName;",
    "        public IntPtr hIconSm;",
    "    }",

    "    [StructLayout(LayoutKind.Sequential)]",
    "    struct DXGI_SWAP_CHAIN_DESC1 {",
    "        public uint Width, Height, Format;",
    "        public int Stereo;",
    "        public DXGI_SAMPLE_DESC SampleDesc;",
    "        public uint BufferUsage, BufferCount;",
    "        public int Scaling, SwapEffect, AlphaMode;",
    "        public uint Flags;",
    "    }",

    "    [StructLayout(LayoutKind.Sequential)] struct DXGI_SAMPLE_DESC { public uint Count, Quality; }",
    "    [StructLayout(LayoutKind.Sequential)] struct D3D12_COMMAND_QUEUE_DESC { public int Type, Priority, Flags; public uint NodeMask; }",
    "    [StructLayout(LayoutKind.Sequential)] struct D3D12_DESCRIPTOR_HEAP_DESC { public int Type; public uint NumDescriptors; public int Flags; public uint NodeMask; }",
    "    [StructLayout(LayoutKind.Sequential)] struct D3D12_CPU_DESCRIPTOR_HANDLE { public IntPtr ptr; }",
    "    [StructLayout(LayoutKind.Sequential)] struct D3D12_GPU_DESCRIPTOR_HANDLE { public ulong ptr; }",
    "    [StructLayout(LayoutKind.Sequential)] struct D3D12_HEAP_PROPERTIES { public int Type, CPUPageProperty, MemoryPoolPreference; public uint CreationNodeMask, VisibleNodeMask; }",

    "    [StructLayout(LayoutKind.Sequential)]",
    "    struct D3D12_RESOURCE_DESC {",
    "        public int Dimension;",
    "        public ulong Alignment, Width;",
    "        public uint Height;",
    "        public ushort DepthOrArraySize, MipLevels;",
    "        public uint Format;",
    "        public DXGI_SAMPLE_DESC SampleDesc;",
    "        public int Layout, Flags;",
    "    }",

    "    [StructLayout(LayoutKind.Sequential)] struct D3D12_SHADER_BYTECODE { public IntPtr pShaderBytecode; public IntPtr BytecodeLength; }",

    "    [StructLayout(LayoutKind.Sequential)]",
    "    struct D3D12_COMPUTE_PIPELINE_STATE_DESC {",
    "        public IntPtr pRootSignature;",
    "        public D3D12_SHADER_BYTECODE CS;",
    "        public uint NodeMask;",
    "        public IntPtr CachedPSO_pCachedBlob;",
    "        public IntPtr CachedPSO_CachedBlobSizeInBytes;",
    "        public int Flags;",
    "    }",

    "    [StructLayout(LayoutKind.Sequential)]",
    "    struct D3D12_STREAM_OUTPUT_DESC { public IntPtr pSODeclaration; public uint NumEntries, NumStrides; public IntPtr pBufferStrides; public uint RasterizedStream; }",

    "    [StructLayout(LayoutKind.Sequential)]",
    "    struct D3D12_RENDER_TARGET_BLEND_DESC {",
    "        public int BlendEnable, LogicOpEnable;",
    "        public int SrcBlend, DestBlend, BlendOp, SrcBlendAlpha, DestBlendAlpha, BlendOpAlpha, LogicOp;",
    "        public byte RenderTargetWriteMask;",
    "    }",

    "    [StructLayout(LayoutKind.Sequential)]",
    "    struct D3D12_BLEND_DESC {",
    "        public int AlphaToCoverageEnable, IndependentBlendEnable;",
    "        public D3D12_RENDER_TARGET_BLEND_DESC RT0, RT1, RT2, RT3, RT4, RT5, RT6, RT7;",
    "    }",

    "    [StructLayout(LayoutKind.Sequential)]",
    "    struct D3D12_RASTERIZER_DESC {",
    "        public int FillMode, CullMode, FrontCounterClockwise;",
    "        public int DepthBias;",
    "        public float DepthBiasClamp, SlopeScaledDepthBias;",
    "        public int DepthClipEnable, MultisampleEnable, AntialiasedLineEnable, ForcedSampleCount, ConservativeRaster;",
    "    }",

    "    [StructLayout(LayoutKind.Sequential)]",
    "    struct D3D12_DEPTH_STENCILOP_DESC { public int StencilFailOp, StencilDepthFailOp, StencilPassOp, StencilFunc; }",

    "    [StructLayout(LayoutKind.Sequential)]",
    "    struct D3D12_DEPTH_STENCIL_DESC {",
    "        public int DepthEnable, DepthWriteMask, DepthFunc, StencilEnable;",
    "        public byte StencilReadMask, StencilWriteMask;",
    "        public D3D12_DEPTH_STENCILOP_DESC FrontFace, BackFace;",
    "    }",

    "    [StructLayout(LayoutKind.Sequential)] struct D3D12_INPUT_LAYOUT_DESC { public IntPtr pInputElementDescs; public uint NumElements; }",

    "    [StructLayout(LayoutKind.Sequential)]",
    "    struct D3D12_GRAPHICS_PIPELINE_STATE_DESC {",
    "        public IntPtr pRootSignature;",
    "        public D3D12_SHADER_BYTECODE VS, PS, DS, HS, GS;",
    "        public D3D12_STREAM_OUTPUT_DESC StreamOutput;",
    "        public D3D12_BLEND_DESC BlendState;",
    "        public uint SampleMask;",
    "        public D3D12_RASTERIZER_DESC RasterizerState;",
    "        public D3D12_DEPTH_STENCIL_DESC DepthStencilState;",
    "        public D3D12_INPUT_LAYOUT_DESC InputLayout;",
    "        public int IBStripCutValue, PrimitiveTopologyType;",
    "        public uint NumRenderTargets;",
    "        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 8)] public uint[] RTVFormats;",
    "        public uint DSVFormat;",
    "        public DXGI_SAMPLE_DESC SampleDesc;",
    "        public uint NodeMask;",
    "        public IntPtr CachedPSO_pCachedBlob;",
    "        public IntPtr CachedPSO_CachedBlobSizeInBytes;",
    "        public int Flags;",
    "    }",

    "    [StructLayout(LayoutKind.Sequential)] struct D3D12_ROOT_SIGNATURE_DESC { public uint NumParameters; public IntPtr pParameters; public uint NumStaticSamplers; public IntPtr pStaticSamplers; public int Flags; }",
    "    [StructLayout(LayoutKind.Sequential)] struct D3D12_ROOT_DESCRIPTOR_TABLE { public uint NumDescriptorRanges; public IntPtr pDescriptorRanges; }",
    "    [StructLayout(LayoutKind.Sequential)] struct D3D12_ROOT_PARAMETER { public int ParameterType; public D3D12_ROOT_DESCRIPTOR_TABLE DescriptorTable; public int ShaderVisibility; }",
    "    [StructLayout(LayoutKind.Sequential)] struct D3D12_DESCRIPTOR_RANGE { public int RangeType; public uint NumDescriptors, BaseShaderRegister, RegisterSpace; public int OffsetInDescriptorsFromTableStart; }",

    "    [StructLayout(LayoutKind.Sequential)]",
    "    struct D3D12_RESOURCE_BARRIER {",
    "        public int Type, Flags;",
    "        public IntPtr pResource;",
    "        public uint Subresource;",
    "        public int StateBefore, StateAfter;",
    "    }",

    "    [StructLayout(LayoutKind.Sequential)] struct D3D12_VIEWPORT { public float TopLeftX, TopLeftY, Width, Height, MinDepth, MaxDepth; }",
    "    [StructLayout(LayoutKind.Sequential)] struct D3D12_RECT { public int left, top, right, bottom; }",
    "    [StructLayout(LayoutKind.Sequential)] struct D3D12_RANGE { public IntPtr Begin, End; }",

    "    [StructLayout(LayoutKind.Sequential)]",
    "    struct D3D12_UNORDERED_ACCESS_VIEW_DESC {",
    "        public uint Format;",
    "        public int ViewDimension;",
    "        public ulong Buffer_FirstElement;",
    "        public uint Buffer_NumElements, Buffer_StructureByteStride;",
    "        public ulong Buffer_CounterOffsetInBytes;",
    "        public int Buffer_Flags;",
    "    }",

    "    [StructLayout(LayoutKind.Sequential)]",
    "    struct D3D12_SHADER_RESOURCE_VIEW_DESC {",
    "        public uint Format;",
    "        public int ViewDimension;",
    "        public int Shader4ComponentMapping;",
    "        public ulong Buffer_FirstElement;",
    "        public uint Buffer_NumElements, Buffer_StructureByteStride;",
    "        public int Buffer_Flags;",
    "    }",

    "    [StructLayout(LayoutKind.Sequential)] struct D3D12_CONSTANT_BUFFER_VIEW_DESC { public ulong BufferLocation; public uint SizeInBytes; }",

    "    [StructLayout(LayoutKind.Sequential)]",
    "    struct HarmonographParams {",
    "        public float A1, f1, p1, d1;",
    "        public float A2, f2, p2, d2;",
    "        public float A3, f3, p3, d3;",
    "        public float A4, f4, p4, d4;",
    "        public uint  max_num;",
    "        public float padding1, padding2, padding3;",
    "        public float resolutionX, resolutionY;",
    "        public float padding4, padding5;",
    "    }",

    // ── Constants ─────────────────────────────────────────────────────────────
    "    const uint WS_OVERLAPPEDWINDOW = 0x00CF0000, WS_VISIBLE = 0x10000000;",
    "    const uint WM_DESTROY = 0x0002, WM_QUIT = 0x0012, PM_REMOVE = 0x0001;",
    "    const uint CS_OWNDC  = 0x0020;",
    "    const int  IDC_ARROW = 32512;",
    "    const uint INFINITE  = 0xFFFFFFFF;",
    "    const int  WIDTH  = 800, HEIGHT = 600, FRAME_COUNT = 2;",
    "    const int  VERTEX_COUNT = 100000;",
    "    const uint D3D_FEATURE_LEVEL_12_0          = 0xc000;",
    "    const uint D3D_ROOT_SIGNATURE_VERSION_1     = 1;",
    "    const uint DXGI_FORMAT_R8G8B8A8_UNORM       = 28;",
    "    const int  D3D12_DESCRIPTOR_RANGE_TYPE_SRV  = 0;",
    "    const int  D3D12_DESCRIPTOR_RANGE_TYPE_UAV  = 1;",
    "    const int  D3D12_DESCRIPTOR_RANGE_TYPE_CBV  = 2;",
    "    const int  D3D12_SRV_DIMENSION_BUFFER       = 1;",

    // ── Win32 P/Invoke ────────────────────────────────────────────────────────
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)]",
    "    delegate IntPtr WndProcDelegate(IntPtr hWnd, uint uMsg, IntPtr wParam, IntPtr lParam);",

    "    [DllImport(\"user32.dll\", CharSet = CharSet.Auto)] static extern bool     ShowWindow(IntPtr hWnd, int nCmdShow);",
    "    [DllImport(\"user32.dll\", CharSet = CharSet.Auto)] static extern IntPtr   LoadCursor(IntPtr hInstance, int lpCursorName);",
    "    [DllImport(\"user32.dll\", CharSet = CharSet.Auto)] static extern ushort   RegisterClassEx([In] ref WNDCLASSEX lpwcx);",
    "    [DllImport(\"user32.dll\", CharSet = CharSet.Auto)] static extern IntPtr   CreateWindowEx(uint dwExStyle, string lpClassName, string lpWindowName, uint dwStyle, int x, int y, int nWidth, int nHeight, IntPtr hWndParent, IntPtr hMenu, IntPtr hInstance, IntPtr lpParam);",
    "    [DllImport(\"user32.dll\", CharSet = CharSet.Auto)] static extern bool     PeekMessage(out MSG lpMsg, IntPtr hWnd, uint wMsgFilterMin, uint wMsgFilterMax, uint wRemoveMsg);",
    "    [DllImport(\"user32.dll\", CharSet = CharSet.Auto)] static extern bool     TranslateMessage([In] ref MSG lpMsg);",
    "    [DllImport(\"user32.dll\", CharSet = CharSet.Auto)] static extern IntPtr   DispatchMessage([In] ref MSG lpMsg);",
    "    [DllImport(\"user32.dll\", CharSet = CharSet.Auto)] static extern void     PostQuitMessage(int nExitCode);",
    "    [DllImport(\"user32.dll\", CharSet = CharSet.Auto)] static extern IntPtr   DefWindowProc(IntPtr hWnd, uint uMsg, IntPtr wParam, IntPtr lParam);",
    "    [DllImport(\"kernel32.dll\")] static extern IntPtr CreateEvent(IntPtr lpEventAttributes, bool bManualReset, bool bInitialState, string lpName);",
    "    [DllImport(\"kernel32.dll\")] static extern uint   WaitForSingleObject(IntPtr hHandle, uint dwMilliseconds);",
    "    [DllImport(\"kernel32.dll\")] static extern bool   CloseHandle(IntPtr hObject);",
    "    [DllImport(\"kernel32.dll\")] static extern void   OutputDebugStringA([MarshalAs(UnmanagedType.LPStr)] string msg);",

    // ── DirectX P/Invoke ──────────────────────────────────────────────────────
    "    [DllImport(\"d3d12.dll\")]          static extern int D3D12GetDebugInterface(ref Guid riid, out IntPtr ppvDebug);",
    "    [DllImport(\"d3d12.dll\")]          static extern int D3D12CreateDevice(IntPtr pAdapter, uint MinimumFeatureLevel, ref Guid riid, out IntPtr ppDevice);",
    "    [DllImport(\"dxgi.dll\")]           static extern int CreateDXGIFactory1(ref Guid riid, out IntPtr ppFactory);",
    "    [DllImport(\"d3d12.dll\")]          static extern int D3D12SerializeRootSignature(ref D3D12_ROOT_SIGNATURE_DESC pRootSignature, uint Version, out IntPtr ppBlob, out IntPtr ppErrorBlob);",
    "    [DllImport(\"d3dcompiler_47.dll\")] static extern int D3DCompileFromFile([MarshalAs(UnmanagedType.LPWStr)] string pFileName, IntPtr pDefines, IntPtr pInclude, [MarshalAs(UnmanagedType.LPStr)] string pEntrypoint, [MarshalAs(UnmanagedType.LPStr)] string pTarget, uint Flags1, uint Flags2, out IntPtr ppCode, out IntPtr ppErrorMsgs);",

    // ── GUIDs ─────────────────────────────────────────────────────────────────
    "    static Guid IID_ID3D12Debug              = new Guid(\"344488b7-6846-474b-b989-f027448245e0\");",
    "    static Guid IID_IDXGIFactory4             = new Guid(\"1bc6ea02-ef36-464f-bf0c-21ca39e5168a\");",
    "    static Guid IID_ID3D12Device              = new Guid(\"189819f1-1db6-4b57-be54-1821339b85f7\");",
    "    static Guid IID_ID3D12CommandQueue        = new Guid(\"0ec870a6-5d7e-4c22-8cfc-5baae07616ed\");",
    "    static Guid IID_IDXGISwapChain3           = new Guid(\"94d99bdb-f1f8-4ab0-b236-7da0170edab1\");",
    "    static Guid IID_ID3D12DescriptorHeap      = new Guid(\"8efb471d-616c-4f49-90f7-127bb763fa51\");",
    "    static Guid IID_ID3D12Resource            = new Guid(\"696442be-a72e-4059-bc79-5b5c98040fad\");",
    "    static Guid IID_ID3D12CommandAllocator    = new Guid(\"6102dee4-af59-4b09-b999-b44d73f09b24\");",
    "    static Guid IID_ID3D12RootSignature       = new Guid(\"c54a6b66-72df-4ee8-8be5-a946a1429214\");",
    "    static Guid IID_ID3D12PipelineState       = new Guid(\"765a30f3-f624-4c6f-a828-ace948622445\");",
    "    static Guid IID_ID3D12GraphicsCommandList = new Guid(\"5b160d0f-ac1b-4185-8ba8-b3ae42a5a455\");",
    "    static Guid IID_ID3D12Fence               = new Guid(\"0a753dcf-c4d8-4b91-adf6-be5a60d95a76\");",

    // ── Delegates ─────────────────────────────────────────────────────────────
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate void     EnableDebugLayerDelegate(IntPtr debug);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int      CreateCommandQueueDelegate(IntPtr device, ref D3D12_COMMAND_QUEUE_DESC desc, ref Guid riid, out IntPtr queue);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int      CreateDescriptorHeapDelegate(IntPtr device, ref D3D12_DESCRIPTOR_HEAP_DESC desc, ref Guid riid, out IntPtr heap);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate uint     GetDescriptorHandleIncrementSizeDelegate(IntPtr device, int type);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int      CreateCommandAllocatorDelegate(IntPtr device, int type, ref Guid riid, out IntPtr allocator);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int      CreateRootSignatureDelegate(IntPtr device, uint nodeMask, IntPtr pBlob, IntPtr blobLen, ref Guid riid, out IntPtr rootSig);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int      CreateGraphicsPipelineStateDelegate(IntPtr device, ref D3D12_GRAPHICS_PIPELINE_STATE_DESC desc, ref Guid riid, out IntPtr pso);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int      CreateComputePipelineStateDelegate(IntPtr device, ref D3D12_COMPUTE_PIPELINE_STATE_DESC desc, ref Guid riid, out IntPtr pso);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int      CreateCommandListDelegate(IntPtr device, uint nodeMask, int type, IntPtr allocator, IntPtr initialState, ref Guid riid, out IntPtr cmdList);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int      CreateCommittedResourceDelegate(IntPtr device, ref D3D12_HEAP_PROPERTIES heapProps, int heapFlags, ref D3D12_RESOURCE_DESC desc, int initialState, IntPtr clearValue, ref Guid riid, out IntPtr resource);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int      CreateFenceDelegate(IntPtr device, ulong initialValue, int flags, ref Guid riid, out IntPtr fence);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate void     CreateRenderTargetViewDelegate(IntPtr device, IntPtr resource, IntPtr desc, D3D12_CPU_DESCRIPTOR_HANDLE destDescriptor);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate void     CreateUnorderedAccessViewDelegate(IntPtr device, IntPtr resource, IntPtr counterResource, ref D3D12_UNORDERED_ACCESS_VIEW_DESC desc, D3D12_CPU_DESCRIPTOR_HANDLE destDescriptor);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate void     CreateConstantBufferViewDelegate(IntPtr device, ref D3D12_CONSTANT_BUFFER_VIEW_DESC desc, D3D12_CPU_DESCRIPTOR_HANDLE destDescriptor);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate void     CreateSRVDelegate(IntPtr device, IntPtr resource, ref D3D12_SHADER_RESOURCE_VIEW_DESC desc, D3D12_CPU_DESCRIPTOR_HANDLE handle);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int      GetBufferDelegate(IntPtr swapChain, uint buffer, ref Guid riid, out IntPtr surface);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int      PresentDelegate(IntPtr swapChain, uint syncInterval, uint flags);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate uint     GetCurrentBackBufferIndexDelegate(IntPtr swapChain);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int      CreateSwapChainForHwndDelegate(IntPtr factory, IntPtr device, IntPtr hwnd, ref DXGI_SWAP_CHAIN_DESC1 desc, IntPtr fullscreenDesc, IntPtr restrictToOutput, out IntPtr swapChain);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int      ResetCommandAllocatorDelegate(IntPtr allocator);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int      ResetCommandListDelegate(IntPtr commandList, IntPtr allocator, IntPtr pso);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int      CloseCommandListDelegate(IntPtr commandList);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate void     SetDescriptorHeapsDelegate(IntPtr commandList, uint numHeaps, IntPtr[] heaps);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate void     SetComputeRootSignatureDelegate(IntPtr commandList, IntPtr rootSignature);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate void     SetGraphicsRootSignatureDelegate(IntPtr commandList, IntPtr rootSignature);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate void     SetComputeRootDescriptorTableDelegate(IntPtr commandList, uint rootParamIndex, D3D12_GPU_DESCRIPTOR_HANDLE baseDescriptor);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate void     SetGraphicsRootDescriptorTableDelegate(IntPtr commandList, uint rootParamIndex, D3D12_GPU_DESCRIPTOR_HANDLE baseDescriptor);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate void     DispatchDelegate(IntPtr commandList, uint x, uint y, uint z);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate void     ResourceBarrierDelegate(IntPtr commandList, uint numBarriers, ref D3D12_RESOURCE_BARRIER barriers);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate void     RSSetViewportsDelegate(IntPtr commandList, uint numViewports, ref D3D12_VIEWPORT viewports);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate void     RSSetScissorRectsDelegate(IntPtr commandList, uint numRects, ref D3D12_RECT rects);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate void     ClearRenderTargetViewDelegate(IntPtr commandList, D3D12_CPU_DESCRIPTOR_HANDLE rtv, float[] colorRGBA, uint numRects, IntPtr rects);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate void     OMSetRenderTargetsDelegate(IntPtr commandList, uint numRTVs, ref D3D12_CPU_DESCRIPTOR_HANDLE rtvDescriptors, int rtsSingleHandle, IntPtr dsvDescriptor);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate void     IASetPrimitiveTopologyDelegate(IntPtr commandList, int primitiveTopology);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate void     DrawInstancedDelegate(IntPtr commandList, uint vertexCountPerInstance, uint instanceCount, uint startVertexLocation, uint startInstanceLocation);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate void     ExecuteCommandListsDelegate(IntPtr commandQueue, uint numCommandLists, IntPtr[] commandLists);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int      SignalDelegate(IntPtr commandQueue, IntPtr fence, ulong value);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate ulong    GetCompletedValueDelegate(IntPtr fence);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int      SetEventOnCompletionDelegate(IntPtr fence, ulong value, IntPtr hEvent);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int      QueryInterfaceDelegate(IntPtr pThis, ref Guid riid, out IntPtr ppvObject);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int      MapDelegate(IntPtr resource, uint subresource, ref D3D12_RANGE readRange, out IntPtr data);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate ulong    GetGPUVirtualAddressDelegate(IntPtr resource);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate IntPtr   GetBufferPointerDelegate(IntPtr blob);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate IntPtr   GetBufferSizeDelegate(IntPtr blob);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate void     GetCPUDescriptorHandleForHeapStartDelegate(IntPtr heap, out D3D12_CPU_DESCRIPTOR_HANDLE handle);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate void     GetGPUDescriptorHandleForHeapStartDelegate(IntPtr heap, out D3D12_GPU_DESCRIPTOR_HANDLE handle);",

    // ── Instance fields ───────────────────────────────────────────────────────
    "    IntPtr device, commandQueue, swapChain, rtvHeap, srvUavHeap;",
    "    IntPtr[] renderTargets = new IntPtr[FRAME_COUNT];",
    "    IntPtr commandAllocator, computeCommandAllocator;",
    "    IntPtr graphicsRootSignature, computeRootSignature;",
    "    IntPtr graphicsPso, computePso;",
    "    IntPtr commandList, computeCommandList;",
    "    IntPtr positionBuffer, colorBuffer, constantBuffer;",
    "    IntPtr fence, fenceEvent;",
    "    ulong  fenceValue;",
    "    uint   frameIndex;",
    "    uint   rtvDescriptorSize, srvUavDescriptorSize;",
    "    IntPtr constantBufferPtr;",
    "",
    "    // Harmonograph parameters (animated each frame)",
    "    float A1 = 50f, f1 = 2f, p1 = 1f / 16f, d1 = 0.02f;",
    "    float A2 = 50f, f2 = 2f, p2 = 3f / 2f,  d2 = 0.0315f;",
    "    float A3 = 50f, f3 = 2f, p3 = 13f / 15f,d3 = 0.02f;",
    "    float A4 = 50f, f4 = 2f, p4 = 1f,        d4 = 0.02f;",
    "    const float PI2 = 6.283185307179586f;",
    "    Random rand = new Random();",
    "",
    "    // Keep a GC root for the WndProc delegate",
    "    static WndProcDelegate wndProcDelegate;",

    // ── Helper: CheckResult ───────────────────────────────────────────────────
    "    void CheckResult(int hr, string message) {",
    "        if (hr < 0) throw new Exception(string.Format(\"FAILED: {0} (HRESULT: 0x{1:X8})\", message, hr));",
    "    }",

    // ── Helper: Log ───────────────────────────────────────────────────────────
    "    void Log(string message) {",
    "        string line = \"[INFO] \" + message;",
    "        Console.WriteLine(line);",
    "        OutputDebugStringA(line);",
    "    }",

    // ── Helper: VTable read + delegate ───────────────────────────────────────
    "    static T GetFn<T>(IntPtr obj, int slot) where T : class {",
    "        IntPtr vt  = Marshal.ReadIntPtr(obj);",
    "        IntPtr ptr = Marshal.ReadIntPtr(vt, slot * IntPtr.Size);",
    "        return Marshal.GetDelegateForFunctionPointer(ptr, typeof(T)) as T;",
    "    }",

    // ── Helper: CPU heap start ────────────────────────────────────────────────
    "    IntPtr GetCPUHeapStart(IntPtr heap) {",
    "        D3D12_CPU_DESCRIPTOR_HANDLE h;",
    "        GetFn<GetCPUDescriptorHandleForHeapStartDelegate>(heap, 9)(heap, out h);",
    "        return h.ptr;",
    "    }",

    // ── Helper: GPU heap start ────────────────────────────────────────────────
    "    D3D12_GPU_DESCRIPTOR_HANDLE GetGPUHeapStart(IntPtr heap) {",
    "        D3D12_GPU_DESCRIPTOR_HANDLE h;",
    "        GetFn<GetGPUDescriptorHandleForHeapStartDelegate>(heap, 10)(heap, out h);",
    "        return h;",
    "    }",

    // ── Helper: compile shader from file ─────────────────────────────────────
    "    IntPtr CompileShader(string filename, string entryPoint, string target) {",
    "        IntPtr blob  = IntPtr.Zero;",
    "        IntPtr error = IntPtr.Zero;",
    "        int hr = D3DCompileFromFile(filename, IntPtr.Zero, IntPtr.Zero, entryPoint, target, 0, 0, out blob, out error);",
    "        if (hr < 0) {",
    "            if (error != IntPtr.Zero) {",
    "                IntPtr msgPtr = GetFn<GetBufferPointerDelegate>(error, 3)(error);",
    "                Console.WriteLine(\"Shader error: \" + Marshal.PtrToStringAnsi(msgPtr));",
    "            }",
    "            throw new Exception(string.Format(\"Failed to compile {0}: 0x{1:X8}\", entryPoint, hr));",
    "        }",
    "        return blob;",
    "    }",

    // ── Helper: blob buffer pointer / size ────────────────────────────────────
    "    IntPtr BlobPtr(IntPtr blob)  { return GetFn<GetBufferPointerDelegate>(blob, 3)(blob); }",
    "    IntPtr BlobSize(IntPtr blob) { return GetFn<GetBufferSizeDelegate>(blob, 4)(blob); }",

    // ── Helper: create SRV ────────────────────────────────────────────────────
    "    void CreateSRV(IntPtr resource, D3D12_SHADER_RESOURCE_VIEW_DESC desc, D3D12_CPU_DESCRIPTOR_HANDLE handle) {",
    "        GetFn<CreateSRVDelegate>(device, 18)(device, resource, ref desc, handle);",
    "    }",

    // ── EnableDebugLayer ──────────────────────────────────────────────────────
    "    void EnableDebugLayer() {",
    "        Log(\"Enabling Debug Layer...\");",
    "        Guid uuid = IID_ID3D12Debug;",
    "        IntPtr dbg;",
    "        int hr = D3D12GetDebugInterface(ref uuid, out dbg);",
    "        if (hr >= 0 && dbg != IntPtr.Zero) {",
    "            GetFn<EnableDebugLayerDelegate>(dbg, 3)(dbg);",
    "            Marshal.Release(dbg);",
    "            Log(\"Debug Layer Enabled.\");",
    "        }",
    "    }",

    // ── LoadPipeline ──────────────────────────────────────────────────────────
    "    void LoadPipeline(IntPtr hwnd) {",
    "        Log(\"LoadPipeline started.\");",
    "",
    "        // DXGI factory",
    "        Guid factoryGuid = IID_IDXGIFactory4;",
    "        IntPtr factory;",
    "        CheckResult(CreateDXGIFactory1(ref factoryGuid, out factory), \"CreateDXGIFactory1\");",
    "",
    "        // D3D12 device",
    "        Guid deviceGuid = IID_ID3D12Device;",
    "        CheckResult(D3D12CreateDevice(IntPtr.Zero, D3D_FEATURE_LEVEL_12_0, ref deviceGuid, out device), \"D3D12CreateDevice\");",
    "",
    "        // Command queue",
    "        var queueDesc = new D3D12_COMMAND_QUEUE_DESC { Type = 0, Priority = 0, Flags = 0, NodeMask = 0 };",
    "        IntPtr vTable = Marshal.ReadIntPtr(device);",
    "        Guid queueGuid = IID_ID3D12CommandQueue;",
    "        CheckResult(GetFn<CreateCommandQueueDelegate>(device, 8)(device, ref queueDesc, ref queueGuid, out commandQueue), \"CreateCommandQueue\");",
    "",
    "        // Swap chain",
    "        var scDesc = new DXGI_SWAP_CHAIN_DESC1 {",
    "            Width = WIDTH, Height = HEIGHT, Format = DXGI_FORMAT_R8G8B8A8_UNORM,",
    "            Stereo = 0, SampleDesc = new DXGI_SAMPLE_DESC { Count = 1, Quality = 0 },",
    "            BufferUsage = 0x20, BufferCount = FRAME_COUNT,",
    "            Scaling = 1, SwapEffect = 4, AlphaMode = 0, Flags = 0",
    "        };",
    "        IntPtr tempSC;",
    "        CheckResult(GetFn<CreateSwapChainForHwndDelegate>(factory, 15)(factory, commandQueue, hwnd, ref scDesc, IntPtr.Zero, IntPtr.Zero, out tempSC), \"CreateSwapChainForHwnd\");",
    "",
    "        // QueryInterface to IDXGISwapChain3 (for GetCurrentBackBufferIndex)",
    "        Guid sc3Guid = IID_IDXGISwapChain3;",
    "        CheckResult(GetFn<QueryInterfaceDelegate>(tempSC, 0)(tempSC, ref sc3Guid, out swapChain), \"QueryInterface IDXGISwapChain3\");",
    "        Marshal.Release(tempSC);",
    "",
    "        // RTV descriptor heap",
    "        var rtvHeapDesc = new D3D12_DESCRIPTOR_HEAP_DESC { Type = 2, NumDescriptors = FRAME_COUNT, Flags = 0, NodeMask = 0 };",
    "        Guid heapGuid = IID_ID3D12DescriptorHeap;",
    "        CheckResult(GetFn<CreateDescriptorHeapDelegate>(device, 14)(device, ref rtvHeapDesc, ref heapGuid, out rtvHeap), \"CreateDescriptorHeap(RTV)\");",
    "        rtvDescriptorSize = GetFn<GetDescriptorHandleIncrementSizeDelegate>(device, 15)(device, 2);",
    "        Log(\"RTV Heap Created.\");",
    "",
    "        // SRV/UAV/CBV descriptor heap (5 slots: UAVÁE, SRVÁE, CBVÁE)",
    "        var srvUavHeapDesc = new D3D12_DESCRIPTOR_HEAP_DESC { Type = 0, NumDescriptors = 5, Flags = 1, NodeMask = 0 };",
    "        CheckResult(GetFn<CreateDescriptorHeapDelegate>(device, 14)(device, ref srvUavHeapDesc, ref heapGuid, out srvUavHeap), \"CreateDescriptorHeap(SRV/UAV)\");",
    "        srvUavDescriptorSize = GetFn<GetDescriptorHandleIncrementSizeDelegate>(device, 15)(device, 0);",
    "        Log(\"SRV/UAV Heap Created.\");",
    "",
    "        // Render target views",
    "        D3D12_CPU_DESCRIPTOR_HANDLE rtvHandle = new D3D12_CPU_DESCRIPTOR_HANDLE { ptr = GetCPUHeapStart(rtvHeap) };",
    "        Guid resourceGuid = IID_ID3D12Resource;",
    "        for (int i = 0; i < FRAME_COUNT; i++) {",
    "            CheckResult(GetFn<GetBufferDelegate>(swapChain, 9)(swapChain, (uint)i, ref resourceGuid, out renderTargets[i]),",
    "                        string.Format(\"GetBuffer[{0}]\", i));",
    "            GetFn<CreateRenderTargetViewDelegate>(device, 20)(device, renderTargets[i], IntPtr.Zero, rtvHandle);",
    "            rtvHandle.ptr = IntPtr.Add(rtvHandle.ptr, (int)rtvDescriptorSize);",
    "        }",
    "        Log(\"RTVs Created.\");",
    "",
    "        // Command allocators (graphics + compute)",
    "        Guid allocGuid = IID_ID3D12CommandAllocator;",
    "        CheckResult(GetFn<CreateCommandAllocatorDelegate>(device, 9)(device, 0, ref allocGuid, out commandAllocator), \"CreateCommandAllocator(Graphics)\");",
    "        CheckResult(GetFn<CreateCommandAllocatorDelegate>(device, 9)(device, 0, ref allocGuid, out computeCommandAllocator), \"CreateCommandAllocator(Compute)\");",
    "        Log(\"Command Allocators Created.\");",
    "",
    "        Marshal.Release(factory);",
    "        Log(\"LoadPipeline finished.\");",
    "    }",

    // ── LoadAssets ────────────────────────────────────────────────────────────
    "    void LoadAssets() {",
    "        Log(\"LoadAssets started.\");",
    "",
    "        // ── Compute root signature (UAVÁE + CBVÁE) ─────────────────────",
    "        var uavRange = new D3D12_DESCRIPTOR_RANGE {",
    "            RangeType = D3D12_DESCRIPTOR_RANGE_TYPE_UAV, NumDescriptors = 2,",
    "            BaseShaderRegister = 0, RegisterSpace = 0, OffsetInDescriptorsFromTableStart = -1",
    "        };",
    "        var cbvRange = new D3D12_DESCRIPTOR_RANGE {",
    "            RangeType = D3D12_DESCRIPTOR_RANGE_TYPE_CBV, NumDescriptors = 1,",
    "            BaseShaderRegister = 0, RegisterSpace = 0, OffsetInDescriptorsFromTableStart = -1",
    "        };",
    "        GCHandle uavRangeH = GCHandle.Alloc(uavRange, GCHandleType.Pinned);",
    "        GCHandle cbvRangeH = GCHandle.Alloc(cbvRange, GCHandleType.Pinned);",
    "",
    "        var computeParams = new D3D12_ROOT_PARAMETER[2];",
    "        computeParams[0] = new D3D12_ROOT_PARAMETER { ParameterType = 0,",
    "            DescriptorTable = new D3D12_ROOT_DESCRIPTOR_TABLE { NumDescriptorRanges = 1, pDescriptorRanges = uavRangeH.AddrOfPinnedObject() },",
    "            ShaderVisibility = 0 };",
    "        computeParams[1] = new D3D12_ROOT_PARAMETER { ParameterType = 0,",
    "            DescriptorTable = new D3D12_ROOT_DESCRIPTOR_TABLE { NumDescriptorRanges = 1, pDescriptorRanges = cbvRangeH.AddrOfPinnedObject() },",
    "            ShaderVisibility = 0 };",
    "        GCHandle computeParamsH = GCHandle.Alloc(computeParams, GCHandleType.Pinned);",
    "",
    "        var computeRSDesc = new D3D12_ROOT_SIGNATURE_DESC {",
    "            NumParameters = 2, pParameters = computeParamsH.AddrOfPinnedObject(),",
    "            NumStaticSamplers = 0, pStaticSamplers = IntPtr.Zero, Flags = 0",
    "        };",
    "        IntPtr computeSigBlob, errBlob1;",
    "        D3D12SerializeRootSignature(ref computeRSDesc, D3D_ROOT_SIGNATURE_VERSION_1, out computeSigBlob, out errBlob1);",
    "",
    "        Guid rootSigGuid = IID_ID3D12RootSignature;",
    "        CheckResult(GetFn<CreateRootSignatureDelegate>(device, 16)(device, 0,",
    "            BlobPtr(computeSigBlob), BlobSize(computeSigBlob), ref rootSigGuid, out computeRootSignature),",
    "            \"CreateRootSignature(Compute)\");",
    "",
    "        // ── Graphics root signature (SRVÁE + CBVÁE) ────────────────────",
    "        var srvRange = new D3D12_DESCRIPTOR_RANGE {",
    "            RangeType = D3D12_DESCRIPTOR_RANGE_TYPE_SRV, NumDescriptors = 2,",
    "            BaseShaderRegister = 0, RegisterSpace = 0, OffsetInDescriptorsFromTableStart = -1",
    "        };",
    "        GCHandle srvRangeH = GCHandle.Alloc(srvRange, GCHandleType.Pinned);",
    "",
    "        var graphicsParams = new D3D12_ROOT_PARAMETER[2];",
    "        graphicsParams[0] = new D3D12_ROOT_PARAMETER { ParameterType = 0,",
    "            DescriptorTable = new D3D12_ROOT_DESCRIPTOR_TABLE { NumDescriptorRanges = 1, pDescriptorRanges = srvRangeH.AddrOfPinnedObject() },",
    "            ShaderVisibility = 1 };",
    "        graphicsParams[1] = new D3D12_ROOT_PARAMETER { ParameterType = 0,",
    "            DescriptorTable = new D3D12_ROOT_DESCRIPTOR_TABLE { NumDescriptorRanges = 1, pDescriptorRanges = cbvRangeH.AddrOfPinnedObject() },",
    "            ShaderVisibility = 1 };",
    "        GCHandle graphicsParamsH = GCHandle.Alloc(graphicsParams, GCHandleType.Pinned);",
    "",
    "        var graphicsRSDesc = new D3D12_ROOT_SIGNATURE_DESC {",
    "            NumParameters = 2, pParameters = graphicsParamsH.AddrOfPinnedObject(),",
    "            NumStaticSamplers = 0, pStaticSamplers = IntPtr.Zero, Flags = 0",
    "        };",
    "        IntPtr graphicsSigBlob, errBlob2;",
    "        D3D12SerializeRootSignature(ref graphicsRSDesc, D3D_ROOT_SIGNATURE_VERSION_1, out graphicsSigBlob, out errBlob2);",
    "        CheckResult(GetFn<CreateRootSignatureDelegate>(device, 16)(device, 0,",
    "            BlobPtr(graphicsSigBlob), BlobSize(graphicsSigBlob), ref rootSigGuid, out graphicsRootSignature),",
    "            \"CreateRootSignature(Graphics)\");",
    "",
    "        // ── Compile shaders from hello.hlsl ─────────────────────────────",
    "        IntPtr csBlob = CompileShader(\"hello.hlsl\", \"CSMain\", \"cs_5_0\");",
    "        IntPtr vsBlob = CompileShader(\"hello.hlsl\", \"VSMain\", \"vs_5_0\");",
    "        IntPtr psBlob = CompileShader(\"hello.hlsl\", \"PSMain\", \"ps_5_0\");",
    "        Log(\"Shaders compiled.\");",
    "",
    "        // ── Compute PSO ─────────────────────────────────────────────────",
    "        var computePsoDesc = new D3D12_COMPUTE_PIPELINE_STATE_DESC {",
    "            pRootSignature = computeRootSignature,",
    "            CS = new D3D12_SHADER_BYTECODE { pShaderBytecode = BlobPtr(csBlob), BytecodeLength = BlobSize(csBlob) }",
    "        };",
    "        Guid psoGuid = IID_ID3D12PipelineState;",
    "        CheckResult(GetFn<CreateComputePipelineStateDelegate>(device, 11)(device, ref computePsoDesc, ref psoGuid, out computePso), \"CreateComputePipelineState\");",
    "",
    "        // ── Graphics PSO (line strip, no input layout) ──────────────────",
    "        var graphicsPsoDesc = new D3D12_GRAPHICS_PIPELINE_STATE_DESC {",
    "            pRootSignature = graphicsRootSignature,",
    "            VS = new D3D12_SHADER_BYTECODE { pShaderBytecode = BlobPtr(vsBlob), BytecodeLength = BlobSize(vsBlob) },",
    "            PS = new D3D12_SHADER_BYTECODE { pShaderBytecode = BlobPtr(psBlob), BytecodeLength = BlobSize(psBlob) },",
    "            BlendState = new D3D12_BLEND_DESC {",
    "                RT0 = new D3D12_RENDER_TARGET_BLEND_DESC {",
    "                    BlendEnable = 0, LogicOpEnable = 0,",
    "                    SrcBlend = 2, DestBlend = 1, BlendOp = 1,",
    "                    SrcBlendAlpha = 2, DestBlendAlpha = 1, BlendOpAlpha = 1,",
    "                    RenderTargetWriteMask = 0xF",
    "                }",
    "            },",
    "            SampleMask      = uint.MaxValue,",
    "            RasterizerState = new D3D12_RASTERIZER_DESC { FillMode = 3, CullMode = 1, DepthClipEnable = 1 },",
    "            DepthStencilState = new D3D12_DEPTH_STENCIL_DESC { DepthEnable = 0, StencilEnable = 0 },",
    "            PrimitiveTopologyType = 2,   // D3D12_PRIMITIVE_TOPOLOGY_TYPE_LINE",
    "            NumRenderTargets = 1,",
    "            RTVFormats = new uint[] { DXGI_FORMAT_R8G8B8A8_UNORM, 0, 0, 0, 0, 0, 0, 0 },",
    "            SampleDesc = new DXGI_SAMPLE_DESC { Count = 1, Quality = 0 }",
    "        };",
    "        CheckResult(GetFn<CreateGraphicsPipelineStateDelegate>(device, 10)(device, ref graphicsPsoDesc, ref psoGuid, out graphicsPso), \"CreateGraphicsPipelineState\");",
    "",
    "        // ── GPU buffers: position + color (UAV-flagged, COMMON state) ───",
    "        var defaultHeap = new D3D12_HEAP_PROPERTIES { Type = 1, CPUPageProperty = 0, MemoryPoolPreference = 0, CreationNodeMask = 1, VisibleNodeMask = 1 };",
    "        var uploadHeap  = new D3D12_HEAP_PROPERTIES { Type = 2, CPUPageProperty = 0, MemoryPoolPreference = 0, CreationNodeMask = 1, VisibleNodeMask = 1 };",
    "",
    "        var bufferDesc = new D3D12_RESOURCE_DESC {",
    "            Dimension = 1, Alignment = 0, Width = (ulong)(VERTEX_COUNT * 16), Height = 1,",
    "            DepthOrArraySize = 1, MipLevels = 1, Format = 0,",
    "            SampleDesc = new DXGI_SAMPLE_DESC { Count = 1, Quality = 0 },",
    "            Layout = 1, Flags = 0x4   // D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS",
    "        };",
    "        Guid resGuid = IID_ID3D12Resource;",
    "        CheckResult(GetFn<CreateCommittedResourceDelegate>(device, 27)(device, ref defaultHeap, 0, ref bufferDesc, 0, IntPtr.Zero, ref resGuid, out positionBuffer), \"CreateResource(Position)\");",
    "        CheckResult(GetFn<CreateCommittedResourceDelegate>(device, 27)(device, ref defaultHeap, 0, ref bufferDesc, 0, IntPtr.Zero, ref resGuid, out colorBuffer),    \"CreateResource(Color)\");",
    "",
    "        // ── Constant buffer (upload heap, UPLOAD state) ─────────────────",
    "        var cbDesc = new D3D12_RESOURCE_DESC {",
    "            Dimension = 1, Alignment = 0, Width = 256, Height = 1,",
    "            DepthOrArraySize = 1, MipLevels = 1, Format = 0,",
    "            SampleDesc = new DXGI_SAMPLE_DESC { Count = 1, Quality = 0 },",
    "            Layout = 1, Flags = 0",
    "        };",
    "        CheckResult(GetFn<CreateCommittedResourceDelegate>(device, 27)(device, ref uploadHeap, 0, ref cbDesc, 0x1, IntPtr.Zero, ref resGuid, out constantBuffer), \"CreateResource(ConstantBuffer)\");",
    "",
    "        // Keep constant buffer persistently mapped",
    "        D3D12_RANGE readRange = new D3D12_RANGE();",
    "        CheckResult(GetFn<MapDelegate>(constantBuffer, 8)(constantBuffer, 0, ref readRange, out constantBufferPtr), \"Map ConstantBuffer\");",
    "",
    "        // ── Descriptors ─────────────────────────────────────────────────",
    "        D3D12_CPU_DESCRIPTOR_HANDLE heapHandle = new D3D12_CPU_DESCRIPTOR_HANDLE { ptr = GetCPUHeapStart(srvUavHeap) };",
    "",
    "        // Slot 0, 1: UAVs for compute write",
    "        var uavDesc = new D3D12_UNORDERED_ACCESS_VIEW_DESC {",
    "            Format = 0, ViewDimension = 1,",
    "            Buffer_FirstElement = 0, Buffer_NumElements = VERTEX_COUNT, Buffer_StructureByteStride = 16",
    "        };",
    "        GetFn<CreateUnorderedAccessViewDelegate>(device, 19)(device, positionBuffer, IntPtr.Zero, ref uavDesc, heapHandle);",
    "        heapHandle.ptr = IntPtr.Add(heapHandle.ptr, (int)srvUavDescriptorSize);",
    "        GetFn<CreateUnorderedAccessViewDelegate>(device, 19)(device, colorBuffer, IntPtr.Zero, ref uavDesc, heapHandle);",
    "        heapHandle.ptr = IntPtr.Add(heapHandle.ptr, (int)srvUavDescriptorSize);",
    "",
    "        // Slot 2, 3: SRVs for vertex shader read",
    "        // D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING = 0x1688 = 5768",
    "        var srvDesc = new D3D12_SHADER_RESOURCE_VIEW_DESC {",
    "            Format = 0, ViewDimension = D3D12_SRV_DIMENSION_BUFFER,",
    "            Shader4ComponentMapping = 5768,",
    "            Buffer_FirstElement = 0, Buffer_NumElements = VERTEX_COUNT, Buffer_StructureByteStride = 16",
    "        };",
    "        CreateSRV(positionBuffer, srvDesc, heapHandle);",
    "        heapHandle.ptr = IntPtr.Add(heapHandle.ptr, (int)srvUavDescriptorSize);",
    "        CreateSRV(colorBuffer, srvDesc, heapHandle);",
    "        heapHandle.ptr = IntPtr.Add(heapHandle.ptr, (int)srvUavDescriptorSize);",
    "",
    "        // Slot 4: CBV",
    "        ulong cbGpuAddr = GetFn<GetGPUVirtualAddressDelegate>(constantBuffer, 11)(constantBuffer);",
    "        var cbvDesc = new D3D12_CONSTANT_BUFFER_VIEW_DESC { BufferLocation = cbGpuAddr, SizeInBytes = 256 };",
    "        GetFn<CreateConstantBufferViewDelegate>(device, 17)(device, ref cbvDesc, heapHandle);",
    "        Log(\"Descriptors Created.\");",
    "",
    "        // ── Command lists ────────────────────────────────────────────────",
    "        Guid cmdListGuid = IID_ID3D12GraphicsCommandList;",
    "        CheckResult(GetFn<CreateCommandListDelegate>(device, 12)(device, 0, 0, commandAllocator, graphicsPso, ref cmdListGuid, out commandList), \"CreateCommandList(Graphics)\");",
    "        CheckResult(GetFn<CreateCommandListDelegate>(device, 12)(device, 0, 0, computeCommandAllocator, computePso, ref cmdListGuid, out computeCommandList), \"CreateCommandList(Compute)\");",
    "        GetFn<CloseCommandListDelegate>(commandList, 9)(commandList);",
    "        GetFn<CloseCommandListDelegate>(computeCommandList, 9)(computeCommandList);",
    "",
    "        // ── Fence ────────────────────────────────────────────────────────",
    "        Guid fenceGuid = IID_ID3D12Fence;",
    "        CheckResult(GetFn<CreateFenceDelegate>(device, 36)(device, 0, 0, ref fenceGuid, out fence), \"CreateFence\");",
    "        fenceValue = 1;",
    "        fenceEvent = CreateEvent(IntPtr.Zero, false, false, null);",
    "",
    "        // Free GCHandles",
    "        uavRangeH.Free(); cbvRangeH.Free(); srvRangeH.Free();",
    "        computeParamsH.Free(); graphicsParamsH.Free();",
    "",
    "        Log(\"LoadAssets finished.\");",
    "    }",

    // ── WaitForPreviousFrame ──────────────────────────────────────────────────
    "    void WaitForPreviousFrame() {",
    "        ulong cur = fenceValue;",
    "        GetFn<SignalDelegate>(commandQueue, 14)(commandQueue, fence, cur);",
    "        fenceValue++;",
    "        if (GetFn<GetCompletedValueDelegate>(fence, 8)(fence) < cur) {",
    "            GetFn<SetEventOnCompletionDelegate>(fence, 9)(fence, cur, fenceEvent);",
    "            WaitForSingleObject(fenceEvent, INFINITE);",
    "        }",
    "        frameIndex = GetFn<GetCurrentBackBufferIndexDelegate>(swapChain, 36)(swapChain);",
    "    }",

    // ── Render ────────────────────────────────────────────────────────────────
    "    void Render() {",
    "        // Animate harmonograph parameters",
    "        f1 = (f1 + (float)rand.NextDouble() / 200f) % 10f;",
    "        f2 = (f2 + (float)rand.NextDouble() / 200f) % 10f;",
    "        p1 += PI2 * 0.5f / 360f;",
    "",
    "        // Upload constant buffer",
    "        var cbData = new HarmonographParams {",
    "            A1 = A1, f1 = f1, p1 = p1, d1 = d1,",
    "            A2 = A2, f2 = f2, p2 = p2, d2 = d2,",
    "            A3 = A3, f3 = f3, p3 = p3, d3 = d3,",
    "            A4 = A4, f4 = f4, p4 = p4, d4 = d4,",
    "            max_num = VERTEX_COUNT,",
    "            resolutionX = WIDTH, resolutionY = HEIGHT",
    "        };",
    "        Marshal.StructureToPtr(cbData, constantBufferPtr, false);",
    "",
    "        // ── Compute pass ─────────────────────────────────────────────────",
    "        GetFn<ResetCommandAllocatorDelegate>(computeCommandAllocator, 8)(computeCommandAllocator);",
    "        GetFn<ResetCommandListDelegate>(computeCommandList, 10)(computeCommandList, computeCommandAllocator, computePso);",
    "",
    "        IntPtr[] heaps = new IntPtr[] { srvUavHeap };",
    "        GetFn<SetDescriptorHeapsDelegate>(computeCommandList, 28)(computeCommandList, 1, heaps);",
    "        GetFn<SetComputeRootSignatureDelegate>(computeCommandList, 29)(computeCommandList, computeRootSignature);",
    "",
    "        // Param 0: UAV table (slots 0-1)",
    "        D3D12_GPU_DESCRIPTOR_HANDLE gpuH = GetGPUHeapStart(srvUavHeap);",
    "        GetFn<SetComputeRootDescriptorTableDelegate>(computeCommandList, 31)(computeCommandList, 0, gpuH);",
    "        // Param 1: CBV table (slot 4)",
    "        gpuH.ptr += srvUavDescriptorSize * 4;",
    "        GetFn<SetComputeRootDescriptorTableDelegate>(computeCommandList, 31)(computeCommandList, 1, gpuH);",
    "",
    "        GetFn<DispatchDelegate>(computeCommandList, 14)(computeCommandList, (uint)((VERTEX_COUNT + 63) / 64), 1, 1);",
    "",
    "        // Transition buffers UAV ↁESRV",
    "        var barrierPos = new D3D12_RESOURCE_BARRIER { Type = 0, Flags = 0, pResource = positionBuffer, Subresource = unchecked((uint)-1), StateBefore = 0x8, StateAfter = 0x40 };",
    "        var barrierCol = new D3D12_RESOURCE_BARRIER { Type = 0, Flags = 0, pResource = colorBuffer,    Subresource = unchecked((uint)-1), StateBefore = 0x8, StateAfter = 0x40 };",
    "        GetFn<ResourceBarrierDelegate>(computeCommandList, 26)(computeCommandList, 1, ref barrierPos);",
    "        GetFn<ResourceBarrierDelegate>(computeCommandList, 26)(computeCommandList, 1, ref barrierCol);",
    "",
    "        GetFn<CloseCommandListDelegate>(computeCommandList, 9)(computeCommandList);",
    "        IntPtr[] computeLists = new IntPtr[] { computeCommandList };",
    "        GetFn<ExecuteCommandListsDelegate>(commandQueue, 10)(commandQueue, 1, computeLists);",
    "",
    "        // ── Graphics pass ─────────────────────────────────────────────────",
    "        GetFn<ResetCommandAllocatorDelegate>(commandAllocator, 8)(commandAllocator);",
    "        GetFn<ResetCommandListDelegate>(commandList, 10)(commandList, commandAllocator, graphicsPso);",
    "",
    "        GetFn<SetDescriptorHeapsDelegate>(commandList, 28)(commandList, 1, heaps);",
    "        GetFn<SetGraphicsRootSignatureDelegate>(commandList, 30)(commandList, graphicsRootSignature);",
    "",
    "        // Param 0: SRV table (slots 2-3)",
    "        gpuH = GetGPUHeapStart(srvUavHeap);",
    "        gpuH.ptr += srvUavDescriptorSize * 2;",
    "        GetFn<SetGraphicsRootDescriptorTableDelegate>(commandList, 32)(commandList, 0, gpuH);",
    "        // Param 1: CBV table (slot 4)",
    "        gpuH.ptr += srvUavDescriptorSize * 2;",
    "        GetFn<SetGraphicsRootDescriptorTableDelegate>(commandList, 32)(commandList, 1, gpuH);",
    "",
    "        var viewport    = new D3D12_VIEWPORT { TopLeftX = 0, TopLeftY = 0, Width = WIDTH, Height = HEIGHT, MinDepth = 0, MaxDepth = 1 };",
    "        var scissorRect = new D3D12_RECT     { left = 0, top = 0, right = WIDTH, bottom = HEIGHT };",
    "        GetFn<RSSetViewportsDelegate>(commandList, 21)(commandList, 1, ref viewport);",
    "        GetFn<RSSetScissorRectsDelegate>(commandList, 22)(commandList, 1, ref scissorRect);",
    "",
    "        // Present ↁERenderTarget",
    "        var rtBarrier = new D3D12_RESOURCE_BARRIER { Type = 0, Flags = 0, pResource = renderTargets[frameIndex], Subresource = unchecked((uint)-1), StateBefore = 0, StateAfter = 4 };",
    "        GetFn<ResourceBarrierDelegate>(commandList, 26)(commandList, 1, ref rtBarrier);",
    "",
    "        D3D12_CPU_DESCRIPTOR_HANDLE rtvHandle = new D3D12_CPU_DESCRIPTOR_HANDLE { ptr = GetCPUHeapStart(rtvHeap) };",
    "        rtvHandle.ptr = IntPtr.Add(rtvHandle.ptr, (int)(frameIndex * rtvDescriptorSize));",
    "",
    "        float[] clearColor = { 0.05f, 0.05f, 0.1f, 1f };",
    "        GetFn<ClearRenderTargetViewDelegate>(commandList, 48)(commandList, rtvHandle, clearColor, 0, IntPtr.Zero);",
    "        GetFn<OMSetRenderTargetsDelegate>(commandList, 46)(commandList, 1, ref rtvHandle, 0, IntPtr.Zero);",
    "",
    "        // Draw line strip",
    "        GetFn<IASetPrimitiveTopologyDelegate>(commandList, 20)(commandList, 3); // D3D_PRIMITIVE_TOPOLOGY_LINESTRIP",
    "        GetFn<DrawInstancedDelegate>(commandList, 12)(commandList, VERTEX_COUNT, 1, 0, 0);",
    "",
    "        // RenderTarget ↁEPresent",
    "        rtBarrier.StateBefore = 4; rtBarrier.StateAfter = 0;",
    "        GetFn<ResourceBarrierDelegate>(commandList, 26)(commandList, 1, ref rtBarrier);",
    "",
    "        // Transition SRV ↁEUAV (ready for next compute pass)",
    "        barrierPos.StateBefore = 0x40; barrierPos.StateAfter = 0x8;",
    "        barrierCol.StateBefore = 0x40; barrierCol.StateAfter = 0x8;",
    "        GetFn<ResourceBarrierDelegate>(commandList, 26)(commandList, 1, ref barrierPos);",
    "        GetFn<ResourceBarrierDelegate>(commandList, 26)(commandList, 1, ref barrierCol);",
    "",
    "        GetFn<CloseCommandListDelegate>(commandList, 9)(commandList);",
    "        IntPtr[] graphicsLists = new IntPtr[] { commandList };",
    "        GetFn<ExecuteCommandListsDelegate>(commandQueue, 10)(commandQueue, 1, graphicsLists);",
    "",
    "        GetFn<PresentDelegate>(swapChain, 8)(swapChain, 1, 0);",
    "        WaitForPreviousFrame();",
    "    }",

    // ── WndProc ───────────────────────────────────────────────────────────────
    "    static IntPtr WndProc(IntPtr hWnd, uint uMsg, IntPtr wParam, IntPtr lParam) {",
    "        if (uMsg == WM_DESTROY) { PostQuitMessage(0); return IntPtr.Zero; }",
    "        return DefWindowProc(hWnd, uMsg, wParam, lParam);",
    "    }",

    // ── Main ──────────────────────────────────────────────────────────────────
    "    public static int Main(string[] args) {",
    "        var app = new Harmonograph();",
    "        try {",
    "            app.EnableDebugLayer();",
    "",
    "            wndProcDelegate = new WndProcDelegate(WndProc);",
    "",
    "            var wndClass = new WNDCLASSEX {",
    "                cbSize        = (uint)Marshal.SizeOf(typeof(WNDCLASSEX)),",
    "                style         = CS_OWNDC,",
    "                lpfnWndProc   = wndProcDelegate,",
    "                hCursor       = LoadCursor(IntPtr.Zero, IDC_ARROW),",
    "                lpszClassName = \"HarmonographDX12\"",
    "            };",
    "            RegisterClassEx(ref wndClass);",
    "",
    "            IntPtr hwnd = CreateWindowEx(0, \"HarmonographDX12\",",
    "                \"DirectX 12 Compute Harmonograph (JScript.NET)\",",
    "                WS_OVERLAPPEDWINDOW | WS_VISIBLE,",
    "                100, 100, WIDTH, HEIGHT,",
    "                IntPtr.Zero, IntPtr.Zero, IntPtr.Zero, IntPtr.Zero);",
    "",
    "            app.LoadPipeline(hwnd);",
    "            app.LoadAssets();",
    "            ShowWindow(hwnd, 1);",
    "",
    "            MSG msg = new MSG();",
    "            while (msg.message != WM_QUIT) {",
    "                if (PeekMessage(out msg, IntPtr.Zero, 0, 0, PM_REMOVE)) {",
    "                    TranslateMessage(ref msg);",
    "                    DispatchMessage(ref msg);",
    "                } else {",
    "                    app.Render();",
    "                }",
    "            }",
    "        } catch (Exception ex) {",
    "            Console.WriteLine(\"[ERROR] \" + ex.Message);",
    "            Console.WriteLine(ex.StackTrace);",
    "            Console.WriteLine(\"Press Enter to exit...\");",
    "            Console.ReadLine();",
    "        }",
    "        return 0;",
    "    }",

    "}" // end class Harmonograph

].join("\n");

// ─── Run ──────────────────────────────────────────────────────────────────────
Main();

