import System;
import System.CodeDom.Compiler;
import Microsoft.CSharp;
import System.Reflection;
import System.Diagnostics;

function LogJs(msg) {
    try { Console.WriteLine(msg); } catch (e) { }
    Debug.WriteLine(msg);
}

function Main() {
    LogJs("Compiling embedded C# DirectX12 raymarching code...");

    var provider = new CSharpCodeProvider();
    var parameters = new CompilerParameters();

    parameters.GenerateInMemory = true;
    parameters.GenerateExecutable = false;
    parameters.CompilerOptions = "/unsafe";

    parameters.ReferencedAssemblies.Add("System.dll");
    parameters.ReferencedAssemblies.Add("System.Numerics.dll");

    var results = provider.CompileAssemblyFromSource(parameters, csharpSource);

    if (results.Errors.HasErrors) {
        LogJs("Compilation failed:");
        for (var i = 0; i < results.Errors.Count; i++) {
            LogJs(results.Errors[i].ToString());
        }
        return;
    }

    LogJs("Compilation successful. Starting application...");

    try {
        var assembly = results.CompiledAssembly;
        var programType = assembly.GetType("Hello");
        var mainMethod = programType.GetMethod("Main", BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static);
        var invokeArgs = new Object[1];
        invokeArgs[0] = new String[0];
        mainMethod.Invoke(null, invokeArgs);
    } catch (e) {
        LogJs("Runtime Error: " + e.ToString());
    }
}
var csharpSource = [
    "using System;",
    "using System.Numerics;",
    "using System.Runtime.InteropServices;",
    "using System.Collections.Generic;",
    "using System.Text;",
    "using System.Diagnostics;",
    "",
    "public class Hello",
    "{",
    "    [StructLayout(LayoutKind.Sequential)]",
    "    public struct POINT",
    "    {",
    "        public int X;",
    "        public int Y;",
    "    }",
    "",
    "    [StructLayout(LayoutKind.Sequential)]",
    "    public struct MSG",
    "    {",
    "        public IntPtr hwnd;",
    "        public uint message;",
    "        public IntPtr wParam;",
    "        public IntPtr lParam;",
    "        public uint time;",
    "        public POINT pt;",
    "    }",
    "",
    "    delegate IntPtr WndProcDelegate(IntPtr hWnd, uint uMsg, IntPtr wParam, IntPtr lParam);",
    "",
    "    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Auto)]",
    "    struct WNDCLASSEX",
    "    {",
    "        public uint cbSize;",
    "        public uint style;",
    "        public WndProcDelegate lpfnWndProc;",
    "        public Int32 cbClsExtra;",
    "        public Int32 cbWndExtra;",
    "        public IntPtr hInstance;",
    "        public IntPtr hIcon;",
    "        public IntPtr hCursor;",
    "        public IntPtr hbrBackground;",
    "        public string lpszMenuName;",
    "        public string lpszClassName;",
    "        public IntPtr hIconSm;",
    "    }",
    "",
    "    [StructLayout(LayoutKind.Sequential)]",
    "    struct RECT",
    "    {",
    "        public int Left;",
    "        public int Top;",
    "        public int Right;",
    "        public int Bottom;",
    "    }",
    "",
    "    [StructLayout(LayoutKind.Sequential)]",
    "    struct PAINTSTRUCT",
    "    {",
    "        public IntPtr hdc;",
    "        public int fErase;",
    "        public RECT rcPaint;",
    "        public int fRestore;",
    "        public int fIncUpdate;",
    "        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 32)]",
    "        public byte[] rgbReserved;",
    "    }",
    "",
    "    const uint WS_OVERLAPPEDWINDOW = 0x0CF0000;",
    "    const uint WS_VISIBLE = 0x10000000;",
    "",
    "    const uint WM_CREATE = 0x0001;",
    "    const uint WM_DESTROY = 0x0002;",
    "    const uint WM_PAINT = 0x000F;",
    "    const uint WM_CLOSE = 0x0010;",
    "    const uint WM_COMMAND = 0x0111;",
    "",
    "    const uint WM_QUIT = 0x0012;",
    "    const uint PM_REMOVE = 0x0001;",
    "",
    "    const uint CS_OWNDC = 0x0020;",
    "",
    "    const int IDC_ARROW = 32512;",
    "",
    "    const uint INFINITE = 0xFFFFFFFF;",
    "",
    "    const int WIDTH = 800;",
    "    const int HEIGHT = 600;",
    "",
    "    [DllImport(\"user32.dll\", CharSet = CharSet.Auto)]",
    "    private static extern bool ShowWindow(IntPtr hWnd, int nCmdShow);",
    "",
    "    [DllImport(\"user32.dll\", CharSet = CharSet.Auto, SetLastError = true)]",
    "    static extern IntPtr LoadCursor(IntPtr hInstance, int lpCursorName);",
    "",
    "    [DllImport(\"user32.dll\", EntryPoint = \"RegisterClassEx\", CharSet = CharSet.Auto, SetLastError = true)]",
    "    static extern ushort RegisterClassEx([In] ref WNDCLASSEX lpwcx);",
    "",
    "    [DllImport(\"user32.dll\", CharSet = CharSet.Auto, SetLastError = true)]",
    "    static extern IntPtr CreateWindowEx(",
    "        uint dwExStyle,",
    "        string lpClassName,",
    "        string lpWindowName,",
    "        uint dwStyle,",
    "        int x,",
    "        int y,",
    "        int nWidth,",
    "        int nHeight,",
    "        IntPtr hWndParent,",
    "        IntPtr hMenu,",
    "        IntPtr hInstance,",
    "        IntPtr lpParam",
    "    );",
    "",
    "    [DllImport(\"user32.dll\", CharSet = CharSet.Auto)]",
    "    static extern bool PeekMessage(out MSG lpMsg, IntPtr hWnd, uint wMsgFilterMin, uint wMsgFilterMax, uint wRemoveMsg);",
    "",
    "    [DllImport(\"user32.dll\", CharSet = CharSet.Auto)]",
    "    static extern bool GetMessage(out MSG lpMsg, IntPtr hWnd, uint wMsgFilterMin, uint wMsgFilterMax);",
    "",
    "    [DllImport(\"user32.dll\", CharSet = CharSet.Auto)]",
    "    static extern bool TranslateMessage([In] ref MSG lpMsg);",
    "",
    "    [DllImport(\"user32.dll\", CharSet = CharSet.Auto)]",
    "    static extern IntPtr DispatchMessage([In] ref MSG lpMsg);",
    "",
    "    [DllImport(\"user32.dll\", CharSet = CharSet.Auto)]",
    "    static extern void PostQuitMessage(int nExitCode);",
    "",
    "    [DllImport(\"user32.dll\", CharSet = CharSet.Auto)]",
    "    static extern IntPtr DefWindowProc(IntPtr hWnd, uint uMsg, IntPtr wParam, IntPtr lParam);",
    "",
    "    [DllImport(\"user32.dll\", CharSet = CharSet.Auto)]",
    "    static extern IntPtr BeginPaint(IntPtr hWnd, out PAINTSTRUCT lpPaint);",
    "",
    "    [DllImport(\"user32.dll\", CharSet = CharSet.Auto)]",
    "    static extern IntPtr EndPaint(IntPtr hWnd, ref PAINTSTRUCT lpPaint);",
    "",
    "    const uint D3D_FEATURE_LEVEL_11_0 = 0xb000;",
    "",
    "    const uint D3D_ROOT_SIGNATURE_VERSION_1 = 0x1;",
    "            ",
    "    // Vertex structure for fullscreen quad (just position)",
    "    [StructLayout(LayoutKind.Sequential)]",
    "    struct Vertex",
    "    {",
    "        public float X, Y;  // position only",
    "    }",
    "",
    "    // Constant buffer for shader parameters",
    "    [StructLayout(LayoutKind.Sequential)]",
    "    struct ConstantBufferData",
    "    {",
    "        public float iTime;",
    "        public float iResolutionX;",
    "        public float iResolutionY;",
    "        public float padding;",
    "    }",
    "",
    "    [DllImport(\"d3d12.dll\")]",
    "    private static extern int D3D12GetDebugInterface([In] ref Guid riid, [Out] out IntPtr ppvDebug);",
    "",
    "    [ComImport]",
    "    [Guid(\"344488b7-6846-474b-b989-f027448245e0\")]",
    "    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]",
    "    private interface ID3D12Debug",
    "    {",
    "        void EnableDebugLayer();",
    "    }",
    "",
    "    [DllImport(\"d3d12.dll\")]",
    "    public static extern int D3D12CreateDevice(",
    "        IntPtr pAdapter,",
    "        uint MinimumFeatureLevel,",
    "        ref Guid riid,",
    "        out IntPtr ppDevice);",
    "",
    "    [DllImport(\"dxgi.dll\")]",
    "    private static extern int CreateDXGIFactory2(uint Flags, ref Guid riid, out IntPtr ppFactory);",
    "",
    "    private static DXGI_SWAP_CHAIN_DESC1 swapChainDesc1;",
    "",
    "    [DllImport(\"d3d12.dll\")]",
    "    public static extern int D3D12SerializeRootSignature(",
    "        ref D3D12_ROOT_SIGNATURE_DESC pRootSignature,",
    "        uint Version,",
    "        out IntPtr ppBlob,",
    "        out IntPtr ppErrorBlob);",
    "",
    "    [DllImport(\"kernel32.dll\")]",
    "    public static extern IntPtr CreateEvent(",
    "        IntPtr lpEventAttributes,",
    "        bool bManualReset,",
    "        bool bInitialState,",
    "        string lpName);",
    "",
    "    [DllImport(\"kernel32.dll\", SetLastError = true)]",
    "    public static extern UInt32 WaitForSingleObject(IntPtr hHandle, UInt32 dwMilliseconds);",
    "",
    "    [DllImport(\"kernel32.dll\", SetLastError = true)]",
    "    [return: MarshalAs(UnmanagedType.Bool)]",
    "    public static extern bool CloseHandle(IntPtr hObject);",
    "",
    "    [DllImport(\"kernel32.dll\", CharSet = CharSet.Unicode)]",
    "    private static extern void OutputDebugString(string lpOutputString);",
    "",
    "    private static void Log(string message)",
    "    {",
    "        string line = \"[\" + DateTime.Now.ToString(\"HH:mm:ss.fff\") + \"] \" + message;",
    "        try { Console.WriteLine(line); } catch { }",
    "        OutputDebugString(line);",
    "    }",
    "",
    "    [DllImport(\"d3dcompiler_47.dll\", CallingConvention = CallingConvention.Winapi)]",
    "    private static extern int D3DCompileFromFile(",
    "        [MarshalAs(UnmanagedType.LPWStr)] string pFileName,",
    "        IntPtr pDefines,",
    "        IntPtr pInclude,",
    "        [MarshalAs(UnmanagedType.LPStr)] string pEntrypoint,",
    "        [MarshalAs(UnmanagedType.LPStr)] string pTarget,",
    "        uint Flags1,",
    "        uint Flags2,",
    "        out IntPtr ppCode,",
    "        out IntPtr ppErrorMsgs",
    "    );",
    "",
    "    [StructLayout(LayoutKind.Sequential)]",
    "    struct D3D12_COMMAND_QUEUE_DESC",
    "    {",
    "        public D3D12_COMMAND_LIST_TYPE Type;",
    "        public int Priority;",
    "        public D3D12_COMMAND_QUEUE_FLAGS Flags;",
    "        public uint NodeMask;",
    "    }",
    "",
    "    enum D3D12_COMMAND_LIST_TYPE",
    "    {",
    "        D3D12_COMMAND_LIST_TYPE_DIRECT = 0,",
    "        D3D12_COMMAND_LIST_TYPE_BUNDLE = 1,",
    "        D3D12_COMMAND_LIST_TYPE_COMPUTE = 2,",
    "        D3D12_COMMAND_LIST_TYPE_COPY = 3",
    "    }",
    "",
    "    [Flags]",
    "    enum D3D12_COMMAND_QUEUE_FLAGS",
    "    {",
    "        D3D12_COMMAND_QUEUE_FLAG_NONE = 0,",
    "        D3D12_COMMAND_QUEUE_FLAG_DISABLE_GPU_TIMEOUT = 0x1",
    "    }",
    "",
    "    [StructLayout(LayoutKind.Sequential)]",
    "    struct D3D12_DESCRIPTOR_HEAP_DESC",
    "    {",
    "        public D3D12_DESCRIPTOR_HEAP_TYPE Type;",
    "        public uint NumDescriptors;",
    "        public D3D12_DESCRIPTOR_HEAP_FLAGS Flags;",
    "        public uint NodeMask;",
    "    }",
    "",
    "    enum D3D12_DESCRIPTOR_HEAP_TYPE",
    "    {",
    "        D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV = 0,",
    "        D3D12_DESCRIPTOR_HEAP_TYPE_SAMPLER = 1,",
    "        D3D12_DESCRIPTOR_HEAP_TYPE_RTV = 2,",
    "        D3D12_DESCRIPTOR_HEAP_TYPE_DSV = 3",
    "    }",
    "",
    "    [Flags]",
    "    enum D3D12_DESCRIPTOR_HEAP_FLAGS",
    "    {",
    "        D3D12_DESCRIPTOR_HEAP_FLAG_NONE = 0,",
    "        D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE = 0x1",
    "    }",
    "",
    "    [StructLayout(LayoutKind.Sequential)]",
    "    public struct D3D12_CPU_DESCRIPTOR_HANDLE",
    "    {",
    "        public IntPtr ptr;",
    "    }",
    "",
    "    [StructLayout(LayoutKind.Sequential)]",
    "    public struct D3D12_GPU_DESCRIPTOR_HANDLE",
    "    {",
    "        public ulong ptr;",
    "    }",
    "",
    "    public enum D3D12_RESOURCE_STATES",
    "    {",
    "        D3D12_RESOURCE_STATE_COMMON = 0,",
    "        D3D12_RESOURCE_STATE_VERTEX_AND_CONSTANT_BUFFER = 0x1,",
    "        D3D12_RESOURCE_STATE_INDEX_BUFFER = 0x2,",
    "        D3D12_RESOURCE_STATE_RENDER_TARGET = 0x4,",
    "        D3D12_RESOURCE_STATE_UNORDERED_ACCESS = 0x8,",
    "        D3D12_RESOURCE_STATE_DEPTH_WRITE = 0x10,",
    "        D3D12_RESOURCE_STATE_DEPTH_READ = 0x20,",
    "        D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE = 0x40,",
    "        D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE = 0x80,",
    "        D3D12_RESOURCE_STATE_STREAM_OUT = 0x100,",
    "        D3D12_RESOURCE_STATE_INDIRECT_ARGUMENT = 0x200,",
    "        D3D12_RESOURCE_STATE_COPY_DEST = 0x400,",
    "        D3D12_RESOURCE_STATE_COPY_SOURCE = 0x800,",
    "        D3D12_RESOURCE_STATE_RESOLVE_DEST = 0x1000,",
    "        D3D12_RESOURCE_STATE_RESOLVE_SOURCE = 0x2000,",
    "        D3D12_RESOURCE_STATE_GENERIC_READ = ",
    "            (D3D12_RESOURCE_STATE_VERTEX_AND_CONSTANT_BUFFER | ",
    "             D3D12_RESOURCE_STATE_INDEX_BUFFER |",
    "             D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE |",
    "             D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE |",
    "             D3D12_RESOURCE_STATE_INDIRECT_ARGUMENT |",
    "             D3D12_RESOURCE_STATE_COPY_SOURCE),",
    "        D3D12_RESOURCE_STATE_PRESENT = 0,",
    "        D3D12_RESOURCE_STATE_PREDICATION = 0x200",
    "    }",
    "",
    "    [StructLayout(LayoutKind.Sequential)]",
    "    struct D3D12_RESOURCE_DESC",
    "    {",
    "        public D3D12_RESOURCE_DIMENSION Dimension;",
    "        public ulong Alignment;",
    "        public ulong Width;",
    "        public uint Height;",
    "        public ushort DepthOrArraySize;",
    "        public ushort MipLevels;",
    "        public uint Format;",
    "        public DXGI_SAMPLE_DESC SampleDesc;",
    "        public D3D12_TEXTURE_LAYOUT Layout;",
    "        public D3D12_RESOURCE_FLAGS Flags;",
    "    }",
    "",
    "    enum D3D12_RESOURCE_DIMENSION",
    "    {",
    "        D3D12_RESOURCE_DIMENSION_UNKNOWN = 0,",
    "        D3D12_RESOURCE_DIMENSION_BUFFER = 1,",
    "        D3D12_RESOURCE_DIMENSION_TEXTURE1D = 2,",
    "        D3D12_RESOURCE_DIMENSION_TEXTURE2D = 3,",
    "        D3D12_RESOURCE_DIMENSION_TEXTURE3D = 4",
    "    }",
    "",
    "    [StructLayout(LayoutKind.Sequential)]",
    "    public struct DXGI_SAMPLE_DESC",
    "    {",
    "        public uint Count;",
    "        public uint Quality;",
    "    }",
    "",
    "    enum D3D12_TEXTURE_LAYOUT",
    "    {",
    "        D3D12_TEXTURE_LAYOUT_UNKNOWN = 0,",
    "        D3D12_TEXTURE_LAYOUT_ROW_MAJOR = 1,",
    "        D3D12_TEXTURE_LAYOUT_64KB_UNDEFINED_SWIZZLE = 2,",
    "        D3D12_TEXTURE_LAYOUT_64KB_STANDARD_SWIZZLE = 3",
    "    }",
    "",
    "    [Flags]",
    "    enum D3D12_RESOURCE_FLAGS",
    "    {",
    "        D3D12_RESOURCE_FLAG_NONE = 0,",
    "        D3D12_RESOURCE_FLAG_ALLOW_RENDER_TARGET = 0x1,",
    "        D3D12_RESOURCE_FLAG_ALLOW_DEPTH_STENCIL = 0x2,",
    "        D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS = 0x4,",
    "        D3D12_RESOURCE_FLAG_DENY_SHADER_RESOURCE = 0x8,",
    "        D3D12_RESOURCE_FLAG_ALLOW_CROSS_ADAPTER = 0x10,",
    "        D3D12_RESOURCE_FLAG_ALLOW_SIMULTANEOUS_ACCESS = 0x20",
    "    }",
    "",
    "    [StructLayout(LayoutKind.Sequential)]",
    "    public struct D3D12_HEAP_PROPERTIES",
    "    {",
    "        public D3D12_HEAP_TYPE Type;",
    "        public D3D12_CPU_PAGE_PROPERTY CPUPageProperty;",
    "        public D3D12_MEMORY_POOL MemoryPoolPreference;",
    "        public uint CreationNodeMask;",
    "        public uint VisibleNodeMask;",
    "    }",
    "",
    "    public enum D3D12_HEAP_TYPE",
    "    {",
    "        D3D12_HEAP_TYPE_DEFAULT = 1,",
    "        D3D12_HEAP_TYPE_UPLOAD = 2,",
    "        D3D12_HEAP_TYPE_READBACK = 3,",
    "        D3D12_HEAP_TYPE_CUSTOM = 4",
    "    }",
    "",
    "    public enum D3D12_CPU_PAGE_PROPERTY",
    "    {",
    "        D3D12_CPU_PAGE_PROPERTY_UNKNOWN = 0,",
    "        D3D12_CPU_PAGE_PROPERTY_NOT_AVAILABLE = 1,",
    "        D3D12_CPU_PAGE_PROPERTY_WRITE_COMBINE = 2,",
    "        D3D12_CPU_PAGE_PROPERTY_WRITE_BACK = 3",
    "    }",
    "",
    "    public enum D3D12_MEMORY_POOL",
    "    {",
    "        D3D12_MEMORY_POOL_UNKNOWN = 0,",
    "        D3D12_MEMORY_POOL_L0 = 1,",
    "        D3D12_MEMORY_POOL_L1 = 2",
    "    }",
    "",
    "    [Flags]",
    "    public enum D3D12_HEAP_FLAGS",
    "    {",
    "        D3D12_HEAP_FLAG_NONE = 0,",
    "        D3D12_HEAP_FLAG_SHARED = 0x1,",
    "        D3D12_HEAP_FLAG_DENY_BUFFERS = 0x4,",
    "        D3D12_HEAP_FLAG_ALLOW_DISPLAY = 0x8,",
    "        D3D12_HEAP_FLAG_SHARED_CROSS_ADAPTER = 0x20,",
    "        D3D12_HEAP_FLAG_DENY_RT_DS_TEXTURES = 0x40,",
    "        D3D12_HEAP_FLAG_DENY_NON_RT_DS_TEXTURES = 0x80,",
    "        D3D12_HEAP_FLAG_ALLOW_ALL_BUFFERS_AND_TEXTURES = 0,",
    "        D3D12_HEAP_FLAG_ALLOW_ONLY_BUFFERS = D3D12_HEAP_FLAG_DENY_RT_DS_TEXTURES | D3D12_HEAP_FLAG_DENY_NON_RT_DS_TEXTURES,",
    "        D3D12_HEAP_FLAG_ALLOW_ONLY_NON_RT_DS_TEXTURES = D3D12_HEAP_FLAG_DENY_BUFFERS | D3D12_HEAP_FLAG_DENY_RT_DS_TEXTURES,",
    "    }",
    "",
    "    [StructLayout(LayoutKind.Sequential)]",
    "    struct D3D12_GRAPHICS_PIPELINE_STATE_DESC",
    "    {",
    "        public IntPtr pRootSignature;",
    "        public D3D12_SHADER_BYTECODE VS;",
    "        public D3D12_SHADER_BYTECODE PS;",
    "        public D3D12_SHADER_BYTECODE DS;",
    "        public D3D12_SHADER_BYTECODE HS;",
    "        public D3D12_SHADER_BYTECODE GS;",
    "        public D3D12_STREAM_OUTPUT_DESC StreamOutput;",
    "        public D3D12_BLEND_DESC BlendState;",
    "        public uint SampleMask;",
    "        public D3D12_RASTERIZER_DESC RasterizerState;",
    "        public D3D12_DEPTH_STENCIL_DESC DepthStencilState;",
    "        public D3D12_INPUT_LAYOUT_DESC InputLayout;",
    "        public D3D12_INDEX_BUFFER_STRIP_CUT_VALUE IBStripCutValue;",
    "        public D3D12_PRIMITIVE_TOPOLOGY_TYPE PrimitiveTopologyType;",
    "        public uint NumRenderTargets;",
    "        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 8)]",
    "        public uint[] RTVFormats;",
    "        public uint DSVFormat;",
    "        public DXGI_SAMPLE_DESC SampleDesc;",
    "        public uint NodeMask;",
    "        public D3D12_CACHED_PIPELINE_STATE CachedPSO;",
    "        public D3D12_PIPELINE_STATE_FLAGS Flags;",
    "    }",
    "",
    "    [StructLayout(LayoutKind.Sequential)]",
    "    struct D3D12_SHADER_BYTECODE",
    "    {",
    "        public IntPtr pShaderBytecode;",
    "        public IntPtr BytecodeLength;",
    "    }",
    "",
    "    [StructLayout(LayoutKind.Sequential)]",
    "    struct D3D12_INPUT_LAYOUT_DESC",
    "    {",
    "        public IntPtr pInputElementDescs;",
    "        public uint NumElements;",
    "    }",
    "",
    "    [StructLayout(LayoutKind.Sequential)]",
    "    struct D3D12_INPUT_ELEMENT_DESC",
    "    {",
    "        public IntPtr SemanticName;",
    "        public uint SemanticIndex;",
    "        public uint Format;",
    "        public uint InputSlot;",
    "        public uint AlignedByteOffset;",
    "        public D3D12_INPUT_CLASSIFICATION InputSlotClass;",
    "        public uint InstanceDataStepRate;",
    "    }",
    "",
    "    enum D3D12_INPUT_CLASSIFICATION",
    "    {",
    "        D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA = 0,",
    "        D3D12_INPUT_CLASSIFICATION_PER_INSTANCE_DATA = 1",
    "    }",
    "",
    "    [StructLayout(LayoutKind.Sequential)]",
    "    public struct D3D12_ROOT_SIGNATURE_DESC",
    "    {",
    "        public uint NumParameters;",
    "        public IntPtr pParameters;",
    "        public uint NumStaticSamplers;",
    "        public IntPtr pStaticSamplers;",
    "        public D3D12_ROOT_SIGNATURE_FLAGS Flags;",
    "    }",
    "",
    "    [StructLayout(LayoutKind.Sequential)]",
    "    public struct D3D12_ROOT_PARAMETER",
    "    {",
    "        public D3D12_ROOT_PARAMETER_TYPE ParameterType;",
    "        public D3D12_ROOT_DESCRIPTOR_TABLE DescriptorTable;",
    "        public D3D12_SHADER_VISIBILITY ShaderVisibility;",
    "    }",
    "",
    "    public enum D3D12_ROOT_PARAMETER_TYPE",
    "    {",
    "        D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE = 0,",
    "        D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS = 1,",
    "        D3D12_ROOT_PARAMETER_TYPE_CBV = 2,",
    "        D3D12_ROOT_PARAMETER_TYPE_SRV = 3,",
    "        D3D12_ROOT_PARAMETER_TYPE_UAV = 4",
    "    }",
    "",
    "    [StructLayout(LayoutKind.Sequential)]",
    "    public struct D3D12_ROOT_DESCRIPTOR_TABLE",
    "    {",
    "        public uint NumDescriptorRanges;",
    "        public IntPtr pDescriptorRanges;",
    "    }",
    "",
    "    [StructLayout(LayoutKind.Sequential)]",
    "    public struct D3D12_DESCRIPTOR_RANGE",
    "    {",
    "        public D3D12_DESCRIPTOR_RANGE_TYPE RangeType;",
    "        public uint NumDescriptors;",
    "        public uint BaseShaderRegister;",
    "        public uint RegisterSpace;",
    "        public uint OffsetInDescriptorsFromTableStart;",
    "    }",
    "",
    "    public enum D3D12_DESCRIPTOR_RANGE_TYPE",
    "    {",
    "        D3D12_DESCRIPTOR_RANGE_TYPE_SRV = 0,",
    "        D3D12_DESCRIPTOR_RANGE_TYPE_UAV = 1,",
    "        D3D12_DESCRIPTOR_RANGE_TYPE_CBV = 2,",
    "        D3D12_DESCRIPTOR_RANGE_TYPE_SAMPLER = 3",
    "    }",
    "",
    "    public enum D3D12_SHADER_VISIBILITY",
    "    {",
    "        D3D12_SHADER_VISIBILITY_ALL = 0,",
    "        D3D12_SHADER_VISIBILITY_VERTEX = 1,",
    "        D3D12_SHADER_VISIBILITY_HULL = 2,",
    "        D3D12_SHADER_VISIBILITY_DOMAIN = 3,",
    "        D3D12_SHADER_VISIBILITY_GEOMETRY = 4,",
    "        D3D12_SHADER_VISIBILITY_PIXEL = 5",
    "    }",
    "",
    "    [Flags]",
    "    public enum D3D12_ROOT_SIGNATURE_FLAGS",
    "    {",
    "        D3D12_ROOT_SIGNATURE_FLAG_NONE = 0,",
    "        D3D12_ROOT_SIGNATURE_FLAG_ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT = 0x1,",
    "        D3D12_ROOT_SIGNATURE_FLAG_DENY_VERTEX_SHADER_ROOT_ACCESS = 0x2,",
    "        D3D12_ROOT_SIGNATURE_FLAG_DENY_HULL_SHADER_ROOT_ACCESS = 0x4,",
    "        D3D12_ROOT_SIGNATURE_FLAG_DENY_DOMAIN_SHADER_ROOT_ACCESS = 0x8,",
    "        D3D12_ROOT_SIGNATURE_FLAG_DENY_GEOMETRY_SHADER_ROOT_ACCESS = 0x10,",
    "        D3D12_ROOT_SIGNATURE_FLAG_DENY_PIXEL_SHADER_ROOT_ACCESS = 0x20,",
    "        D3D12_ROOT_SIGNATURE_FLAG_ALLOW_STREAM_OUTPUT = 0x40",
    "    }",
    "",
    "    [StructLayout(LayoutKind.Sequential)]",
    "    public struct D3D12_VERTEX_BUFFER_VIEW",
    "    {",
    "        public ulong BufferLocation;",
    "        public uint SizeInBytes;",
    "        public uint StrideInBytes;",
    "    }",
    "",
    "    [StructLayout(LayoutKind.Sequential)]",
    "    public struct D3D12_CONSTANT_BUFFER_VIEW_DESC",
    "    {",
    "        public ulong BufferLocation;",
    "        public uint SizeInBytes;",
    "    }",
    "",
    "    [Flags]",
    "    public enum D3D12_FENCE_FLAGS",
    "    {",
    "        D3D12_FENCE_FLAG_NONE = 0,",
    "        D3D12_FENCE_FLAG_SHARED = 0x1,",
    "        D3D12_FENCE_FLAG_SHARED_CROSS_ADAPTER = 0x2",
    "    }",
    "",
    "    [StructLayout(LayoutKind.Sequential)]",
    "    struct D3D12_STREAM_OUTPUT_DESC",
    "    {",
    "        public IntPtr pSODeclaration;",
    "        public uint NumEntries;",
    "        public IntPtr pBufferStrides;",
    "        public uint NumStrides;",
    "        public uint RasterizedStream;",
    "    }",
    "",
    "    [StructLayout(LayoutKind.Sequential)]",
    "    struct D3D12_BLEND_DESC",
    "    {",
    "        public int AlphaToCoverageEnable;",
    "        public int IndependentBlendEnable;",
    "        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 8)]",
    "        public D3D12_RENDER_TARGET_BLEND_DESC[] RenderTarget;",
    "    }",
    "",
    "    [StructLayout(LayoutKind.Sequential)]",
    "    struct D3D12_RENDER_TARGET_BLEND_DESC",
    "    {",
    "        public int BlendEnable;",
    "        public int LogicOpEnable;",
    "        public D3D12_BLEND SrcBlend;",
    "        public D3D12_BLEND DestBlend;",
    "        public D3D12_BLEND_OP BlendOp;",
    "        public D3D12_BLEND SrcBlendAlpha;",
    "        public D3D12_BLEND DestBlendAlpha;",
    "        public D3D12_BLEND_OP BlendOpAlpha;",
    "        public D3D12_LOGIC_OP LogicOp;",
    "        public byte RenderTargetWriteMask;",
    "    }",
    "",
    "    enum D3D12_BLEND",
    "    {",
    "        D3D12_BLEND_ZERO = 1,",
    "        D3D12_BLEND_ONE = 2,",
    "        D3D12_BLEND_SRC_COLOR = 3,",
    "        D3D12_BLEND_INV_SRC_COLOR = 4,",
    "        D3D12_BLEND_SRC_ALPHA = 5,",
    "        D3D12_BLEND_INV_SRC_ALPHA = 6,",
    "        D3D12_BLEND_DEST_ALPHA = 7,",
    "        D3D12_BLEND_INV_DEST_ALPHA = 8,",
    "        D3D12_BLEND_DEST_COLOR = 9,",
    "        D3D12_BLEND_INV_DEST_COLOR = 10,",
    "        D3D12_BLEND_SRC_ALPHA_SAT = 11,",
    "        D3D12_BLEND_BLEND_FACTOR = 14,",
    "        D3D12_BLEND_INV_BLEND_FACTOR = 15,",
    "        D3D12_BLEND_SRC1_COLOR = 16,",
    "        D3D12_BLEND_INV_SRC1_COLOR = 17,",
    "        D3D12_BLEND_SRC1_ALPHA = 18,",
    "        D3D12_BLEND_INV_SRC1_ALPHA = 19",
    "    }",
    "",
    "    enum D3D12_BLEND_OP",
    "    {",
    "        D3D12_BLEND_OP_ADD = 1,",
    "        D3D12_BLEND_OP_SUBTRACT = 2,",
    "        D3D12_BLEND_OP_REV_SUBTRACT = 3,",
    "        D3D12_BLEND_OP_MIN = 4,",
    "        D3D12_BLEND_OP_MAX = 5",
    "    }",
    "",
    "    enum D3D12_LOGIC_OP",
    "    {",
    "        D3D12_LOGIC_OP_CLEAR = 0,",
    "        D3D12_LOGIC_OP_SET = 1,",
    "        D3D12_LOGIC_OP_COPY = 2,",
    "        D3D12_LOGIC_OP_COPY_INVERTED = 3,",
    "        D3D12_LOGIC_OP_NOOP = 4",
    "    }",
    "",
    "    [StructLayout(LayoutKind.Sequential)]",
    "    struct D3D12_RASTERIZER_DESC",
    "    {",
    "        public D3D12_FILL_MODE FillMode;",
    "        public D3D12_CULL_MODE CullMode;",
    "        public int FrontCounterClockwise;",
    "        public int DepthBias;",
    "        public float DepthBiasClamp;",
    "        public float SlopeScaledDepthBias;",
    "        public int DepthClipEnable;",
    "        public int MultisampleEnable;",
    "        public int AntialiasedLineEnable;",
    "        public uint ForcedSampleCount;",
    "        public D3D12_CONSERVATIVE_RASTERIZATION_MODE ConservativeRaster;",
    "    }",
    "",
    "    enum D3D12_FILL_MODE",
    "    {",
    "        D3D12_FILL_MODE_WIREFRAME = 2,",
    "        D3D12_FILL_MODE_SOLID = 3",
    "    }",
    "",
    "    enum D3D12_CULL_MODE",
    "    {",
    "        D3D12_CULL_MODE_NONE = 1,",
    "        D3D12_CULL_MODE_FRONT = 2,",
    "        D3D12_CULL_MODE_BACK = 3",
    "    }",
    "",
    "    enum D3D12_CONSERVATIVE_RASTERIZATION_MODE",
    "    {",
    "        D3D12_CONSERVATIVE_RASTERIZATION_MODE_OFF = 0,",
    "        D3D12_CONSERVATIVE_RASTERIZATION_MODE_ON = 1",
    "    }",
    "",
    "    [StructLayout(LayoutKind.Sequential)]",
    "    struct D3D12_DEPTH_STENCIL_DESC",
    "    {",
    "        public int DepthEnable;",
    "        public D3D12_DEPTH_WRITE_MASK DepthWriteMask;",
    "        public D3D12_COMPARISON_FUNC DepthFunc;",
    "        public int StencilEnable;",
    "        public byte StencilReadMask;",
    "        public byte StencilWriteMask;",
    "        public D3D12_DEPTH_STENCILOP_DESC FrontFace;",
    "        public D3D12_DEPTH_STENCILOP_DESC BackFace;",
    "    }",
    "",
    "    enum D3D12_DEPTH_WRITE_MASK",
    "    {",
    "        D3D12_DEPTH_WRITE_MASK_ZERO = 0,",
    "        D3D12_DEPTH_WRITE_MASK_ALL = 1",
    "    }",
    "",
    "    enum D3D12_COMPARISON_FUNC",
    "    {",
    "        D3D12_COMPARISON_FUNC_NEVER = 1,",
    "        D3D12_COMPARISON_FUNC_LESS = 2,",
    "        D3D12_COMPARISON_FUNC_EQUAL = 3,",
    "        D3D12_COMPARISON_FUNC_LESS_EQUAL = 4,",
    "        D3D12_COMPARISON_FUNC_GREATER = 5,",
    "        D3D12_COMPARISON_FUNC_NOT_EQUAL = 6,",
    "        D3D12_COMPARISON_FUNC_GREATER_EQUAL = 7,",
    "        D3D12_COMPARISON_FUNC_ALWAYS = 8",
    "    }",
    "",
    "    [StructLayout(LayoutKind.Sequential)]",
    "    struct D3D12_DEPTH_STENCILOP_DESC",
    "    {",
    "        public D3D12_STENCIL_OP StencilFailOp;",
    "        public D3D12_STENCIL_OP StencilDepthFailOp;",
    "        public D3D12_STENCIL_OP StencilPassOp;",
    "        public D3D12_COMPARISON_FUNC StencilFunc;",
    "    }",
    "",
    "    enum D3D12_STENCIL_OP",
    "    {",
    "        D3D12_STENCIL_OP_KEEP = 1,",
    "        D3D12_STENCIL_OP_ZERO = 2,",
    "        D3D12_STENCIL_OP_REPLACE = 3,",
    "        D3D12_STENCIL_OP_INCR_SAT = 4,",
    "        D3D12_STENCIL_OP_DECR_SAT = 5,",
    "        D3D12_STENCIL_OP_INVERT = 6,",
    "        D3D12_STENCIL_OP_INCR = 7,",
    "        D3D12_STENCIL_OP_DECR = 8",
    "    }",
    "",
    "    enum D3D12_INDEX_BUFFER_STRIP_CUT_VALUE",
    "    {",
    "        D3D12_INDEX_BUFFER_STRIP_CUT_VALUE_DISABLED = 0,",
    "        D3D12_INDEX_BUFFER_STRIP_CUT_VALUE_0xFFFF = 1,",
    "        D3D12_INDEX_BUFFER_STRIP_CUT_VALUE_0xFFFFFFFF = 2",
    "    }",
    "",
    "    enum D3D12_PRIMITIVE_TOPOLOGY_TYPE",
    "    {",
    "        D3D12_PRIMITIVE_TOPOLOGY_TYPE_UNDEFINED = 0,",
    "        D3D12_PRIMITIVE_TOPOLOGY_TYPE_POINT = 1,",
    "        D3D12_PRIMITIVE_TOPOLOGY_TYPE_LINE = 2,",
    "        D3D12_PRIMITIVE_TOPOLOGY_TYPE_TRIANGLE = 3,",
    "        D3D12_PRIMITIVE_TOPOLOGY_TYPE_PATCH = 4",
    "    }",
    "",
    "    [StructLayout(LayoutKind.Sequential)]",
    "    struct D3D12_CACHED_PIPELINE_STATE",
    "    {",
    "        public IntPtr pCachedBlob;",
    "        public IntPtr CachedBlobSizeInBytes;",
    "    }",
    "",
    "    enum D3D12_PIPELINE_STATE_FLAGS",
    "    {",
    "        D3D12_PIPELINE_STATE_FLAG_NONE = 0,",
    "        D3D12_PIPELINE_STATE_FLAG_TOOL_DEBUG = 0x1",
    "    }",
    "",
    "    [StructLayout(LayoutKind.Sequential)]",
    "    struct D3D12_VIEWPORT",
    "    {",
    "        public float TopLeftX;",
    "        public float TopLeftY;",
    "        public float Width;",
    "        public float Height;",
    "        public float MinDepth;",
    "        public float MaxDepth;",
    "    }",
    "",
    "    [StructLayout(LayoutKind.Sequential)]",
    "    struct D3D12_RECT",
    "    {",
    "        public int left;",
    "        public int top;",
    "        public int right;",
    "        public int bottom;",
    "    }",
    "",
    "    enum D3D12_RESOURCE_BARRIER_TYPE",
    "    {",
    "        D3D12_RESOURCE_BARRIER_TYPE_TRANSITION = 0,",
    "        D3D12_RESOURCE_BARRIER_TYPE_ALIASING = 1,",
    "        D3D12_RESOURCE_BARRIER_TYPE_UAV = 2",
    "    }",
    "",
    "    enum D3D12_RESOURCE_BARRIER_FLAGS",
    "    {",
    "        D3D12_RESOURCE_BARRIER_FLAG_NONE = 0,",
    "        D3D12_RESOURCE_BARRIER_FLAG_BEGIN_ONLY = 1,",
    "        D3D12_RESOURCE_BARRIER_FLAG_END_ONLY = 2",
    "    }",
    "",
    "    [StructLayout(LayoutKind.Explicit)]",
    "    struct D3D12_RESOURCE_BARRIER",
    "    {",
    "        [FieldOffset(0)]",
    "        public D3D12_RESOURCE_BARRIER_TYPE Type;",
    "        [FieldOffset(4)]",
    "        public D3D12_RESOURCE_BARRIER_FLAGS Flags;",
    "        [FieldOffset(8)]",
    "        public D3D12_RESOURCE_TRANSITION_BARRIER Transition;",
    "    }",
    "",
    "    [StructLayout(LayoutKind.Sequential)]",
    "    struct D3D12_RESOURCE_TRANSITION_BARRIER",
    "    {",
    "        public IntPtr pResource;",
    "        public uint Subresource;",
    "        public D3D12_RESOURCE_STATES StateBefore;",
    "        public D3D12_RESOURCE_STATES StateAfter;",
    "    }",
    "",
    "    [StructLayout(LayoutKind.Sequential)]",
    "    struct D3D12_RANGE",
    "    {",
    "        public IntPtr Begin;",
    "        public IntPtr End;",
    "    }",
    "",
    "    enum D3D_PRIMITIVE_TOPOLOGY",
    "    {",
    "        D3D_PRIMITIVE_TOPOLOGY_UNDEFINED = 0,",
    "        D3D_PRIMITIVE_TOPOLOGY_POINTLIST = 1,",
    "        D3D_PRIMITIVE_TOPOLOGY_LINELIST = 2,",
    "        D3D_PRIMITIVE_TOPOLOGY_LINESTRIP = 3,",
    "        D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST = 4,",
    "        D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP = 5",
    "    }",
    "",
    "    [StructLayout(LayoutKind.Sequential)]",
    "    public struct DXGI_SWAP_CHAIN_DESC1",
    "    {",
    "        public uint Width;",
    "        public uint Height;",
    "        public uint Format;",
    "        public bool Stereo; ",
    "        public DXGI_SAMPLE_DESC SampleDesc;",
    "        public uint BufferUsage;",
    "        public uint BufferCount;",
    "        public DXGI_SCALING Scaling;",
    "        public uint SwapEffect;",
    "        public DXGI_ALPHA_MODE AlphaMode;",
    "        public uint Flags;",
    "    }",
    "",
    "    public enum DXGI_SCALING",
    "    {",
    "        DXGI_SCALING_STRETCH = 0,",
    "        DXGI_SCALING_NONE = 1,",
    "        DXGI_SCALING_ASPECT_RATIO_STRETCH = 2",
    "    }",
    "",
    "    public enum DXGI_ALPHA_MODE",
    "    {",
    "        DXGI_ALPHA_MODE_UNSPECIFIED = 0,",
    "        DXGI_ALPHA_MODE_PREMULTIPLIED = 1,",
    "        DXGI_ALPHA_MODE_STRAIGHT = 2,",
    "        DXGI_ALPHA_MODE_IGNORE = 3",
    "    }",
    "",
    "    [StructLayout(LayoutKind.Sequential)]",
    "    public struct D3D12_CPU_DESCRIPTOR_HANDLE_ARRAY",
    "    {",
    "        public IntPtr ptr;",
    "    }",
    "",
    "    // DXGI formats",
    "    const uint DXGI_FORMAT_UNKNOWN = 0;",
    "    const uint DXGI_FORMAT_R32G32_FLOAT = 16;",
    "    const uint DXGI_FORMAT_R32G32B32_FLOAT = 6;",
    "    const uint DXGI_FORMAT_R32G32B32A32_FLOAT = 2;",
    "    const uint DXGI_FORMAT_R8G8B8A8_UNORM = 28;",
    "",
    "    const uint DXGI_USAGE_RENDER_TARGET_OUTPUT = 0x00000020;",
    "    const uint DXGI_SWAP_EFFECT_FLIP_DISCARD = 4;",
    "    const uint DXGI_SWAP_CHAIN_FLAG_ALLOW_MODE_SWITCH = 2;",
    "    const uint DXGI_SWAP_CHAIN_FLAG_FRAME_LATENCY_WAITABLE_OBJECT = 0x40; // Fixed from 0x80",
    "",
    "    const uint D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES = 0xffffffff;",
    "    const uint D3D12_DESCRIPTOR_RANGE_OFFSET_APPEND = 0xffffffff;",
    "",
    "    // GUIDs",
    "    static readonly Guid IID_IDXGIFactory4 = new Guid(\"1bc6ea02-ef36-464f-bf0c-21ca39e5168a\");",
    "    static readonly Guid IID_IDXGISwapChain3 = new Guid(\"94d99bdb-f1f8-4ab0-b236-7da0170edab1\");",
    "    static readonly Guid IID_ID3D12Device = new Guid(\"189819f1-1db6-4b57-be54-1821339b85f7\");",
    "    static readonly Guid IID_ID3D12CommandQueue = new Guid(\"0ec870a6-5d7e-4c22-8cfc-5baae07616ed\");",
    "    static readonly Guid IID_ID3D12CommandAllocator = new Guid(\"6102dee4-af59-4b09-b999-b44d73f09b24\");",
    "    static readonly Guid IID_ID3D12GraphicsCommandList = new Guid(\"5b160d0f-ac1b-4185-8ba8-b3ae42a5a455\");",
    "    static readonly Guid IID_ID3D12DescriptorHeap = new Guid(\"8efb471d-616c-4f49-90f7-127bb763fa51\");",
    "    static readonly Guid IID_ID3D12Resource = new Guid(\"696442be-a72e-4059-bc79-5b5c98040fad\");",
    "    static readonly Guid IID_ID3D12PipelineState = new Guid(\"765a30f3-f624-4c6f-a828-ace948622445\");",
    "    static readonly Guid IID_ID3D12RootSignature = new Guid(\"c54a6b66-72df-4ee8-8be5-a946a1429214\");",
    "    static readonly Guid IID_ID3D12Fence = new Guid(\"0a753dcf-c4d8-4b91-adf6-be5a60d95a76\");",
    "    static readonly Guid IID_ID3D12Debug = new Guid(\"344488b7-6846-474b-b989-f027448245e0\");",
    "",
    "    // Delegates",
    "    delegate int CreateCommandQueueDelegate(IntPtr device, ref D3D12_COMMAND_QUEUE_DESC desc, ref Guid riid, out IntPtr commandQueue);",
    "    delegate int CreateDescriptorHeapDelegate(IntPtr device, ref D3D12_DESCRIPTOR_HEAP_DESC desc, ref Guid riid, out IntPtr heap);",
    "    delegate uint GetDescriptorHandleIncrementSizeDelegate(IntPtr device, D3D12_DESCRIPTOR_HEAP_TYPE type);",
    "    delegate int GetBufferDelegate(IntPtr swapChain, uint buffer, ref Guid riid, out IntPtr surface);",
    "    delegate void CreateRenderTargetViewDelegate(IntPtr device, IntPtr resource, IntPtr desc, D3D12_CPU_DESCRIPTOR_HANDLE handle);",
    "    delegate void CreateConstantBufferViewDelegate(IntPtr device, ref D3D12_CONSTANT_BUFFER_VIEW_DESC desc, D3D12_CPU_DESCRIPTOR_HANDLE destDescriptor);",
    "    delegate int CreateCommandAllocatorDelegate(IntPtr device, D3D12_COMMAND_LIST_TYPE type, ref Guid riid, out IntPtr allocator);",
    "    delegate int CreateRootSignatureDelegate(IntPtr device, uint nodeMask, IntPtr blobWithRootSignature, IntPtr blobLengthInBytes, ref Guid riid, out IntPtr rootSignature);",
    "    delegate int CreateGraphicsPipelineStateDelegate(IntPtr device, ref D3D12_GRAPHICS_PIPELINE_STATE_DESC desc, ref Guid riid, out IntPtr pipelineState);",
    "    delegate int CreateCommandListDelegate(IntPtr device, uint nodeMask, D3D12_COMMAND_LIST_TYPE type, IntPtr allocator, IntPtr initialState, ref Guid riid, out IntPtr commandList);",
    "    delegate int CloseDelegate(IntPtr commandList);",
    "    delegate int CreateCommittedResourceDelegate(IntPtr device, ref D3D12_HEAP_PROPERTIES heapProperties, D3D12_HEAP_FLAGS heapFlags, ref D3D12_RESOURCE_DESC desc, D3D12_RESOURCE_STATES initialState, IntPtr optimizedClearValue, ref Guid riid, out IntPtr resource);",
    "    delegate int MapDelegate(IntPtr resource, uint subresource, ref D3D12_RANGE readRange, out IntPtr data);",
    "    delegate void UnmapDelegate(IntPtr resource, uint subresource, ref D3D12_RANGE writtenRange);",
    "    delegate ulong GetGPUVirtualAddressDelegate(IntPtr resource);",
    "    delegate int CreateFenceDelegate(IntPtr device, ulong initialValue, D3D12_FENCE_FLAGS flags, ref Guid riid, out IntPtr fence);",
    "    delegate int ResetCommandAllocatorDelegate(IntPtr allocator);",
    "    delegate int ResetCommandListDelegate(IntPtr commandList, IntPtr allocator, IntPtr initialState);",
    "    delegate void SetGraphicsRootSignatureDelegate(IntPtr commandList, IntPtr rootSignature);",
    "    delegate void SetDescriptorHeapsDelegate(IntPtr commandList, uint numDescriptorHeaps, IntPtr[] ppDescriptorHeaps);",
    "    delegate void SetGraphicsRootDescriptorTableDelegate(IntPtr commandList, uint rootParameterIndex, D3D12_GPU_DESCRIPTOR_HANDLE baseDescriptor);",
    "    delegate void RSSetViewportsDelegate(IntPtr commandList, uint numViewports, D3D12_VIEWPORT[] viewports);",
    "    delegate void RSSetScissorRectsDelegate(IntPtr commandList, uint numRects, D3D12_RECT[] rects);",
    "    delegate void ResourceBarrierDelegate(IntPtr commandList, uint numBarriers, D3D12_RESOURCE_BARRIER[] barriers);",
    "    delegate void OMSetRenderTargetsDelegate(IntPtr commandList, uint numRenderTargetDescriptors, D3D12_CPU_DESCRIPTOR_HANDLE_ARRAY[] renderTargetDescriptors, bool RTsSingleHandleToDescriptorRange, IntPtr depthStencilDescriptor);",
    "    delegate void ClearRenderTargetViewDelegate(IntPtr commandList, D3D12_CPU_DESCRIPTOR_HANDLE renderTargetView, float[] colorRGBA, uint numRects, IntPtr rects);",
    "    delegate void IASetPrimitiveTopologyDelegate(IntPtr commandList, D3D_PRIMITIVE_TOPOLOGY topology);",
    "    delegate void IASetVertexBuffersDelegate(IntPtr commandList, uint startSlot, uint numViews, D3D12_VERTEX_BUFFER_VIEW[] views);",
    "    delegate void DrawInstancedDelegate(IntPtr commandList, uint vertexCountPerInstance, uint instanceCount, uint startVertexLocation, uint startInstanceLocation);",
    "    delegate int ExecuteCommandListsDelegate(IntPtr commandQueue, uint numCommandLists, IntPtr[] commandLists);",
    "    delegate int PresentDelegate(IntPtr swapChain, uint syncInterval, uint flags);",
    "    delegate int SignalDelegate(IntPtr commandQueue, IntPtr fence, ulong value);",
    "    delegate ulong GetCompletedValueDelegate(IntPtr fence);",
    "    delegate int SetEventOnCompletionDelegate(IntPtr fence, ulong value, IntPtr hEvent);",
    "    delegate int CreateSwapChainForHwndDelegate(IntPtr factory, IntPtr device, IntPtr hwnd, ref DXGI_SWAP_CHAIN_DESC1 desc, IntPtr fullscreenDesc, IntPtr restrictToOutput, out IntPtr swapChain);",
    "    delegate uint GetCurrentBackBufferIndexDelegate(IntPtr swapChain);",
    "",
    "    // Helper functions",
    "    static class CD3DX12_BLEND_DESC",
    "    {",
    "        public static D3D12_BLEND_DESC Default()",
    "        {",
    "            var desc = new D3D12_BLEND_DESC",
    "            {",
    "                AlphaToCoverageEnable = 0,",
    "                IndependentBlendEnable = 0,",
    "                RenderTarget = new D3D12_RENDER_TARGET_BLEND_DESC[8]",
    "            };",
    "",
    "            for (int i = 0; i < 8; i++)",
    "            {",
    "                desc.RenderTarget[i] = new D3D12_RENDER_TARGET_BLEND_DESC",
    "                {",
    "                    BlendEnable = 0,",
    "                    LogicOpEnable = 0,",
    "                    SrcBlend = D3D12_BLEND.D3D12_BLEND_ONE,",
    "                    DestBlend = D3D12_BLEND.D3D12_BLEND_ZERO,",
    "                    BlendOp = D3D12_BLEND_OP.D3D12_BLEND_OP_ADD,",
    "                    SrcBlendAlpha = D3D12_BLEND.D3D12_BLEND_ONE,",
    "                    DestBlendAlpha = D3D12_BLEND.D3D12_BLEND_ZERO,",
    "                    BlendOpAlpha = D3D12_BLEND_OP.D3D12_BLEND_OP_ADD,",
    "                    LogicOp = D3D12_LOGIC_OP.D3D12_LOGIC_OP_NOOP,",
    "                    RenderTargetWriteMask = 0x0F",
    "                };",
    "            }",
    "            return desc;",
    "        }",
    "    }",
    "",
    "    static class CD3DX12_RASTERIZER_DESC",
    "    {",
    "        public static D3D12_RASTERIZER_DESC Default()",
    "        {",
    "            return new D3D12_RASTERIZER_DESC",
    "            {",
    "                FillMode = D3D12_FILL_MODE.D3D12_FILL_MODE_SOLID,",
    "                CullMode = D3D12_CULL_MODE.D3D12_CULL_MODE_BACK,",
    "                FrontCounterClockwise = 0,",
    "                DepthBias = 0,",
    "                DepthBiasClamp = 0.0f,",
    "                SlopeScaledDepthBias = 0.0f,",
    "                DepthClipEnable = 1,",
    "                MultisampleEnable = 0,",
    "                AntialiasedLineEnable = 0,",
    "                ForcedSampleCount = 0,",
    "                ConservativeRaster = D3D12_CONSERVATIVE_RASTERIZATION_MODE.D3D12_CONSERVATIVE_RASTERIZATION_MODE_OFF",
    "            };",
    "        }",
    "    }",
    "",
    "    static class CD3DX12_DEPTH_STENCIL_DESC",
    "    {",
    "        public static D3D12_DEPTH_STENCIL_DESC Default()",
    "        {",
    "            return new D3D12_DEPTH_STENCIL_DESC",
    "            {",
    "                DepthEnable = 1,",
    "                DepthWriteMask = D3D12_DEPTH_WRITE_MASK.D3D12_DEPTH_WRITE_MASK_ALL,",
    "                DepthFunc = D3D12_COMPARISON_FUNC.D3D12_COMPARISON_FUNC_LESS,",
    "                StencilEnable = 0,",
    "                StencilReadMask = 0xFF,",
    "                StencilWriteMask = 0xFF,",
    "                FrontFace = new D3D12_DEPTH_STENCILOP_DESC",
    "                {",
    "                    StencilFailOp = D3D12_STENCIL_OP.D3D12_STENCIL_OP_KEEP,",
    "                    StencilDepthFailOp = D3D12_STENCIL_OP.D3D12_STENCIL_OP_KEEP,",
    "                    StencilPassOp = D3D12_STENCIL_OP.D3D12_STENCIL_OP_KEEP,",
    "                    StencilFunc = D3D12_COMPARISON_FUNC.D3D12_COMPARISON_FUNC_ALWAYS",
    "                },",
    "                BackFace = new D3D12_DEPTH_STENCILOP_DESC",
    "                {",
    "                    StencilFailOp = D3D12_STENCIL_OP.D3D12_STENCIL_OP_KEEP,",
    "                    StencilDepthFailOp = D3D12_STENCIL_OP.D3D12_STENCIL_OP_KEEP,",
    "                    StencilPassOp = D3D12_STENCIL_OP.D3D12_STENCIL_OP_KEEP,",
    "                    StencilFunc = D3D12_COMPARISON_FUNC.D3D12_COMPARISON_FUNC_ALWAYS",
    "                }",
    "            };",
    "        }",
    "    }",
    "",
    "    static class CD3DX12_RESOURCE_BARRIER",
    "    {",
    "        public static D3D12_RESOURCE_BARRIER Transition(",
    "            IntPtr resource,",
    "            D3D12_RESOURCE_STATES stateBefore,",
    "            D3D12_RESOURCE_STATES stateAfter,",
    "            uint subresource = D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES)",
    "        {",
    "            return new D3D12_RESOURCE_BARRIER",
    "            {",
    "                Type = D3D12_RESOURCE_BARRIER_TYPE.D3D12_RESOURCE_BARRIER_TYPE_TRANSITION,",
    "                Flags = D3D12_RESOURCE_BARRIER_FLAGS.D3D12_RESOURCE_BARRIER_FLAG_NONE,",
    "                Transition = new D3D12_RESOURCE_TRANSITION_BARRIER",
    "                {",
    "                    pResource = resource,",
    "                    Subresource = subresource,",
    "                    StateBefore = stateBefore,",
    "                    StateAfter = stateAfter",
    "                }",
    "            };",
    "        }",
    "    }",
    "",
    "    // Member variables",
    "    const int FrameCount = 2;",
    "",
    "    IntPtr device;",
    "    IntPtr commandQueue;",
    "    IntPtr swapChain;",
    "    IntPtr rtvHeap;",
    "    IntPtr cbvHeap;",
    "    IntPtr commandAllocator;",
    "    IntPtr commandList;",
    "    IntPtr rootSignature;",
    "    IntPtr pipelineState;",
    "    IntPtr vertexBuffer;",
    "    IntPtr constantBuffer;",
    "    IntPtr constantBufferDataBegin;",
    "    IntPtr fence;",
    "    IntPtr fenceEvent;",
    "    ulong fenceValue;",
    "",
    "    IntPtr[] renderTargets = new IntPtr[FrameCount];",
    "    uint rtvDescriptorSize;",
    "    uint cbvDescriptorSize;",
    "    int frameIndex = 0;",
    "",
    "    D3D12_VERTEX_BUFFER_VIEW vertexBufferView;",
    "",
    "    Stopwatch stopwatch;",
    "",
    "    // Fullscreen quad vertices (6 vertices for 2 triangles)",
    "    Vertex[] quadVertices = new Vertex[]",
    "    {",
    "        new Vertex { X = -1.0f, Y = -1.0f },",
    "        new Vertex { X =  1.0f, Y = -1.0f },",
    "        new Vertex { X = -1.0f, Y =  1.0f },",
    "        new Vertex { X = -1.0f, Y =  1.0f },",
    "        new Vertex { X =  1.0f, Y = -1.0f },",
    "        new Vertex { X =  1.0f, Y =  1.0f }",
    "    };",
    "",
    "    // Helper methods",
    "    IntPtr GetCPUDescriptorHandleForHeapStart(IntPtr heap)",
    "    {",
    "        IntPtr vTable = Marshal.ReadIntPtr(heap);",
    "        IntPtr getCpuHandlePtr = Marshal.ReadIntPtr(vTable, 9 * IntPtr.Size);",
    "        ",
    "        var thunk = Marshal.GetDelegateForFunctionPointer<GetCPUDescriptorHandleForHeapStartThunk>(getCpuHandlePtr);",
    "        D3D12_CPU_DESCRIPTOR_HANDLE handle = new D3D12_CPU_DESCRIPTOR_HANDLE();",
    "        thunk(heap, out handle);",
    "        return handle.ptr;",
    "    }",
    "",
    "    D3D12_GPU_DESCRIPTOR_HANDLE GetGPUDescriptorHandleForHeapStart(IntPtr heap)",
    "    {",
    "        IntPtr vTable = Marshal.ReadIntPtr(heap);",
    "        IntPtr getGpuHandlePtr = Marshal.ReadIntPtr(vTable, 10 * IntPtr.Size);",
    "        ",
    "        var thunk = Marshal.GetDelegateForFunctionPointer<GetGPUDescriptorHandleForHeapStartThunk>(getGpuHandlePtr);",
    "        D3D12_GPU_DESCRIPTOR_HANDLE handle = new D3D12_GPU_DESCRIPTOR_HANDLE();",
    "        thunk(heap, out handle);",
    "        return handle;",
    "    }",
    "",
    "    uint GetCurrentBackBufferIndex(IntPtr swapChain)",
    "    {",
    "        IntPtr vTable = Marshal.ReadIntPtr(swapChain);",
    "        IntPtr getCurrentIndexPtr = Marshal.ReadIntPtr(vTable, 36 * IntPtr.Size);",
    "        var getCurrentBackBufferIndex = Marshal.GetDelegateForFunctionPointer<GetCurrentBackBufferIndexDelegate>(getCurrentIndexPtr);",
    "        return getCurrentBackBufferIndex(swapChain);",
    "    }",
    "",
    "    delegate void GetCPUDescriptorHandleForHeapStartThunk(IntPtr heap, out D3D12_CPU_DESCRIPTOR_HANDLE handle);",
    "    delegate void GetGPUDescriptorHandleForHeapStartThunk(IntPtr heap, out D3D12_GPU_DESCRIPTOR_HANDLE handle);",
    "",
    "    static int CreateSwapChainForHwnd(IntPtr factory, IntPtr commandQueue, IntPtr hwnd, ref DXGI_SWAP_CHAIN_DESC1 desc, IntPtr fullscreenDesc, IntPtr restrictToOutput, out IntPtr swapChain)",
    "    {",
    "        IntPtr vTable = Marshal.ReadIntPtr(factory);",
    "        IntPtr createSwapChainForHwndPtr = Marshal.ReadIntPtr(vTable, 15 * IntPtr.Size);",
    "        var createSwapChainForHwnd = Marshal.GetDelegateForFunctionPointer<CreateSwapChainForHwndDelegate>(createSwapChainForHwndPtr);",
    "        return createSwapChainForHwnd(factory, commandQueue, hwnd, ref desc, fullscreenDesc, restrictToOutput, out swapChain);",
    "    }",
    "",
    "    IntPtr CompileShaderFromFile(string fileName, string entryPoint, string target)",
    "    {",
    "        IntPtr shaderBlob;",
    "        IntPtr errorBlob;",
    "        ",
    "        int result = D3DCompileFromFile(fileName, IntPtr.Zero, IntPtr.Zero, entryPoint, target, 0, 0, out shaderBlob, out errorBlob);",
    "        ",
    "        if (result < 0)",
    "        {",
    "            if (errorBlob != IntPtr.Zero)",
    "            {",
    "                IntPtr errorPtr = GetBufferPointer(errorBlob);",
    "                string error = Marshal.PtrToStringAnsi(errorPtr);",
    "                Log(\"Shader compilation error: {error}\");",
    "                Marshal.Release(errorBlob);",
    "            }",
    "            throw new Exception(\"Failed to compile shader: {result:X}\");",
    "        }",
    "        ",
    "        return shaderBlob;",
    "    }",
    "",
    "    IntPtr GetBufferPointer(IntPtr blob)",
    "    {",
    "        IntPtr vTable = Marshal.ReadIntPtr(blob);",
    "        IntPtr getBufferPointerPtr = Marshal.ReadIntPtr(vTable, 3 * IntPtr.Size);",
    "        var getBufferPointer = Marshal.GetDelegateForFunctionPointer<GetBufferPointerDelegate>(getBufferPointerPtr);",
    "        return getBufferPointer(blob);",
    "    }",
    "",
    "    ulong GetBlobSize(IntPtr blob)",
    "    {",
    "        IntPtr vTable = Marshal.ReadIntPtr(blob);",
    "        IntPtr getBufferSizePtr = Marshal.ReadIntPtr(vTable, 4 * IntPtr.Size);",
    "        var getBufferSize = Marshal.GetDelegateForFunctionPointer<GetBufferSizeDelegate>(getBufferSizePtr);",
    "        return getBufferSize(blob);",
    "    }",
    "",
    "    delegate IntPtr GetBufferPointerDelegate(IntPtr blob);",
    "    delegate ulong GetBufferSizeDelegate(IntPtr blob);",
    "",
    "    static byte[] StructArrayToByteArray<T>(T[] array) where T : struct",
    "    {",
    "        int size = Marshal.SizeOf<T>() * array.Length;",
    "        byte[] bytes = new byte[size];",
    "        GCHandle handle = GCHandle.Alloc(array, GCHandleType.Pinned);",
    "        try",
    "        {",
    "            Marshal.Copy(handle.AddrOfPinnedObject(), bytes, 0, size);",
    "        }",
    "        finally",
    "        {",
    "            handle.Free();",
    "        }",
    "        return bytes;",
    "    }",
    "",
    "    private void LoadAssets()",
    "    {",
    "        Log(\"[LoadAssets] - Start\");",
    "",
    "        // Create root signature with CBV",
    "        var cbvRange = new D3D12_DESCRIPTOR_RANGE",
    "        {",
    "            RangeType = D3D12_DESCRIPTOR_RANGE_TYPE.D3D12_DESCRIPTOR_RANGE_TYPE_CBV,",
    "            NumDescriptors = 1,",
    "            BaseShaderRegister = 0,",
    "            RegisterSpace = 0,",
    "            OffsetInDescriptorsFromTableStart = D3D12_DESCRIPTOR_RANGE_OFFSET_APPEND",
    "        };",
    "",
    "        GCHandle cbvRangeHandle = GCHandle.Alloc(new D3D12_DESCRIPTOR_RANGE[] { cbvRange }, GCHandleType.Pinned);",
    "",
    "        var rootParameter = new D3D12_ROOT_PARAMETER",
    "        {",
    "            ParameterType = D3D12_ROOT_PARAMETER_TYPE.D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE,",
    "            DescriptorTable = new D3D12_ROOT_DESCRIPTOR_TABLE",
    "            {",
    "                NumDescriptorRanges = 1,",
    "                pDescriptorRanges = cbvRangeHandle.AddrOfPinnedObject()",
    "            },",
    "            ShaderVisibility = D3D12_SHADER_VISIBILITY.D3D12_SHADER_VISIBILITY_PIXEL",
    "        };",
    "",
    "        GCHandle rootParamHandle = GCHandle.Alloc(new D3D12_ROOT_PARAMETER[] { rootParameter }, GCHandleType.Pinned);",
    "",
    "        D3D12_ROOT_SIGNATURE_DESC rootSignatureDesc = new D3D12_ROOT_SIGNATURE_DESC",
    "        {",
    "            NumParameters = 1,",
    "            pParameters = rootParamHandle.AddrOfPinnedObject(),",
    "            NumStaticSamplers = 0,",
    "            pStaticSamplers = IntPtr.Zero,",
    "            Flags = D3D12_ROOT_SIGNATURE_FLAGS.D3D12_ROOT_SIGNATURE_FLAG_ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT",
    "        };",
    "",
    "        IntPtr signature = IntPtr.Zero;",
    "        IntPtr error = IntPtr.Zero;",
    "",
    "        try",
    "        {",
    "            int result = D3D12SerializeRootSignature(ref rootSignatureDesc, D3D_ROOT_SIGNATURE_VERSION_1, out signature, out error);",
    "",
    "            if (result < 0)",
    "            {",
    "                if (error != IntPtr.Zero)",
    "                {",
    "                    IntPtr errorPtr = GetBufferPointer(error);",
    "                    string errorMsg = Marshal.PtrToStringAnsi(errorPtr);",
    "                    Log(\"Root signature serialization error: {errorMsg}\");",
    "                }",
    "                throw new Exception(\"Failed to serialize root signature: {result:X}\");",
    "            }",
    "",
    "            IntPtr vTable = Marshal.ReadIntPtr(device);",
    "            IntPtr createRootSigPtr = Marshal.ReadIntPtr(vTable, 16 * IntPtr.Size);",
    "            var createRootSignature = Marshal.GetDelegateForFunctionPointer<CreateRootSignatureDelegate>(createRootSigPtr);",
    "",
    "            Guid rootSignatureGuid = IID_ID3D12RootSignature;",
    "            result = createRootSignature(device, 0, GetBufferPointer(signature), (IntPtr)GetBlobSize(signature), ref rootSignatureGuid, out rootSignature);",
    "",
    "            if (result < 0)",
    "            {",
    "                throw new Exception(\"Failed to create root signature: {result:X}\");",
    "            }",
    "            Log(\"Root signature created: {rootSignature:X}\");",
    "        }",
    "        finally",
    "        {",
    "            cbvRangeHandle.Free();",
    "            rootParamHandle.Free();",
    "            if (signature != IntPtr.Zero) Marshal.Release(signature);",
    "            if (error != IntPtr.Zero) Marshal.Release(error);",
    "        }",
    "",
    "        // Compile shaders",
    "        IntPtr vertexShader = CompileShaderFromFile(\"hello.hlsl\", \"VSMain\", \"vs_5_0\");",
    "        IntPtr pixelShader = CompileShaderFromFile(\"hello.hlsl\", \"PSMain\", \"ps_5_0\");",
    "",
    "        // Input layout for fullscreen quad (position only)",
    "        D3D12_INPUT_ELEMENT_DESC[] inputElementDescs = new[]",
    "        {",
    "            new D3D12_INPUT_ELEMENT_DESC",
    "            {",
    "                SemanticName = Marshal.StringToHGlobalAnsi(\"POSITION\"),",
    "                SemanticIndex = 0,",
    "                Format = DXGI_FORMAT_R32G32_FLOAT,",
    "                InputSlot = 0,",
    "                AlignedByteOffset = 0,",
    "                InputSlotClass = D3D12_INPUT_CLASSIFICATION.D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA,",
    "                InstanceDataStepRate = 0",
    "            }",
    "        };",
    "",
    "        GCHandle inputElementsHandle = GCHandle.Alloc(inputElementDescs, GCHandleType.Pinned);",
    "",
    "        D3D12_GRAPHICS_PIPELINE_STATE_DESC psoDesc = new D3D12_GRAPHICS_PIPELINE_STATE_DESC",
    "        {",
    "            pRootSignature = rootSignature,",
    "            VS = new D3D12_SHADER_BYTECODE { pShaderBytecode = GetBufferPointer(vertexShader), BytecodeLength = (IntPtr)GetBlobSize(vertexShader) },",
    "            PS = new D3D12_SHADER_BYTECODE { pShaderBytecode = GetBufferPointer(pixelShader), BytecodeLength = (IntPtr)GetBlobSize(pixelShader) },",
    "            BlendState = CD3DX12_BLEND_DESC.Default(),",
    "            SampleMask = uint.MaxValue,",
    "            RasterizerState = CD3DX12_RASTERIZER_DESC.Default(),",
    "            DepthStencilState = CD3DX12_DEPTH_STENCIL_DESC.Default(),",
    "            InputLayout = new D3D12_INPUT_LAYOUT_DESC",
    "            {",
    "                pInputElementDescs = inputElementsHandle.AddrOfPinnedObject(),",
    "                NumElements = (uint)inputElementDescs.Length",
    "            },",
    "            PrimitiveTopologyType = D3D12_PRIMITIVE_TOPOLOGY_TYPE.D3D12_PRIMITIVE_TOPOLOGY_TYPE_TRIANGLE,",
    "            NumRenderTargets = 1,",
    "            RTVFormats = new uint[8] { DXGI_FORMAT_R8G8B8A8_UNORM, 0, 0, 0, 0, 0, 0, 0 },",
    "            DSVFormat = DXGI_FORMAT_UNKNOWN,",
    "            SampleDesc = new DXGI_SAMPLE_DESC { Count = 1, Quality = 0 },",
    "            NodeMask = 0",
    "        };",
    "",
    "        // Disable depth test for fullscreen quad",
    "        psoDesc.DepthStencilState.DepthEnable = 0;",
    "        psoDesc.RasterizerState.CullMode = D3D12_CULL_MODE.D3D12_CULL_MODE_NONE;",
    "",
    "        try",
    "        {",
    "            IntPtr vTable = Marshal.ReadIntPtr(device);",
    "            IntPtr createPipelineStatePtr = Marshal.ReadIntPtr(vTable, 10 * IntPtr.Size);",
    "            var createPipelineState = Marshal.GetDelegateForFunctionPointer<CreateGraphicsPipelineStateDelegate>(createPipelineStatePtr);",
    "",
    "            Guid pipelineStateGuid = IID_ID3D12PipelineState;",
    "            int result = createPipelineState(device, ref psoDesc, ref pipelineStateGuid, out pipelineState);",
    "",
    "            if (result < 0)",
    "            {",
    "                throw new Exception(\"Failed to create pipeline state: {result:X}\");",
    "            }",
    "            Log(\"Pipeline state created: {pipelineState:X}\");",
    "        }",
    "        finally",
    "        {",
    "            inputElementsHandle.Free();",
    "        }",
    "",
    "        // Create command list",
    "        {",
    "            IntPtr vTable = Marshal.ReadIntPtr(device);",
    "            IntPtr createCommandListPtr = Marshal.ReadIntPtr(vTable, 12 * IntPtr.Size);",
    "            var createCommandList = Marshal.GetDelegateForFunctionPointer<CreateCommandListDelegate>(createCommandListPtr);",
    "",
    "            Guid commandListGuid = IID_ID3D12GraphicsCommandList;",
    "            int result = createCommandList(device, 0, D3D12_COMMAND_LIST_TYPE.D3D12_COMMAND_LIST_TYPE_DIRECT, commandAllocator, pipelineState, ref commandListGuid, out commandList);",
    "",
    "            if (result < 0)",
    "            {",
    "                throw new Exception(\"Failed to create command list: {result:X}\");",
    "            }",
    "",
    "            IntPtr vTableCmdList = Marshal.ReadIntPtr(commandList);",
    "            IntPtr closePtr = Marshal.ReadIntPtr(vTableCmdList, 9 * IntPtr.Size);",
    "            var close = Marshal.GetDelegateForFunctionPointer<CloseDelegate>(closePtr);",
    "            close(commandList);",
    "        }",
    "",
    "        // Create vertex buffer",
    "        uint vertexBufferSize = (uint)(Marshal.SizeOf<Vertex>() * quadVertices.Length);",
    "",
    "        D3D12_HEAP_PROPERTIES heapProps = new D3D12_HEAP_PROPERTIES",
    "        {",
    "            Type = D3D12_HEAP_TYPE.D3D12_HEAP_TYPE_UPLOAD,",
    "            CPUPageProperty = D3D12_CPU_PAGE_PROPERTY.D3D12_CPU_PAGE_PROPERTY_UNKNOWN,",
    "            MemoryPoolPreference = D3D12_MEMORY_POOL.D3D12_MEMORY_POOL_UNKNOWN",
    "        };",
    "",
    "        D3D12_RESOURCE_DESC resourceDesc = new D3D12_RESOURCE_DESC",
    "        {",
    "            Dimension = D3D12_RESOURCE_DIMENSION.D3D12_RESOURCE_DIMENSION_BUFFER,",
    "            Width = vertexBufferSize,",
    "            Height = 1,",
    "            DepthOrArraySize = 1,",
    "            MipLevels = 1,",
    "            Format = DXGI_FORMAT_UNKNOWN,",
    "            SampleDesc = new DXGI_SAMPLE_DESC { Count = 1, Quality = 0 },",
    "            Layout = D3D12_TEXTURE_LAYOUT.D3D12_TEXTURE_LAYOUT_ROW_MAJOR,",
    "            Flags = D3D12_RESOURCE_FLAGS.D3D12_RESOURCE_FLAG_NONE",
    "        };",
    "",
    "        {",
    "            IntPtr vTable = Marshal.ReadIntPtr(device);",
    "            IntPtr createResourcePtr = Marshal.ReadIntPtr(vTable, 27 * IntPtr.Size);",
    "            var createResource = Marshal.GetDelegateForFunctionPointer<CreateCommittedResourceDelegate>(createResourcePtr);",
    "",
    "            Guid resourceGuid = IID_ID3D12Resource;",
    "            int result = createResource(device, ref heapProps, D3D12_HEAP_FLAGS.D3D12_HEAP_FLAG_NONE, ref resourceDesc, D3D12_RESOURCE_STATES.D3D12_RESOURCE_STATE_GENERIC_READ, IntPtr.Zero, ref resourceGuid, out vertexBuffer);",
    "",
    "            if (result < 0)",
    "            {",
    "                throw new Exception(\"Failed to create vertex buffer: {result:X}\");",
    "            }",
    "        }",
    "",
    "        // Map and copy vertex data",
    "        {",
    "            IntPtr pData;",
    "            D3D12_RANGE readRange = new D3D12_RANGE { Begin = IntPtr.Zero, End = IntPtr.Zero };",
    "",
    "            IntPtr vTable = Marshal.ReadIntPtr(vertexBuffer);",
    "            IntPtr mapPtr = Marshal.ReadIntPtr(vTable, 8 * IntPtr.Size);",
    "            var map = Marshal.GetDelegateForFunctionPointer<MapDelegate>(mapPtr);",
    "            map(vertexBuffer, 0, ref readRange, out pData);",
    "",
    "            byte[] vertexData = StructArrayToByteArray(quadVertices);",
    "            Marshal.Copy(vertexData, 0, pData, (int)vertexBufferSize);",
    "",
    "            D3D12_RANGE emptyRange = new D3D12_RANGE { Begin = IntPtr.Zero, End = IntPtr.Zero };",
    "            IntPtr unmapPtr = Marshal.ReadIntPtr(vTable, 9 * IntPtr.Size);",
    "            var unmap = Marshal.GetDelegateForFunctionPointer<UnmapDelegate>(unmapPtr);",
    "            unmap(vertexBuffer, 0, ref emptyRange);",
    "        }",
    "",
    "        // Create vertex buffer view",
    "        {",
    "            IntPtr vTable = Marshal.ReadIntPtr(vertexBuffer);",
    "            IntPtr getGPUVirtualAddressPtr = Marshal.ReadIntPtr(vTable, 11 * IntPtr.Size);",
    "            var getGPUVirtualAddress = Marshal.GetDelegateForFunctionPointer<GetGPUVirtualAddressDelegate>(getGPUVirtualAddressPtr);",
    "",
    "            vertexBufferView = new D3D12_VERTEX_BUFFER_VIEW",
    "            {",
    "                BufferLocation = getGPUVirtualAddress(vertexBuffer),",
    "                StrideInBytes = (uint)Marshal.SizeOf<Vertex>(),",
    "                SizeInBytes = vertexBufferSize",
    "            };",
    "        }",
    "",
    "        // Create constant buffer (256-byte aligned)",
    "        uint constantBufferSize = 256;",
    "",
    "        D3D12_RESOURCE_DESC cbResourceDesc = new D3D12_RESOURCE_DESC",
    "        {",
    "            Dimension = D3D12_RESOURCE_DIMENSION.D3D12_RESOURCE_DIMENSION_BUFFER,",
    "            Width = constantBufferSize,",
    "            Height = 1,",
    "            DepthOrArraySize = 1,",
    "            MipLevels = 1,",
    "            Format = DXGI_FORMAT_UNKNOWN,",
    "            SampleDesc = new DXGI_SAMPLE_DESC { Count = 1, Quality = 0 },",
    "            Layout = D3D12_TEXTURE_LAYOUT.D3D12_TEXTURE_LAYOUT_ROW_MAJOR,",
    "            Flags = D3D12_RESOURCE_FLAGS.D3D12_RESOURCE_FLAG_NONE",
    "        };",
    "",
    "        {",
    "            IntPtr vTable = Marshal.ReadIntPtr(device);",
    "            IntPtr createResourcePtr = Marshal.ReadIntPtr(vTable, 27 * IntPtr.Size);",
    "            var createResource = Marshal.GetDelegateForFunctionPointer<CreateCommittedResourceDelegate>(createResourcePtr);",
    "",
    "            Guid resourceGuid = IID_ID3D12Resource;",
    "            int result = createResource(device, ref heapProps, D3D12_HEAP_FLAGS.D3D12_HEAP_FLAG_NONE, ref cbResourceDesc, D3D12_RESOURCE_STATES.D3D12_RESOURCE_STATE_GENERIC_READ, IntPtr.Zero, ref resourceGuid, out constantBuffer);",
    "",
    "            if (result < 0)",
    "            {",
    "                throw new Exception(\"Failed to create constant buffer: {result:X}\");",
    "            }",
    "        }",
    "",
    "        // Map constant buffer (keep mapped)",
    "        {",
    "            D3D12_RANGE readRange = new D3D12_RANGE { Begin = IntPtr.Zero, End = IntPtr.Zero };",
    "",
    "            IntPtr vTable = Marshal.ReadIntPtr(constantBuffer);",
    "            IntPtr mapPtr = Marshal.ReadIntPtr(vTable, 8 * IntPtr.Size);",
    "            var map = Marshal.GetDelegateForFunctionPointer<MapDelegate>(mapPtr);",
    "            map(constantBuffer, 0, ref readRange, out constantBufferDataBegin);",
    "        }",
    "",
    "        // Create CBV",
    "        {",
    "            IntPtr vTable = Marshal.ReadIntPtr(constantBuffer);",
    "            IntPtr getGPUVirtualAddressPtr = Marshal.ReadIntPtr(vTable, 11 * IntPtr.Size);",
    "            var getGPUVirtualAddress = Marshal.GetDelegateForFunctionPointer<GetGPUVirtualAddressDelegate>(getGPUVirtualAddressPtr);",
    "",
    "            D3D12_CONSTANT_BUFFER_VIEW_DESC cbvDesc = new D3D12_CONSTANT_BUFFER_VIEW_DESC",
    "            {",
    "                BufferLocation = getGPUVirtualAddress(constantBuffer),",
    "                SizeInBytes = constantBufferSize",
    "            };",
    "",
    "            D3D12_CPU_DESCRIPTOR_HANDLE cbvHandle = new D3D12_CPU_DESCRIPTOR_HANDLE",
    "            {",
    "                ptr = GetCPUDescriptorHandleForHeapStart(cbvHeap)",
    "            };",
    "",
    "            vTable = Marshal.ReadIntPtr(device);",
    "            IntPtr createCBVPtr = Marshal.ReadIntPtr(vTable, 17 * IntPtr.Size);",
    "            var createCBV = Marshal.GetDelegateForFunctionPointer<CreateConstantBufferViewDelegate>(createCBVPtr);",
    "            createCBV(device, ref cbvDesc, cbvHandle);",
    "        }",
    "",
    "        // Create fence",
    "        {",
    "            IntPtr vTable = Marshal.ReadIntPtr(device);",
    "            IntPtr createFencePtr = Marshal.ReadIntPtr(vTable, 36 * IntPtr.Size);",
    "            var createFence = Marshal.GetDelegateForFunctionPointer<CreateFenceDelegate>(createFencePtr);",
    "",
    "            Guid fenceGuid = IID_ID3D12Fence;",
    "            int result = createFence(device, 0, D3D12_FENCE_FLAGS.D3D12_FENCE_FLAG_NONE, ref fenceGuid, out fence);",
    "",
    "            if (result < 0)",
    "            {",
    "                throw new Exception(\"Failed to create fence: {result:X}\");",
    "            }",
    "",
    "            fenceValue = 1;",
    "            fenceEvent = CreateEvent(IntPtr.Zero, false, false, null);",
    "        }",
    "",
    "        // Initialize stopwatch",
    "        stopwatch = new Stopwatch();",
    "        stopwatch.Start();",
    "",
    "        Log(\"[LoadAssets] - Complete\");",
    "    }",
    "",
    "    private void PopulateCommandList()",
    "    {",
    "        Log(\"[PopulateCommandList] Begin\");",
    "        // Reset command allocator",
    "        IntPtr allocatorVTable = Marshal.ReadIntPtr(commandAllocator);",
    "        IntPtr resetAllocatorPtr = Marshal.ReadIntPtr(allocatorVTable, 8 * IntPtr.Size);",
    "        var resetAllocator = Marshal.GetDelegateForFunctionPointer<ResetCommandAllocatorDelegate>(resetAllocatorPtr);",
    "        resetAllocator(commandAllocator);",
    "",
    "        // Reset command list",
    "        IntPtr vTable = Marshal.ReadIntPtr(commandList);",
    "        IntPtr resetPtr = Marshal.ReadIntPtr(vTable, 10 * IntPtr.Size);",
    "        var reset = Marshal.GetDelegateForFunctionPointer<ResetCommandListDelegate>(resetPtr);",
    "        reset(commandList, commandAllocator, pipelineState);",
    "",
    "        // Set root signature",
    "        IntPtr setRootSigPtr = Marshal.ReadIntPtr(vTable, 30 * IntPtr.Size);",
    "        var setRootSig = Marshal.GetDelegateForFunctionPointer<SetGraphicsRootSignatureDelegate>(setRootSigPtr);",
    "        setRootSig(commandList, rootSignature);",
    "",
    "        // Set descriptor heaps",
    "        IntPtr setDescHeapsPtr = Marshal.ReadIntPtr(vTable, 28 * IntPtr.Size);",
    "        var setDescHeaps = Marshal.GetDelegateForFunctionPointer<SetDescriptorHeapsDelegate>(setDescHeapsPtr);",
    "        setDescHeaps(commandList, 1, new IntPtr[] { cbvHeap });",
    "",
    "        // Set root descriptor table",
    "        IntPtr setRootTablePtr = Marshal.ReadIntPtr(vTable, 32 * IntPtr.Size);",
    "        var setRootTable = Marshal.GetDelegateForFunctionPointer<SetGraphicsRootDescriptorTableDelegate>(setRootTablePtr);",
    "        D3D12_GPU_DESCRIPTOR_HANDLE gpuHandle = GetGPUDescriptorHandleForHeapStart(cbvHeap);",
    "        setRootTable(commandList, 0, gpuHandle);",
    "",
    "        // Set viewport",
    "        var viewports = new D3D12_VIEWPORT[]",
    "        {",
    "            new D3D12_VIEWPORT",
    "            {",
    "                TopLeftX = 0,",
    "                TopLeftY = 0,",
    "                Width = WIDTH,",
    "                Height = HEIGHT,",
    "                MinDepth = 0.0f,",
    "                MaxDepth = 1.0f",
    "            }",
    "        };",
    "",
    "        IntPtr setViewportsPtr = Marshal.ReadIntPtr(vTable, 21 * IntPtr.Size);",
    "        var rsSetViewports = Marshal.GetDelegateForFunctionPointer<RSSetViewportsDelegate>(setViewportsPtr);",
    "        rsSetViewports(commandList, 1, viewports);",
    "",
    "        // Set scissor rect",
    "        var scissorRects = new D3D12_RECT[]",
    "        {",
    "            new D3D12_RECT",
    "            {",
    "                left = 0,",
    "                top = 0,",
    "                right = WIDTH,",
    "                bottom = HEIGHT",
    "            }",
    "        };",
    "",
    "        IntPtr setScissorRectsPtr = Marshal.ReadIntPtr(vTable, 22 * IntPtr.Size);",
    "        var setScissorRects = Marshal.GetDelegateForFunctionPointer<RSSetScissorRectsDelegate>(setScissorRectsPtr);",
    "        setScissorRects(commandList, 1, scissorRects);",
    "",
    "        // Resource barrier: PRESENT -> RENDER_TARGET",
    "        var barrierDesc = CD3DX12_RESOURCE_BARRIER.Transition(",
    "            renderTargets[frameIndex],",
    "            D3D12_RESOURCE_STATES.D3D12_RESOURCE_STATE_PRESENT,",
    "            D3D12_RESOURCE_STATES.D3D12_RESOURCE_STATE_RENDER_TARGET);",
    "",
    "        IntPtr resourceBarrierPtr = Marshal.ReadIntPtr(vTable, 26 * IntPtr.Size);",
    "        var resourceBarrier = Marshal.GetDelegateForFunctionPointer<ResourceBarrierDelegate>(resourceBarrierPtr);",
    "        resourceBarrier(commandList, 1, new D3D12_RESOURCE_BARRIER[] { barrierDesc });",
    "",
    "        // Get RTV handle",
    "        D3D12_CPU_DESCRIPTOR_HANDLE rtvHandle = new D3D12_CPU_DESCRIPTOR_HANDLE",
    "        {",
    "            ptr = GetCPUDescriptorHandleForHeapStart(rtvHeap) + frameIndex * (int)rtvDescriptorSize",
    "        };",
    "",
    "        // Set render target",
    "        var rtvHandleArray = new[] { new D3D12_CPU_DESCRIPTOR_HANDLE_ARRAY { ptr = rtvHandle.ptr } };",
    "        IntPtr setRenderTargetsPtr = Marshal.ReadIntPtr(vTable, 46 * IntPtr.Size);",
    "        var omSetRenderTargets = Marshal.GetDelegateForFunctionPointer<OMSetRenderTargetsDelegate>(setRenderTargetsPtr);",
    "        omSetRenderTargets(commandList, 1, rtvHandleArray, false, IntPtr.Zero);",
    "",
    "        // Clear render target",
    "        float[] clearColor = new float[] { 0.0f, 0.0f, 0.0f, 1.0f };",
    "        IntPtr clearRtvPtr = Marshal.ReadIntPtr(vTable, 48 * IntPtr.Size);",
    "        var clearRtv = Marshal.GetDelegateForFunctionPointer<ClearRenderTargetViewDelegate>(clearRtvPtr);",
    "        clearRtv(commandList, rtvHandle, clearColor, 0, IntPtr.Zero);",
    "",
    "        // Set primitive topology",
    "        IntPtr setPrimTopoPtr = Marshal.ReadIntPtr(vTable, 20 * IntPtr.Size);",
    "        var setPrimTopo = Marshal.GetDelegateForFunctionPointer<IASetPrimitiveTopologyDelegate>(setPrimTopoPtr);",
    "        setPrimTopo(commandList, D3D_PRIMITIVE_TOPOLOGY.D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST);",
    "",
    "        // Set vertex buffer",
    "        IntPtr setVBPtr = Marshal.ReadIntPtr(vTable, 44 * IntPtr.Size);",
    "        var setVB = Marshal.GetDelegateForFunctionPointer<IASetVertexBuffersDelegate>(setVBPtr);",
    "        setVB(commandList, 0, 1, new[] { vertexBufferView });",
    "",
    "        // Draw fullscreen quad (6 vertices)",
    "        IntPtr drawPtr = Marshal.ReadIntPtr(vTable, 12 * IntPtr.Size);",
    "        var draw = Marshal.GetDelegateForFunctionPointer<DrawInstancedDelegate>(drawPtr);",
    "        draw(commandList, 6, 1, 0, 0);",
    "",
    "        // Resource barrier: RENDER_TARGET -> PRESENT",
    "        barrierDesc = CD3DX12_RESOURCE_BARRIER.Transition(",
    "            renderTargets[frameIndex],",
    "            D3D12_RESOURCE_STATES.D3D12_RESOURCE_STATE_RENDER_TARGET,",
    "            D3D12_RESOURCE_STATES.D3D12_RESOURCE_STATE_PRESENT);",
    "",
    "        resourceBarrier(commandList, 1, new D3D12_RESOURCE_BARRIER[] { barrierDesc });",
    "",
    "        // Close command list",
    "        IntPtr closePtr = Marshal.ReadIntPtr(vTable, 9 * IntPtr.Size);",
    "        var close = Marshal.GetDelegateForFunctionPointer<CloseDelegate>(closePtr);",
    "        close(commandList);",
    "    }",
    "",
    "    private void WaitForPreviousFrame()",
    "    {",
    "        Log(\"[WaitForPreviousFrame] Begin\");",
    "        IntPtr vTable = Marshal.ReadIntPtr(commandQueue);",
    "        IntPtr signalPtr = Marshal.ReadIntPtr(vTable, 14 * IntPtr.Size);",
    "        var signal = Marshal.GetDelegateForFunctionPointer<SignalDelegate>(signalPtr);",
    "        signal(commandQueue, fence, fenceValue);",
    "",
    "        IntPtr fenceVTable = Marshal.ReadIntPtr(fence);",
    "        IntPtr getCompletedValuePtr = Marshal.ReadIntPtr(fenceVTable, 8 * IntPtr.Size);",
    "        var getCompletedValue = Marshal.GetDelegateForFunctionPointer<GetCompletedValueDelegate>(getCompletedValuePtr);",
    "",
    "        if (getCompletedValue(fence) < fenceValue)",
    "        {",
    "            IntPtr setEventPtr = Marshal.ReadIntPtr(fenceVTable, 9 * IntPtr.Size);",
    "            var setEvent = Marshal.GetDelegateForFunctionPointer<SetEventOnCompletionDelegate>(setEventPtr);",
    "            setEvent(fence, fenceValue, fenceEvent);",
    "            WaitForSingleObject(fenceEvent, INFINITE);",
    "        }",
    "",
    "        fenceValue++;",
    "",
    "        frameIndex = (int)GetCurrentBackBufferIndex(swapChain);",
    "    }",
    "",
    "    public void Render()",
    "    {",
    "        if (fenceValue <= 5) Log(\"[Render] frameIndex=\" + frameIndex + \" fenceValue=\" + fenceValue);",
    "        // Update constant buffer with time",
    "        float time = (float)stopwatch.Elapsed.TotalSeconds;",
    "        ConstantBufferData cbData = new ConstantBufferData",
    "        {",
    "            iTime = time,",
    "            iResolutionX = WIDTH,",
    "            iResolutionY = HEIGHT,",
    "            padding = 0",
    "        };",
    "",
    "        Marshal.StructureToPtr(cbData, constantBufferDataBegin, false);",
    "",
    "        PopulateCommandList();",
    "",
    "        // Execute command list",
    "        IntPtr[] commandLists = { commandList };",
    "        IntPtr vTable = Marshal.ReadIntPtr(commandQueue);",
    "        IntPtr executePtr = Marshal.ReadIntPtr(vTable, 10 * IntPtr.Size);",
    "        var executeCommandLists = Marshal.GetDelegateForFunctionPointer<ExecuteCommandListsDelegate>(executePtr);",
    "        executeCommandLists(commandQueue, 1, commandLists);",
    "",
    "        // Present",
    "        vTable = Marshal.ReadIntPtr(swapChain);",
    "        IntPtr presentPtr = Marshal.ReadIntPtr(vTable, 8 * IntPtr.Size);",
    "        var present = Marshal.GetDelegateForFunctionPointer<PresentDelegate>(presentPtr);",
    "        present(swapChain, 1, 0);",
    "",
    "        WaitForPreviousFrame();",
    "    }",
    "",
    "    private void CleanupDevice()",
    "    {",
    "        Log(\"[CleanupDevice] - Start\");",
    "",
    "        CloseHandle(fenceEvent);",
    "",
    "        if (fence != IntPtr.Zero) Marshal.Release(fence);",
    "        if (constantBuffer != IntPtr.Zero) Marshal.Release(constantBuffer);",
    "        if (vertexBuffer != IntPtr.Zero) Marshal.Release(vertexBuffer);",
    "        if (pipelineState != IntPtr.Zero) Marshal.Release(pipelineState);",
    "        if (rootSignature != IntPtr.Zero) Marshal.Release(rootSignature);",
    "        if (commandList != IntPtr.Zero) Marshal.Release(commandList);",
    "        if (commandAllocator != IntPtr.Zero) Marshal.Release(commandAllocator);",
    "        if (cbvHeap != IntPtr.Zero) Marshal.Release(cbvHeap);",
    "        if (rtvHeap != IntPtr.Zero) Marshal.Release(rtvHeap);",
    "",
    "        foreach (var rt in renderTargets)",
    "        {",
    "            if (rt != IntPtr.Zero) Marshal.Release(rt);",
    "        }",
    "",
    "        if (swapChain != IntPtr.Zero) Marshal.Release(swapChain);",
    "        if (commandQueue != IntPtr.Zero) Marshal.Release(commandQueue);",
    "        if (device != IntPtr.Zero) Marshal.Release(device);",
    "    }",
    "",
    "    private void LoadPipeline(IntPtr hwnd)",
    "    {",
    "        Log(\"[LoadPipeline] - Start\");",
    "",
    "        // Enable debug layer",
    "        IntPtr debugInterface;",
    "        Guid debugGuid = IID_ID3D12Debug;",
    "        int debugResult = D3D12GetDebugInterface(ref debugGuid, out debugInterface);",
    "        if (debugResult >= 0 && debugInterface != IntPtr.Zero)",
    "        {",
    "            ID3D12Debug debug = Marshal.GetObjectForIUnknown(debugInterface) as ID3D12Debug;",
    "            debug.EnableDebugLayer();",
    "            Marshal.ReleaseComObject(debug);",
    "            Log(\"Debug layer enabled.\");",
    "        }",
    "",
    "        // Create DXGI factory",
    "        IntPtr factory = IntPtr.Zero;",
    "        Guid factoryIID = IID_IDXGIFactory4;",
    "        int result = CreateDXGIFactory2(0, ref factoryIID, out factory);",
    "        if (result < 0)",
    "        {",
    "            throw new Exception(\"Failed to create DXGI Factory: {result:X}\");",
    "        }",
    "        Log(\"DXGI Factory created.\");",
    "",
    "        // Create device",
    "        Guid deviceGuid = IID_ID3D12Device;",
    "        result = D3D12CreateDevice(IntPtr.Zero, D3D_FEATURE_LEVEL_11_0, ref deviceGuid, out device);",
    "        if (result < 0)",
    "        {",
    "            throw new Exception(\"Failed to create D3D12 Device: {result:X}\");",
    "        }",
    "        Log(\"D3D12 Device created.\");",
    "",
    "        // Create command queue",
    "        D3D12_COMMAND_QUEUE_DESC queueDesc = new D3D12_COMMAND_QUEUE_DESC",
    "        {",
    "            Type = D3D12_COMMAND_LIST_TYPE.D3D12_COMMAND_LIST_TYPE_DIRECT,",
    "            Priority = 0,",
    "            Flags = D3D12_COMMAND_QUEUE_FLAGS.D3D12_COMMAND_QUEUE_FLAG_NONE,",
    "            NodeMask = 0",
    "        };",
    "",
    "        IntPtr vTable = Marshal.ReadIntPtr(device);",
    "        IntPtr createCommandQueuePtr = Marshal.ReadIntPtr(vTable, 8 * IntPtr.Size);",
    "        var createCommandQueue = Marshal.GetDelegateForFunctionPointer<CreateCommandQueueDelegate>(createCommandQueuePtr);",
    "        Guid queueGuid = IID_ID3D12CommandQueue;",
    "        result = createCommandQueue(device, ref queueDesc, ref queueGuid, out commandQueue);",
    "        if (result < 0)",
    "        {",
    "            throw new Exception(\"Failed to create Command Queue: {result:X}\");",
    "        }",
    "        Log(\"Command Queue created.\");",
    "",
    "        // Create swap chain",
    "        swapChainDesc1 = new DXGI_SWAP_CHAIN_DESC1",
    "        {",
    "            Width = WIDTH,",
    "            Height = HEIGHT,",
    "            Format = DXGI_FORMAT_R8G8B8A8_UNORM,",
    "            Stereo = false,",
    "            SampleDesc = new DXGI_SAMPLE_DESC { Count = 1, Quality = 0 },",
    "            BufferUsage = DXGI_USAGE_RENDER_TARGET_OUTPUT,",
    "            BufferCount = FrameCount,",
    "            Scaling = DXGI_SCALING.DXGI_SCALING_STRETCH,",
    "            SwapEffect = DXGI_SWAP_EFFECT_FLIP_DISCARD,",
    "            AlphaMode = DXGI_ALPHA_MODE.DXGI_ALPHA_MODE_UNSPECIFIED,",
    "            Flags = DXGI_SWAP_CHAIN_FLAG_ALLOW_MODE_SWITCH | DXGI_SWAP_CHAIN_FLAG_FRAME_LATENCY_WAITABLE_OBJECT",
    "        };",
    "",
    "        Log(\"Calling CreateSwapChainForHwnd...\");",
    "        result = CreateSwapChainForHwnd(factory, commandQueue, hwnd, ref swapChainDesc1, IntPtr.Zero, IntPtr.Zero, out swapChain);",
    "        if (result < 0)",
    "        {",
    "            throw new Exception(\"Failed to create Swap Chain: {result:X}\");",
    "        }",
    "        Log(\"Swap Chain created.\");",
    "",
    "        // Upgrade to IDXGISwapChain3 so we can query the current back buffer index",
    "        IntPtr swapChain1 = swapChain;",
    "        Guid swapChain3Guid = IID_IDXGISwapChain3;",
    "        result = Marshal.QueryInterface(swapChain1, ref swapChain3Guid, out swapChain);",
    "        if (result < 0)",
    "        {",
    "            Marshal.Release(swapChain1);",
    "            throw new Exception(\"Failed to query IDXGISwapChain3: {result:X}\");",
    "        }",
    "        Marshal.Release(swapChain1);",
    "",
    "        frameIndex = (int)GetCurrentBackBufferIndex(swapChain);",
    "",
    "        // Create RTV descriptor heap",
    "        D3D12_DESCRIPTOR_HEAP_DESC rtvHeapDesc = new D3D12_DESCRIPTOR_HEAP_DESC",
    "        {",
    "            Type = D3D12_DESCRIPTOR_HEAP_TYPE.D3D12_DESCRIPTOR_HEAP_TYPE_RTV,",
    "            NumDescriptors = FrameCount,",
    "            Flags = D3D12_DESCRIPTOR_HEAP_FLAGS.D3D12_DESCRIPTOR_HEAP_FLAG_NONE,",
    "            NodeMask = 0",
    "        };",
    "",
    "        Guid heapGuid = IID_ID3D12DescriptorHeap;",
    "        vTable = Marshal.ReadIntPtr(device);",
    "        IntPtr createHeapPtr = Marshal.ReadIntPtr(vTable, 14 * IntPtr.Size);",
    "        var createHeap = Marshal.GetDelegateForFunctionPointer<CreateDescriptorHeapDelegate>(createHeapPtr);",
    "        result = createHeap(device, ref rtvHeapDesc, ref heapGuid, out rtvHeap);",
    "        if (result < 0)",
    "        {",
    "            throw new Exception(\"Failed to create RTV Descriptor Heap: {result:X}\");",
    "        }",
    "",
    "        IntPtr getIncrementPtr = Marshal.ReadIntPtr(vTable, 15 * IntPtr.Size);",
    "        var getIncrement = Marshal.GetDelegateForFunctionPointer<GetDescriptorHandleIncrementSizeDelegate>(getIncrementPtr);",
    "        rtvDescriptorSize = getIncrement(device, D3D12_DESCRIPTOR_HEAP_TYPE.D3D12_DESCRIPTOR_HEAP_TYPE_RTV);",
    "",
    "        // Create CBV descriptor heap (shader visible)",
    "        D3D12_DESCRIPTOR_HEAP_DESC cbvHeapDesc = new D3D12_DESCRIPTOR_HEAP_DESC",
    "        {",
    "            Type = D3D12_DESCRIPTOR_HEAP_TYPE.D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV,",
    "            NumDescriptors = 1,",
    "            Flags = D3D12_DESCRIPTOR_HEAP_FLAGS.D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE,",
    "            NodeMask = 0",
    "        };",
    "",
    "        result = createHeap(device, ref cbvHeapDesc, ref heapGuid, out cbvHeap);",
    "        if (result < 0)",
    "        {",
    "            throw new Exception(\"Failed to create CBV Descriptor Heap: {result:X}\");",
    "        }",
    "",
    "        cbvDescriptorSize = getIncrement(device, D3D12_DESCRIPTOR_HEAP_TYPE.D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);",
    "",
    "        // Create render target views",
    "        D3D12_CPU_DESCRIPTOR_HANDLE rtvHandle = new D3D12_CPU_DESCRIPTOR_HANDLE",
    "        {",
    "            ptr = GetCPUDescriptorHandleForHeapStart(rtvHeap)",
    "        };",
    "",
    "        for (int i = 0; i < FrameCount; i++)",
    "        {",
    "            IntPtr swapChainVTable = Marshal.ReadIntPtr(swapChain);",
    "            IntPtr getBufferPtr = Marshal.ReadIntPtr(swapChainVTable, 9 * IntPtr.Size);",
    "            var getBuffer = Marshal.GetDelegateForFunctionPointer<GetBufferDelegate>(getBufferPtr);",
    "",
    "            Guid resourceGuid = IID_ID3D12Resource;",
    "            IntPtr resourcePtr;",
    "            result = getBuffer(swapChain, (uint)i, ref resourceGuid, out resourcePtr);",
    "            if (result < 0)",
    "            {",
    "                throw new Exception(\"Failed to get Buffer: {result:X}\");",
    "            }",
    "            renderTargets[i] = resourcePtr;",
    "",
    "            vTable = Marshal.ReadIntPtr(device);",
    "            IntPtr createRTVPtr = Marshal.ReadIntPtr(vTable, 20 * IntPtr.Size);",
    "            var createRTV = Marshal.GetDelegateForFunctionPointer<CreateRenderTargetViewDelegate>(createRTVPtr);",
    "            createRTV(device, resourcePtr, IntPtr.Zero, rtvHandle);",
    "",
    "            rtvHandle.ptr += (int)rtvDescriptorSize;",
    "        }",
    "",
    "        // Create command allocator",
    "        vTable = Marshal.ReadIntPtr(device);",
    "        IntPtr createCommandAllocatorPtr = Marshal.ReadIntPtr(vTable, 9 * IntPtr.Size);",
    "        var createCommandAllocator = Marshal.GetDelegateForFunctionPointer<CreateCommandAllocatorDelegate>(createCommandAllocatorPtr);",
    "        Guid allocatorGuid = IID_ID3D12CommandAllocator;",
    "        result = createCommandAllocator(device, D3D12_COMMAND_LIST_TYPE.D3D12_COMMAND_LIST_TYPE_DIRECT, ref allocatorGuid, out commandAllocator);",
    "        if (result < 0)",
    "        {",
    "            throw new Exception(\"Failed to create Command Allocator: {result:X}\");",
    "        }",
    "",
    "        Marshal.Release(factory);",
    "",
    "        Log(\"[LoadPipeline] - Complete\");",
    "    }",
    "",
    "    static IntPtr WndProc(IntPtr hWnd, uint uMsg, IntPtr wParam, IntPtr lParam)",
    "    {",
    "        Log(\"[WndProc] msg=0x\" + uMsg.ToString(\"X\"));",
    "        switch (uMsg)",
    "        {",
    "            case WM_DESTROY:",
    "                PostQuitMessage(0);",
    "                break;",
    "            default:",
    "                return DefWindowProc(hWnd, uMsg, wParam, lParam);",
    "        }",
    "",
    "        return IntPtr.Zero;",
    "    }",
    "",
    "    static WndProcDelegate wndProcDelegate;",
    "",
    "    [STAThread]",
    "    static int Main(string[] args)",
    "    {",
    "        Log(\"Raymarching - DirectX 12 / C#\");",
    "        Log(\"========================================\");",
    "",
    "        var app = new Hello();",
    "",
    "        const string CLASS_NAME = \"HelloClass\";",
    "        const string WINDOW_NAME = \"Raymarching - DirectX 12 / C#\";",
    "",
    "        IntPtr hInstance = Marshal.GetHINSTANCE(typeof(Hello).Module);",
    "",
    "        wndProcDelegate = new WndProcDelegate(WndProc);",
    "",
    "        var wndClassEx = new WNDCLASSEX",
    "        {",
    "            cbSize = (uint)Marshal.SizeOf(typeof(WNDCLASSEX)),",
    "            style = CS_OWNDC,",
    "            lpfnWndProc = wndProcDelegate,",
    "            cbClsExtra = 0,",
    "            cbWndExtra = 0,",
    "            hInstance = hInstance,",
    "            hIcon = IntPtr.Zero,",
    "            hCursor = LoadCursor(IntPtr.Zero, (int)IDC_ARROW),",
    "            hbrBackground = IntPtr.Zero,",
    "            lpszMenuName = null,",
    "            lpszClassName = CLASS_NAME,",
    "            hIconSm = IntPtr.Zero",
    "        };",
    "",
    "        ushort atom = RegisterClassEx(ref wndClassEx);",
    "",
    "        if (atom == 0)",
    "        {",
    "            Log(\"Failed to register window class.\");",
    "            return 0;",
    "        }",
    "",
    "        IntPtr hwnd = CreateWindowEx(",
    "            0,",
    "            CLASS_NAME,",
    "            WINDOW_NAME,",
    "            WS_OVERLAPPEDWINDOW | WS_VISIBLE,",
    "            100, 100,",
    "            WIDTH, HEIGHT,",
    "            IntPtr.Zero,",
    "            IntPtr.Zero,",
    "            hInstance,",
    "            IntPtr.Zero",
    "        );",
    "",
    "        Log(\"[Main] CreateWindowEx hwnd=0x\" + hwnd.ToInt64().ToString(\"X\") + \" lastError=\" + Marshal.GetLastWin32Error());",
    "        if (hwnd == IntPtr.Zero)",
    "        {",
    "            Log(\"[Main] CreateWindowEx failed. Aborting.\");",
    "            return 0;",
    "        }",
    "",
    "        try",
    "        {",
    "            app.LoadPipeline(hwnd);",
    "            app.LoadAssets();",
    "",
    "            ShowWindow(hwnd, 1);",
    "",
    "            MSG msg = new MSG();",
    "            while (msg.message != WM_QUIT)",
    "            {",
    "                if (PeekMessage(out msg, IntPtr.Zero, 0, 0, PM_REMOVE))",
    "                {",
    "                    TranslateMessage(ref msg);",
    "                    DispatchMessage(ref msg);",
    "                }",
    "                else",
    "                {",
    "                    app.Render();",
    "                }",
    "            }",
    "",
    "            return (int)msg.wParam;",
    "        }",
    "        finally",
    "        {",
    "            app.CleanupDevice();",
    "        }",
    "    }",
    "}"
].join("\n");

Main();







