[package]
name = "hello"
version = "0.0.1"
edition = "2021"

[dependencies.gl]
git = "https://github.com/brendanzab/gl-rs.git"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs.git"
version = "0.57.0"
default-features = false
features = ["with-window-handle-v0-5"]
