import System;
import System.Collections.Generic;
import System.CodeDom.Compiler;
import Microsoft.CSharp;
import System.Reflection;

function Main() {
    Console.WriteLine("Compiling embedded C# DirectX12 code...");

    var provider = new CSharpCodeProvider();
    var parameters = new CompilerParameters();
    
    parameters.GenerateInMemory = true;
    parameters.GenerateExecutable = false;
    parameters.CompilerOptions = "/unsafe"; 
    
    parameters.ReferencedAssemblies.Add("System.dll");
    parameters.ReferencedAssemblies.Add("System.Drawing.dll");
    parameters.ReferencedAssemblies.Add("System.Windows.Forms.dll");

    var results = provider.CompileAssemblyFromSource(parameters, csharpSource);

    if (results.Errors.HasErrors) {
        Console.WriteLine("Compilation failed:");
        for(var i=0; i < results.Errors.Count; i++) {
            Console.WriteLine(results.Errors[i].ErrorText);
        }
        return;
    }

    Console.WriteLine("Compilation successful. Starting application...");

    try {
        var assembly = results.CompiledAssembly;
        var programType = assembly.GetType("Hello");
        var mainMethod = programType.GetMethod("Main");
        mainMethod.Invoke(null, null);
    } catch (e) {
        Console.WriteLine("Runtime Error: " + e.ToString());
    }
}

var csharpSource = [
    "using System;",
    "using System.Text;",
    "using System.Runtime.InteropServices;",
    "using System.Reflection;",
    "using System.ComponentModel;",

    "public class Hello",
    "{",
    "    const string SHADER_SOURCE = @\"",
    "      struct VS_IN { float3 pos : POSITION; float4 col : COLOR; };",
    "      struct PS_IN { float4 pos : SV_POSITION; float4 col : COLOR; };",
    "      PS_IN VS(VS_IN input) {",
    "        PS_IN output;",
    "        output.pos = float4(input.pos, 1.0);",
    "        output.col = input.col;",
    "        return output;",
    "      }",
    "      float4 PS(PS_IN input) : SV_Target {",
    "        return input.col;",
    "      }",
    "    \";",

    "    [StructLayout(LayoutKind.Sequential)] struct POINT { public int X; public int Y; }",
    "    [StructLayout(LayoutKind.Sequential)] struct MSG { public IntPtr hwnd; public uint message; public IntPtr wParam; public IntPtr lParam; public uint time; public POINT pt; }",
    "    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)] ",
    "    struct WNDCLASSEX { public uint cbSize; public uint style; public IntPtr lpfnWndProc; public int cbClsExtra; public int cbWndExtra; public IntPtr hInstance; public IntPtr hIcon; public IntPtr hCursor; public IntPtr hbrBackground; public string lpszMenuName; public string lpszClassName; public IntPtr hIconSm; }",
    
    "    [StructLayout(LayoutKind.Sequential)] struct DXGI_SWAP_CHAIN_DESC1 { public uint Width; public uint Height; public uint Format; public int Stereo; public DXGI_SAMPLE_DESC SampleDesc; public uint BufferUsage; public uint BufferCount; public uint Scaling; public uint SwapEffect; public uint AlphaMode; public uint Flags; }",
    "    [StructLayout(LayoutKind.Sequential)] struct DXGI_SAMPLE_DESC { public uint Count; public uint Quality; }",
    "    [StructLayout(LayoutKind.Sequential)] struct D3D12_VIEWPORT { public float TopLeftX; public float TopLeftY; public float Width; public float Height; public float MinDepth; public float MaxDepth; }",
    "    [StructLayout(LayoutKind.Sequential)] struct D3D12_INPUT_ELEMENT_DESC { public IntPtr SemanticName; public uint SemanticIndex; public uint Format; public uint InputSlot; public uint AlignedByteOffset; public uint InputSlotClass; public uint InstanceDataStepRate; }",
    "    [StructLayout(LayoutKind.Sequential)] struct Vertex { public float X, Y, Z; public float R, G, B, A; }",
    "    [StructLayout(LayoutKind.Sequential)] struct D3D12_COMMAND_QUEUE_DESC { public uint Type; public int Priority; public uint Flags; public uint NodeMask; }",
    "    [StructLayout(LayoutKind.Sequential)] struct D3D12_DESCRIPTOR_HEAP_DESC { public uint Type; public uint NumDescriptors; public uint Flags; public uint NodeMask; }",
    "    [StructLayout(LayoutKind.Sequential)] struct D3D12_ROOT_SIGNATURE_DESC { public uint NumParameters; public IntPtr pParameters; public uint NumStaticSamplers; public IntPtr pStaticSamplers; public uint Flags; }",
    "    [StructLayout(LayoutKind.Sequential)] struct D3D12_GRAPHICS_PIPELINE_STATE_DESC { public IntPtr pRootSignature; public D3D12_SHADER_BYTECODE VS; public D3D12_SHADER_BYTECODE PS; public D3D12_SHADER_BYTECODE DS; public D3D12_SHADER_BYTECODE HS; public D3D12_SHADER_BYTECODE GS; public D3D12_STREAM_OUTPUT_DESC StreamOutput; public D3D12_BLEND_DESC BlendState; public uint SampleMask; public D3D12_RASTERIZER_DESC RasterizerState; public D3D12_DEPTH_STENCIL_DESC DepthStencilState; public D3D12_INPUT_LAYOUT_DESC InputLayout; public uint IBStripCutValue; public uint PrimitiveTopologyType; public uint NumRenderTargets; [MarshalAs(UnmanagedType.ByValArray, SizeConst = 8)] public uint[] RTVFormats; public uint DSVFormat; public D3D12_MULTISAMPLE_QUALITY_LEVEL_FLAGS SampleDesc; public uint NodeMask; public D3D12_CACHED_PIPELINE_STATE CachedPSO; public uint Flags; }",
    "    [StructLayout(LayoutKind.Sequential)] struct D3D12_SHADER_BYTECODE { public IntPtr pShaderBytecode; public IntPtr BytecodeLength; }",
    "    [StructLayout(LayoutKind.Sequential)] struct D3D12_BLEND_DESC { public int AlphaToCoverageEnable; public int IndependentBlendEnable; [MarshalAs(UnmanagedType.ByValArray, SizeConst = 8)] public D3D12_RENDER_TARGET_BLEND_DESC[] RenderTarget; }",
    "    [StructLayout(LayoutKind.Sequential)] struct D3D12_RENDER_TARGET_BLEND_DESC { public int BlendEnable; public int LogicOpEnable; public uint SrcBlend; public uint DestBlend; public uint BlendOp; public uint SrcBlendAlpha; public uint DestBlendAlpha; public uint BlendOpAlpha; public uint LogicOp; public uint RenderTargetWriteMask; }",
    "    [StructLayout(LayoutKind.Sequential)] struct D3D12_RASTERIZER_DESC { public uint FillMode; public uint CullMode; public int FrontCounterClockwise; public int DepthBias; public float DepthBiasClamp; public float SlopeScaledDepthBias; public int DepthClipEnable; public int MultisampleEnable; public int AntialiasedLineEnable; public uint ForcedSampleCount; public uint ConservativeRaster; }",
    "    [StructLayout(LayoutKind.Sequential)] struct D3D12_DEPTH_STENCIL_DESC { public int DepthEnable; public bool DepthWriteMask; public uint DepthFunc; public int StencilEnable; public byte StencilReadMask; public byte StencilWriteMask; public D3D12_DEPTH_STENCILOP_DESC FrontFace; public D3D12_DEPTH_STENCILOP_DESC BackFace; }",
    "    [StructLayout(LayoutKind.Sequential)] struct D3D12_DEPTH_STENCILOP_DESC { public uint StencilFailOp; public uint StencilDepthFailOp; public uint StencilPassOp; public uint StencilFunc; }",
    "    [StructLayout(LayoutKind.Sequential)] struct D3D12_INPUT_LAYOUT_DESC { public IntPtr pInputElementDescs; public uint NumElements; }",
    "    [StructLayout(LayoutKind.Sequential)] struct D3D12_CACHED_PIPELINE_STATE { public IntPtr pCachedBlob; public IntPtr CachedBlobSizeInBytes; }",
    "    [StructLayout(LayoutKind.Sequential)] struct D3D12_RESOURCE_BARRIER { public uint Type; public uint Flags; public D3D12_RESOURCE_TRANSITION_BARRIER Transition; }",
    "    [StructLayout(LayoutKind.Sequential)] struct D3D12_RESOURCE_TRANSITION_BARRIER { public IntPtr pResource; public uint Subresource; public uint StateBefore; public uint StateAfter; }",
    "    [StructLayout(LayoutKind.Sequential)] struct D3D12_STREAM_OUTPUT_DESC { public IntPtr pSODeclaration; public uint NumEntries; public IntPtr pBufferStrides; public uint NumStrides; public uint RasterizedStream; }",
    "    [StructLayout(LayoutKind.Sequential)] struct D3D12_MULTISAMPLE_QUALITY_LEVEL_FLAGS { public uint Count; public uint Quality; }",
    "    [StructLayout(LayoutKind.Sequential)] struct D3D12_CPU_DESCRIPTOR_HANDLE { public IntPtr ptr; }",

    "    [StructLayout(LayoutKind.Sequential)] struct RECT { public int Left; public int Top; public int Right; public int Bottom; }",
    "    [StructLayout(LayoutKind.Sequential)] struct PAINTSTRUCT { public IntPtr hdc; public int fErase; public RECT rcPaint; public int fRestore; public int fIncUpdate; [MarshalAs(UnmanagedType.ByValArray, SizeConst = 32)] public byte[] Reserved; };",

    "    const uint CS_HREDRAW = 0x0002;",
    "    const uint CS_VREDRAW = 0x0001;",
    "    const uint WS_OVERLAPPEDWINDOW = 0x00CF0000; const uint WS_VISIBLE = 0x10000000;",
    "    const uint PM_REMOVE = 0x0001; const uint WM_QUIT = 0x0012; const uint WM_DESTROY = 0x0002; const uint WM_PAINT = 0x000F; const uint WM_ERASEBKGND = 0x0014;",
    "    const uint D3DCOMPILE_ENABLE_STRICTNESS = (1 << 11);",
    "    const int DXGI_FORMAT_R8G8B8A8_UNORM = 28; const int DXGI_FORMAT_R32G32B32_FLOAT = 6; const int DXGI_FORMAT_R32G32B32A32_FLOAT = 2;",
    "    const int DXGI_USAGE_RENDER_TARGET_OUTPUT = 0x20; const int DXGI_SWAP_EFFECT_FLIP_DISCARD = 4;",
    "    const int DXGI_SWAP_CHAIN_FLAG_ALLOW_MODE_SWITCH = 2;",
    "    const int D3D_FEATURE_LEVEL_11_0 = 0xb000;",
    "    const int D3D12_COMMAND_LIST_TYPE_DIRECT = 0;",
    "    const int D3D12_DESCRIPTOR_HEAP_TYPE_RTV = 2;",
    "    const int D3D12_DESCRIPTOR_HEAP_FLAG_NONE = 0;",
    "    const int D3D12_ROOT_SIGNATURE_FLAG_ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT = 1;",
    "    const int D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST = 4;",
    "    const uint D3D12_RESOURCE_STATE_PRESENT = 0;",
    "    const uint D3D12_RESOURCE_STATE_RENDER_TARGET = 4;",
    "    const int D3D12_HEAP_TYPE_UPLOAD = 2;",
    "    const int D3D12_HEAP_FLAG_NONE = 0;",

    "    [DllImport(\"user32.dll\", EntryPoint = \"CreateWindowExW\", SetLastError = true, CharSet = CharSet.Unicode)] static extern IntPtr CreateWindowEx(uint dwExStyle, string lpClassName, string lpWindowName, uint dwStyle, int x, int y, int nWidth, int nHeight, IntPtr hWndParent, IntPtr hMenu, IntPtr hInstance, IntPtr lpParam);",
    "    [DllImport(\"user32.dll\", EntryPoint = \"RegisterClassExW\", SetLastError = true, CharSet = CharSet.Unicode)] static extern ushort RegisterClassEx([In] ref WNDCLASSEX lpwcx);",
    "    [DllImport(\"user32.dll\", EntryPoint = \"DefWindowProcW\", SetLastError = true, CharSet = CharSet.Unicode)] static extern IntPtr DefWindowProc(IntPtr hWnd, uint uMsg, IntPtr wParam, IntPtr lParam);",
    "    [DllImport(\"user32.dll\", SetLastError = true)] static extern void PostQuitMessage(int nExitCode);",
    "    [DllImport(\"user32.dll\")] static extern bool PeekMessage(out MSG lpMsg, IntPtr hWnd, uint wMsgFilterMin, uint wMsgFilterMax, uint wRemoveMsg);",
    "    [DllImport(\"user32.dll\")] static extern bool TranslateMessage([In] ref MSG lpMsg);",
    "    [DllImport(\"user32.dll\")] static extern IntPtr DispatchMessage([In] ref MSG lpMsg);",
    "    [DllImport(\"user32.dll\")] static extern IntPtr LoadCursor(IntPtr hInstance, IntPtr lpCursorName);",
    "    [DllImport(\"kernel32.dll\", CharSet = CharSet.Unicode)] static extern IntPtr GetModuleHandle(string lpModuleName);",
    "    [DllImport(\"user32.dll\")] static extern IntPtr BeginPaint(IntPtr hWnd, out PAINTSTRUCT lpPaint);",
    "    [DllImport(\"user32.dll\")] static extern bool EndPaint(IntPtr hWnd, ref PAINTSTRUCT lpPaint);",
    "    [DllImport(\"user32.dll\", CharSet = CharSet.Unicode)] static extern int GetWindowText(IntPtr hWnd, StringBuilder lpString, int nMaxCount);",
    "    [DllImport(\"kernel32.dll\")] static extern void OutputDebugStringA([MarshalAs(UnmanagedType.LPStr)] string lpOutputString);",

    "    [DllImport(\"d3d12.dll\", CallingConvention = CallingConvention.StdCall)] static extern int D3D12CreateDevice(IntPtr pAdapter, uint MinimumFeatureLevel, ref Guid riid, out IntPtr ppDevice);",
    "    [DllImport(\"d3d12.dll\", CallingConvention = CallingConvention.StdCall)] static extern int D3D12GetDebugInterface(ref Guid riid, out IntPtr ppvDebug);",
    "    [DllImport(\"dxgi.dll\", CallingConvention = CallingConvention.StdCall)] static extern int CreateDXGIFactory2(uint Flags, ref Guid riid, out IntPtr ppFactory);",
    "    [DllImport(\"d3dcompiler_47.dll\", CallingConvention = CallingConvention.StdCall)] static extern int D3DCompile([MarshalAs(UnmanagedType.LPStr)] string srcData, IntPtr srcDataSize, string sourceName, IntPtr defines, IntPtr include, string entryPoint, string target, uint flags1, uint flags2, out IntPtr code, out IntPtr errorMsgs);",
    "    [DllImport(\"d3d12.dll\", CallingConvention = CallingConvention.StdCall)] static extern int D3D12SerializeRootSignature(ref D3D12_ROOT_SIGNATURE_DESC pRootSignature, uint Version, out IntPtr ppBlob, out IntPtr ppErrorBlob);",
    "    [DllImport(\"kernel32.dll\", SetLastError = true)] static extern IntPtr CreateEvent(IntPtr lpEventAttributes, bool bManualReset, bool bInitialState, string lpName);",
    "    [DllImport(\"kernel32.dll\", SetLastError = true)] static extern uint WaitForSingleObject(IntPtr hHandle, uint dwMilliseconds);",
    "    [DllImport(\"kernel32.dll\", SetLastError = true)] static extern bool CloseHandle(IntPtr hObject);",

    "    delegate IntPtr WndProcDelegate(IntPtr hWnd, uint uMsg, IntPtr wParam, IntPtr lParam);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int QueryInterfaceDelegate(IntPtr thisPtr, ref Guid riid, out IntPtr ppvObject);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int CreateSwapChainForHwndDelegate(IntPtr factory, IntPtr pDevice, IntPtr hWnd, [In] ref DXGI_SWAP_CHAIN_DESC1 pDesc, IntPtr pFullscreenDesc, IntPtr pRestrictToOutput, out IntPtr ppSwapChain);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int GetBufferDelegate(IntPtr swapChain, uint Buffer, ref Guid riid, out IntPtr ppSurface);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int CreateRenderTargetViewDelegate(IntPtr device, IntPtr pResource, IntPtr pDesc, D3D12_CPU_DESCRIPTOR_HANDLE destDescriptor);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate void ClearRenderTargetViewDelegate(IntPtr context, D3D12_CPU_DESCRIPTOR_HANDLE RenderTargetView, [MarshalAs(UnmanagedType.LPArray, SizeConst = 4)] float[] ColorRGBA, uint NumRects, IntPtr pRects);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int CreateCommittedResourceDelegate(IntPtr device, ref D3D12_HEAP_PROPERTIES pHeapProperties, uint HeapFlags, ref D3D12_RESOURCE_DESC pDesc, uint InitialResourceState, IntPtr pOptimizedClearValue, ref Guid riidResource, out IntPtr ppvResource);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int CreateRootSignatureDelegate(IntPtr device, uint nodeMask, IntPtr blobWithRootSignature, IntPtr blobLengthInBytes, ref Guid riid, out IntPtr ppvRootSignature);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int CreateGraphicsPipelineStateDelegate(IntPtr device, ref D3D12_GRAPHICS_PIPELINE_STATE_DESC pDesc, ref Guid riid, out IntPtr ppPipelineState);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate void SetGraphicsRootSignatureDelegate(IntPtr context, IntPtr pRootSignature);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate void IASetPrimitiveTopologyDelegate(IntPtr context, uint PrimitiveTopology);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate void RSSetViewportsDelegate(IntPtr context, uint NumViewports, ref D3D12_VIEWPORT pViewports);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate void OMSetRenderTargetsDelegate(IntPtr context, uint NumRenderTargetDescriptors, ref D3D12_CPU_DESCRIPTOR_HANDLE pRenderTargetDescriptors, bool RTsSingleHandleToDescriptorRange, IntPtr pDepthStencilDescriptor);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate void IASetVertexBuffersDelegate(IntPtr context, uint StartSlot, uint NumViews, [In] D3D12_VERTEX_BUFFER_VIEW[] pViews);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate void DrawInstancedDelegate(IntPtr context, uint VertexCountPerInstance, uint InstanceCount, uint StartVertexLocation, uint StartInstanceLocation);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int PresentDelegate(IntPtr pSwapChain, uint SyncInterval, uint Flags);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate IntPtr GetBufferPointerDelegate(IntPtr pBlob);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate IntPtr GetBufferSizeDelegate(IntPtr pBlob);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int CreateCommandQueueDelegate(IntPtr device, ref D3D12_COMMAND_QUEUE_DESC pDesc, ref Guid riid, out IntPtr ppCommandQueue);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int CreateCommandAllocatorDelegate(IntPtr device, uint type, ref Guid riid, out IntPtr ppCommandAllocator);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int CreateGraphicsCommandListDelegate(IntPtr device, uint nodeMask, uint type, IntPtr commandAllocator, IntPtr pso, ref Guid riid, out IntPtr ppCommandList);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int CloseCommandListDelegate(IntPtr commandList);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate void ExecuteCommandListsDelegate(IntPtr commandQueue, uint NumCommandLists, [In] IntPtr[] ppCommandLists);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int CreateDescriptorHeapDelegate(IntPtr device, ref D3D12_DESCRIPTOR_HEAP_DESC pDesc, ref Guid riid, out IntPtr ppvHeap);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate uint GetDescriptorHandleIncrementSizeDelegate(IntPtr device, uint DescriptorHeapType);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate void GetCPUDescriptorHandleForHeapStartDelegate(IntPtr heap, out D3D12_CPU_DESCRIPTOR_HANDLE handle);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int CreateFenceDelegate(IntPtr device, ulong InitialValue, uint Flags, ref Guid riid, out IntPtr ppFence);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int SignalDelegate(IntPtr commandQueue, IntPtr fence, ulong Value);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate ulong GetCompletedValueDelegate(IntPtr fence);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int SetEventOnCompletionDelegate(IntPtr fence, ulong Value, IntPtr hEvent);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate void ResourceBarrierDelegate(IntPtr commandList, uint NumBarriers, [In] D3D12_RESOURCE_BARRIER[] pBarriers);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int ResetCommandAllocatorDelegate(IntPtr allocator);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int ResetCommandListDelegate(IntPtr commandList, IntPtr allocator, IntPtr pso);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int MapDelegate(IntPtr resource, uint Subresource, IntPtr pReadRange, out IntPtr ppData);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate void UnmapDelegate(IntPtr resource, uint Subresource, IntPtr pWrittenRange);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate uint GetCurrentBackBufferIndexDelegate(IntPtr swapChain);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate ulong GetGPUVirtualAddressDelegate(IntPtr resource);",
    "    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate void EnableDebugLayerDelegate(IntPtr debug);",

    "    [StructLayout(LayoutKind.Sequential)] struct D3D12_HEAP_PROPERTIES { public uint Type; public uint CPUPageProperty; public uint MemoryPoolPreference; public uint CreationNodeMask; public uint VisibleNodeMask; }",
    "    [StructLayout(LayoutKind.Sequential)] struct D3D12_RESOURCE_DESC { public uint Dimension; public ulong Alignment; public ulong Width; public uint Height; public ushort DepthOrArraySize; public ushort MipLevels; public uint Format; public D3D12_MULTISAMPLE_QUALITY_LEVEL_FLAGS SampleDesc; public uint Layout; public uint Flags; }",
    "    [StructLayout(LayoutKind.Sequential)] struct D3D12_VERTEX_BUFFER_VIEW { public ulong BufferLocation; public uint SizeInBytes; public uint StrideInBytes; }",

    "    static void Log(string msg) {",
    "        Console.WriteLine(msg);",
    "        OutputDebugStringA(msg + \"\\n\");",
    "    }",

    "    static T GetMethod<T>(IntPtr ptr, int index) {",
    "        if (ptr == IntPtr.Zero) throw new Exception(\"Null pointer passed to GetMethod\");",
    "        IntPtr vTable = Marshal.ReadIntPtr(ptr);",
    "        if (vTable == IntPtr.Zero) throw new Exception(\"Null vTable\");",
    "        IntPtr methodPtr = Marshal.ReadIntPtr(vTable, index * IntPtr.Size);",
    "        if (methodPtr == IntPtr.Zero) throw new Exception(string.Format(\"Null method pointer at index {0}\", index));",
    "        return Marshal.GetDelegateForFunctionPointer<T>(methodPtr);",
    "    }",

    "    static D3D12_CPU_DESCRIPTOR_HANDLE GetCPUDescriptorHandleForHeapStart(IntPtr heap) {",
    "        IntPtr vTable = Marshal.ReadIntPtr(heap);",
    "        IntPtr methodPtr = Marshal.ReadIntPtr(vTable, 9 * IntPtr.Size);",
    "        D3D12_CPU_DESCRIPTOR_HANDLE result;",
    "        var method = Marshal.GetDelegateForFunctionPointer<GetCPUDescriptorHandleForHeapStartDelegate>(methodPtr);",
    "        method(heap, out result);",
    "        return result;",
    "    }",

    "    static IntPtr WndProc(IntPtr hWnd, uint uMsg, IntPtr wParam, IntPtr lParam) {",
    "        if (uMsg == WM_DESTROY) {",
    "            PostQuitMessage(0);",
    "            return IntPtr.Zero;",
    "        }",
    "        if (uMsg == WM_ERASEBKGND) {",
    "            return (IntPtr)1;",
    "        }",
    "        if (uMsg == WM_PAINT) {",
    "            PAINTSTRUCT ps;",
    "            IntPtr hdc = BeginPaint(hWnd, out ps);",
    "            EndPaint(hWnd, ref ps);",
    "            return IntPtr.Zero;",
    "        }",
    "        return DefWindowProc(hWnd, uMsg, wParam, lParam);",
    "    }",

    "    public static void Main() {",
    "        int hr;",
    "        try {",
    "            Log(\"=== DirectX12 JScript.NET Triangle ===\");",
    "            Log(string.Format(\"Running as {0}-bit process\", IntPtr.Size * 8));",
    "",
    "            // Enable Debug Layer",
    "            Log(\"Enabling D3D12 Debug Layer...\");",
    "            Guid IID_Debug = new Guid(\"344488b7-6846-474b-b989-f027448245e0\");",
    "            IntPtr debugController;",
    "            hr = D3D12GetDebugInterface(ref IID_Debug, out debugController);",
    "            if (hr >= 0 && debugController != IntPtr.Zero) {",
    "                GetMethod<EnableDebugLayerDelegate>(debugController, 3)(debugController);",
    "                Log(\"Debug Layer Enabled\");",
    "            } else {",
    "                Log(string.Format(\"Debug Layer not available (hr=0x{0:X8})\", hr));",
    "            }",
    "",
    "            IntPtr hInstance = GetModuleHandle(null);",
    "            WndProcDelegate wndProc = WndProc;",
    "            var wndClass = new WNDCLASSEX { cbSize = (uint)Marshal.SizeOf(typeof(WNDCLASSEX)), style = CS_HREDRAW | CS_VREDRAW | 0x0020, lpfnWndProc = Marshal.GetFunctionPointerForDelegate(wndProc), hInstance = hInstance, hCursor = LoadCursor(IntPtr.Zero, (IntPtr)32512), lpszClassName = \"DX12Class\" };",
    "            RegisterClassEx(ref wndClass);",
    "            IntPtr hWnd = CreateWindowEx(0, \"DX12Class\", \"JScript.NET DX12 Triangle\", WS_OVERLAPPEDWINDOW | WS_VISIBLE, 100, 100, 800, 600, IntPtr.Zero, IntPtr.Zero, hInstance, IntPtr.Zero);",
    "            Log(string.Format(\"Window created: 0x{0:X}\", hWnd.ToInt64()));",
    "",
    "            // Create Device",
    "            Log(\"Creating D3D12 Device...\");",
    "            Guid IID_Device = new Guid(\"189819f1-1db6-4b57-be54-1821339b85f7\");",
    "            IntPtr device;",
    "            hr = D3D12CreateDevice(IntPtr.Zero, (uint)D3D_FEATURE_LEVEL_11_0, ref IID_Device, out device);",
    "            if (hr < 0) throw new Exception(string.Format(\"D3D12CreateDevice failed: 0x{0:X8}\", hr));",
    "            Log(string.Format(\"Device created: 0x{0:X}\", device.ToInt64()));",
    "",
    "            // Create Command Queue",
    "            Log(\"Creating Command Queue...\");",
    "            var queueDesc = new D3D12_COMMAND_QUEUE_DESC { Type = (uint)D3D12_COMMAND_LIST_TYPE_DIRECT, Priority = 0, Flags = 0, NodeMask = 0 };",
    "            Guid IID_CommandQueue = new Guid(\"0ec870a6-5d7e-4c22-8cfc-5baae07616ed\");",
    "            IntPtr commandQueue;",
    "            hr = GetMethod<CreateCommandQueueDelegate>(device, 8)(device, ref queueDesc, ref IID_CommandQueue, out commandQueue);",
    "            if (hr < 0) throw new Exception(string.Format(\"CreateCommandQueue failed: 0x{0:X8}\", hr));",
    "            Log(string.Format(\"Command Queue created: 0x{0:X}\", commandQueue.ToInt64()));",
    "",
    "            // Create DXGI Factory with Debug flag",
    "            Log(\"Creating DXGI Factory2...\");",
    "            IntPtr factory;",
    "            Guid IID_Factory2 = new Guid(\"50c83a1c-e072-4c48-87b0-3630fa36a6d0\");",
    "            hr = CreateDXGIFactory2(0x01, ref IID_Factory2, out factory);",
    "            if (hr < 0) throw new Exception(string.Format(\"CreateDXGIFactory2 failed: 0x{0:X8}\", hr));",
    "            Log(string.Format(\"Factory2 created: 0x{0:X}\", factory.ToInt64()));",
    "",
    "            // Create Swap Chain",
    "            Log(\"Creating Swap Chain...\");",
    "            var scDesc = new DXGI_SWAP_CHAIN_DESC1 { Width = 800, Height = 600, Format = (uint)DXGI_FORMAT_R8G8B8A8_UNORM, SampleDesc = new DXGI_SAMPLE_DESC { Count = 1 }, BufferUsage = (uint)DXGI_USAGE_RENDER_TARGET_OUTPUT, BufferCount = 2, SwapEffect = (uint)DXGI_SWAP_EFFECT_FLIP_DISCARD, Flags = (uint)DXGI_SWAP_CHAIN_FLAG_ALLOW_MODE_SWITCH };",
    "            IntPtr swapChain;",
    "            hr = GetMethod<CreateSwapChainForHwndDelegate>(factory, 15)(factory, commandQueue, hWnd, ref scDesc, IntPtr.Zero, IntPtr.Zero, out swapChain);",
    "            if (hr < 0) throw new Exception(string.Format(\"CreateSwapChainForHwnd failed: 0x{0:X8}\", hr));",
    "            Log(string.Format(\"Swap Chain created: 0x{0:X}\", swapChain.ToInt64()));",
    "",
    "            // Create RTV Descriptor Heap",
    "            Log(\"Creating RTV Descriptor Heap...\");",
    "            var heapDesc = new D3D12_DESCRIPTOR_HEAP_DESC { Type = (uint)D3D12_DESCRIPTOR_HEAP_TYPE_RTV, NumDescriptors = 2, Flags = (uint)D3D12_DESCRIPTOR_HEAP_FLAG_NONE, NodeMask = 0 };",
    "            Guid IID_DescriptorHeap = new Guid(\"8efb471d-616c-4f49-90f7-127bb763fa51\");",
    "            IntPtr rtvHeap;",
    "            hr = GetMethod<CreateDescriptorHeapDelegate>(device, 14)(device, ref heapDesc, ref IID_DescriptorHeap, out rtvHeap);",
    "            if (hr < 0) throw new Exception(string.Format(\"CreateDescriptorHeap failed: 0x{0:X8}\", hr));",
    "            Log(string.Format(\"RTV Heap created: 0x{0:X}\", rtvHeap.ToInt64()));",
    "",
    "            uint rtvIncrement = GetMethod<GetDescriptorHandleIncrementSizeDelegate>(device, 15)(device, (uint)D3D12_DESCRIPTOR_HEAP_TYPE_RTV);",
    "            Log(string.Format(\"RTV Increment Size: {0}\", rtvIncrement));",
    "",
    "            Log(\"Calling GetCPUDescriptorHandleForHeapStart...\");",
    "            D3D12_CPU_DESCRIPTOR_HANDLE rtvHandle = GetCPUDescriptorHandleForHeapStart(rtvHeap);",
    "            Log(string.Format(\"RTV Handle Start: 0x{0:X}\", rtvHandle.ptr.ToInt64()));",
    "",
    "            // Get Back Buffers and Create RTVs",
    "            Log(\"Creating Render Target Views...\");",
    "            IntPtr[] backBuffers = new IntPtr[2];",
    "            Guid IID_Resource = new Guid(\"696442be-a72e-4059-bc79-5b5c98040fad\");",
    "            D3D12_CPU_DESCRIPTOR_HANDLE currentRtvForInit = rtvHandle;",
    "            for (int i = 0; i < 2; i++) {",
    "                hr = GetMethod<GetBufferDelegate>(swapChain, 9)(swapChain, (uint)i, ref IID_Resource, out backBuffers[i]);",
    "                if (hr < 0) throw new Exception(string.Format(\"GetBuffer[{0}] failed: 0x{1:X8}\", i, hr));",
    "                Log(string.Format(\"BackBuffer[{0}]: 0x{1:X}\", i, backBuffers[i].ToInt64()));",
    "                GetMethod<CreateRenderTargetViewDelegate>(device, 20)(device, backBuffers[i], IntPtr.Zero, currentRtvForInit);",
    "                currentRtvForInit.ptr = IntPtr.Add(currentRtvForInit.ptr, (int)rtvIncrement);",
    "            }",
    "",
    "            // Create Command Allocator",
    "            Log(\"Creating Command Allocator...\");",
    "            IntPtr commandAllocator;",
    "            Guid IID_CommandAllocator = new Guid(\"6102dee4-af59-4b09-b999-b44d73f09b24\");",
    "            hr = GetMethod<CreateCommandAllocatorDelegate>(device, 9)(device, (uint)D3D12_COMMAND_LIST_TYPE_DIRECT, ref IID_CommandAllocator, out commandAllocator);",
    "            if (hr < 0) throw new Exception(string.Format(\"CreateCommandAllocator failed: 0x{0:X8}\", hr));",
    "            Log(string.Format(\"Command Allocator created: 0x{0:X}\", commandAllocator.ToInt64()));",
    "",
    "            // Create Command List",
    "            Log(\"Creating Graphics Command List...\");",
    "            IntPtr commandList;",
    "            Guid IID_GraphicsCommandList = new Guid(\"5b160d0f-ac1b-4185-8ba8-b3ae42a5a455\");",
    "            hr = GetMethod<CreateGraphicsCommandListDelegate>(device, 12)(device, 0, (uint)D3D12_COMMAND_LIST_TYPE_DIRECT, commandAllocator, IntPtr.Zero, ref IID_GraphicsCommandList, out commandList);",
    "            if (hr < 0) throw new Exception(string.Format(\"CreateCommandList failed: 0x{0:X8}\", hr));",
    "            Log(string.Format(\"Command List created: 0x{0:X}\", commandList.ToInt64()));",
    "            hr = GetMethod<CloseCommandListDelegate>(commandList, 9)(commandList);",
    "            if (hr < 0) throw new Exception(string.Format(\"Close CommandList failed: 0x{0:X8}\", hr));",
    "",
    "            // Create Fence",
    "            Log(\"Creating Fence...\");",
    "            IntPtr fence;",
    "            Guid IID_Fence = new Guid(\"0a753dcf-c4d8-4b91-adf6-be5a60d95a76\");",
    "            hr = GetMethod<CreateFenceDelegate>(device, 36)(device, 0, 0, ref IID_Fence, out fence);",
    "            if (hr < 0) throw new Exception(string.Format(\"CreateFence failed: 0x{0:X8}\", hr));",
    "            Log(string.Format(\"Fence created: 0x{0:X}\", fence.ToInt64()));",
    "            IntPtr fenceEvent = CreateEvent(IntPtr.Zero, false, false, null);",
    "            ulong fenceValue = 0;",
    "",
    "            // Compile Shaders",
    "            Log(\"Compiling Shaders...\");",
    "            IntPtr vsBlob, psBlob, err;",
    "            hr = D3DCompile(SHADER_SOURCE, (IntPtr)SHADER_SOURCE.Length, null, IntPtr.Zero, IntPtr.Zero, \"VS\", \"vs_5_0\", D3DCOMPILE_ENABLE_STRICTNESS, 0, out vsBlob, out err);",
    "            if (hr < 0) throw new Exception(string.Format(\"VS Compile failed: 0x{0:X8}\", hr));",
    "            Log(string.Format(\"VS Blob: 0x{0:X}\", vsBlob.ToInt64()));",
    "            hr = D3DCompile(SHADER_SOURCE, (IntPtr)SHADER_SOURCE.Length, null, IntPtr.Zero, IntPtr.Zero, \"PS\", \"ps_5_0\", D3DCOMPILE_ENABLE_STRICTNESS, 0, out psBlob, out err);",
    "            if (hr < 0) throw new Exception(string.Format(\"PS Compile failed: 0x{0:X8}\", hr));",
    "            Log(string.Format(\"PS Blob: 0x{0:X}\", psBlob.ToInt64()));",
    "",
    "            // Create Root Signature",
    "            Log(\"Creating Root Signature...\");",
    "            D3D12_ROOT_SIGNATURE_DESC rootSigDesc = new D3D12_ROOT_SIGNATURE_DESC { NumParameters = 0, pParameters = IntPtr.Zero, NumStaticSamplers = 0, pStaticSamplers = IntPtr.Zero, Flags = (uint)D3D12_ROOT_SIGNATURE_FLAG_ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT };",
    "            IntPtr rootSigBlob, rootSigError;",
    "            hr = D3D12SerializeRootSignature(ref rootSigDesc, 1, out rootSigBlob, out rootSigError);",
    "            if (hr < 0) throw new Exception(string.Format(\"SerializeRootSignature failed: 0x{0:X8}\", hr));",
    "            IntPtr rootSignature;",
    "            Guid IID_RootSignature = new Guid(\"c54a6b66-72df-4ee8-8be5-a946a1429214\");",
    "            hr = GetMethod<CreateRootSignatureDelegate>(device, 16)(device, 0, GetMethod<GetBufferPointerDelegate>(rootSigBlob, 3)(rootSigBlob), GetMethod<GetBufferSizeDelegate>(rootSigBlob, 4)(rootSigBlob), ref IID_RootSignature, out rootSignature);",
    "            if (hr < 0) throw new Exception(string.Format(\"CreateRootSignature failed: 0x{0:X8}\", hr));",
    "            Log(string.Format(\"Root Signature created: 0x{0:X}\", rootSignature.ToInt64()));",
    "",
    "            // Create PSO",
    "            Log(\"Creating Pipeline State Object...\");",
    "            IntPtr semanticNamePos = Marshal.StringToHGlobalAnsi(\"POSITION\");",
    "            IntPtr semanticNameCol = Marshal.StringToHGlobalAnsi(\"COLOR\");",
    "            try {",
    "                var elements = new D3D12_INPUT_ELEMENT_DESC[] {",
    "                    new D3D12_INPUT_ELEMENT_DESC { SemanticName = semanticNamePos, Format = (uint)DXGI_FORMAT_R32G32B32_FLOAT, InputSlotClass = 0 },",
    "                    new D3D12_INPUT_ELEMENT_DESC { SemanticName = semanticNameCol, Format = (uint)DXGI_FORMAT_R32G32B32A32_FLOAT, AlignedByteOffset = 12, InputSlotClass = 0 }",
    "                };",
    "                GCHandle elementsHandle = GCHandle.Alloc(elements, GCHandleType.Pinned);",
    "                D3D12_INPUT_LAYOUT_DESC inputLayout = new D3D12_INPUT_LAYOUT_DESC { pInputElementDescs = elementsHandle.AddrOfPinnedObject(), NumElements = 2 };",
    "",
    "                var defaultRtBlendDesc = new D3D12_RENDER_TARGET_BLEND_DESC { BlendEnable = 0, LogicOpEnable = 0, RenderTargetWriteMask = 0xF };",
    "                var rtBlendDescs = new D3D12_RENDER_TARGET_BLEND_DESC[8];",
    "                for (int i = 0; i < 8; i++) rtBlendDescs[i] = defaultRtBlendDesc;",
    "",
    "                D3D12_GRAPHICS_PIPELINE_STATE_DESC psoDesc = new D3D12_GRAPHICS_PIPELINE_STATE_DESC {",
    "                    pRootSignature = rootSignature,",
    "                    VS = new D3D12_SHADER_BYTECODE { pShaderBytecode = GetMethod<GetBufferPointerDelegate>(vsBlob, 3)(vsBlob), BytecodeLength = GetMethod<GetBufferSizeDelegate>(vsBlob, 4)(vsBlob) },",
    "                    PS = new D3D12_SHADER_BYTECODE { pShaderBytecode = GetMethod<GetBufferPointerDelegate>(psBlob, 3)(psBlob), BytecodeLength = GetMethod<GetBufferSizeDelegate>(psBlob, 4)(psBlob) },",
    "                    BlendState = new D3D12_BLEND_DESC { AlphaToCoverageEnable = 0, IndependentBlendEnable = 0, RenderTarget = rtBlendDescs },",
    "                    SampleMask = uint.MaxValue,",
    "                    RasterizerState = new D3D12_RASTERIZER_DESC { FillMode = 3, CullMode = 1, FrontCounterClockwise = 0, DepthBias = 0, DepthBiasClamp = 0, SlopeScaledDepthBias = 0, DepthClipEnable = 1, MultisampleEnable = 0, AntialiasedLineEnable = 0, ForcedSampleCount = 0, ConservativeRaster = 0 },",
    "                    DepthStencilState = new D3D12_DEPTH_STENCIL_DESC { DepthEnable = 0, StencilEnable = 0 },",
    "                    InputLayout = inputLayout,",
    "                    PrimitiveTopologyType = 3,",
    "                    NumRenderTargets = 1,",
    "                    RTVFormats = new uint[8] { (uint)DXGI_FORMAT_R8G8B8A8_UNORM, 0, 0, 0, 0, 0, 0, 0 },",
    "                    SampleDesc = new D3D12_MULTISAMPLE_QUALITY_LEVEL_FLAGS { Count = 1, Quality = 0 }",
    "                };",
    "                IntPtr pso;",
    "                Guid IID_PipelineState = new Guid(\"765a30f3-f624-4c6f-a828-ace948622445\");",
    "                hr = GetMethod<CreateGraphicsPipelineStateDelegate>(device, 10)(device, ref psoDesc, ref IID_PipelineState, out pso);",
    "                if (hr < 0) throw new Exception(string.Format(\"CreateGraphicsPipelineState failed: 0x{0:X8}\", hr));",
    "                Log(string.Format(\"PSO created: 0x{0:X}\", pso.ToInt64()));",
    "                elementsHandle.Free();",
    "",
    "                // Create Vertex Buffer",
    "                Log(\"Creating Vertex Buffer...\");",
    "                var vertices = new Vertex[] {",
    "                    new Vertex { X=0.0f, Y=0.5f, Z=0.5f, R=1, G=0, B=0, A=1 },",
    "                    new Vertex { X=0.5f, Y=-0.5f, Z=0.5f, R=0, G=1, B=0, A=1 },",
    "                    new Vertex { X=-0.5f, Y=-0.5f, Z=0.5f, R=0, G=0, B=1, A=1 }",
    "                };",
    "                uint vertexBufferSize = (uint)(Marshal.SizeOf(typeof(Vertex)) * 3);",
    "                IntPtr vb;",
    "                var resourceDesc = new D3D12_RESOURCE_DESC { Dimension = 1, Alignment = 0, Width = vertexBufferSize, Height = 1, DepthOrArraySize = 1, MipLevels = 1, Format = 0, SampleDesc = new D3D12_MULTISAMPLE_QUALITY_LEVEL_FLAGS { Count = 1, Quality = 0 }, Layout = 1, Flags = 0 };",
    "                var heapProps = new D3D12_HEAP_PROPERTIES { Type = (uint)D3D12_HEAP_TYPE_UPLOAD, CPUPageProperty = 0, MemoryPoolPreference = 0, CreationNodeMask = 1, VisibleNodeMask = 1 };",
    "                hr = GetMethod<CreateCommittedResourceDelegate>(device, 27)(device, ref heapProps, (uint)D3D12_HEAP_FLAG_NONE, ref resourceDesc, 0x1, IntPtr.Zero, ref IID_Resource, out vb);",
    "                if (hr < 0) throw new Exception(string.Format(\"CreateCommittedResource (VB) failed: 0x{0:X8}\", hr));",
    "                Log(string.Format(\"Vertex Buffer created: 0x{0:X}\", vb.ToInt64()));",
    "",
    "                IntPtr dataPtr;",
    "                hr = GetMethod<MapDelegate>(vb, 8)(vb, 0, IntPtr.Zero, out dataPtr);",
    "                if (hr < 0) throw new Exception(string.Format(\"Map failed: 0x{0:X8}\", hr));",
    "                int vertexSize = Marshal.SizeOf(typeof(Vertex));",
    "                for (int i = 0; i < vertices.Length; i++) {",
    "                    Marshal.StructureToPtr(vertices[i], IntPtr.Add(dataPtr, i * vertexSize), false);",
    "                }",
    "                GetMethod<UnmapDelegate>(vb, 9)(vb, 0, IntPtr.Zero);",
    "",
    "                ulong vbGpuAddress = GetMethod<GetGPUVirtualAddressDelegate>(vb, 11)(vb);",
    "                Log(string.Format(\"VB GPU Address: 0x{0:X}\", vbGpuAddress));",
    "                D3D12_VERTEX_BUFFER_VIEW vbView = new D3D12_VERTEX_BUFFER_VIEW { BufferLocation = vbGpuAddress, SizeInBytes = vertexBufferSize, StrideInBytes = (uint)Marshal.SizeOf(typeof(Vertex)) };",
    "",
    "                Log(\"Entering main loop...\");",
    "                MSG msg;",
    "                float[] color = { 0.0f, 0.2f, 0.4f, 1.0f };",
    "                var vp = new D3D12_VIEWPORT { Width = 800, Height = 600, MaxDepth = 1.0f };",
    "                int frameCount = 0;",
    "                while (true) {",
    "                    if (PeekMessage(out msg, IntPtr.Zero, 0, 0, PM_REMOVE)) {",
    "                        if (msg.message == WM_QUIT) break;",
    "                        TranslateMessage(ref msg);",
    "                        DispatchMessage(ref msg);",
    "                    } else {",
    "                        hr = GetMethod<ResetCommandAllocatorDelegate>(commandAllocator, 8)(commandAllocator);",
    "                        hr = GetMethod<ResetCommandListDelegate>(commandList, 10)(commandList, commandAllocator, pso);",
    "                        GetMethod<SetGraphicsRootSignatureDelegate>(commandList, 30)(commandList, rootSignature);",
    "                        GetMethod<IASetPrimitiveTopologyDelegate>(commandList, 20)(commandList, (uint)D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST);",
    "                        GetMethod<RSSetViewportsDelegate>(commandList, 21)(commandList, 1, ref vp);",
    
    "                        uint currentBackBufferIndex = GetMethod<GetCurrentBackBufferIndexDelegate>(swapChain, 36)(swapChain);",
    
    "                        D3D12_RESOURCE_BARRIER barrierToRt = new D3D12_RESOURCE_BARRIER { Type = 0, Flags = 0, Transition = new D3D12_RESOURCE_TRANSITION_BARRIER { pResource = backBuffers[currentBackBufferIndex], Subresource = 0xFFFFFFFF, StateBefore = D3D12_RESOURCE_STATE_PRESENT, StateAfter = D3D12_RESOURCE_STATE_RENDER_TARGET } };",
    "                        GetMethod<ResourceBarrierDelegate>(commandList, 26)(commandList, 1, new D3D12_RESOURCE_BARRIER[] { barrierToRt });",
    "                        D3D12_CPU_DESCRIPTOR_HANDLE currentRtv = new D3D12_CPU_DESCRIPTOR_HANDLE { ptr = IntPtr.Add(rtvHandle.ptr, (int)(currentBackBufferIndex * rtvIncrement)) };",
    "                        GetMethod<OMSetRenderTargetsDelegate>(commandList, 46)(commandList, 1, ref currentRtv, true, IntPtr.Zero);",
    "                        GetMethod<ClearRenderTargetViewDelegate>(commandList, 48)(commandList, currentRtv, color, 0, IntPtr.Zero);",
    "                        GetMethod<IASetVertexBuffersDelegate>(commandList, 44)(commandList, 0, 1, new D3D12_VERTEX_BUFFER_VIEW[] { vbView });",
    "                        GetMethod<DrawInstancedDelegate>(commandList, 12)(commandList, 3, 1, 0, 0);",
    "                        D3D12_RESOURCE_BARRIER barrierToPresent = new D3D12_RESOURCE_BARRIER { Type = 0, Flags = 0, Transition = new D3D12_RESOURCE_TRANSITION_BARRIER { pResource = backBuffers[currentBackBufferIndex], Subresource = 0xFFFFFFFF, StateBefore = D3D12_RESOURCE_STATE_RENDER_TARGET, StateAfter = D3D12_RESOURCE_STATE_PRESENT } };",
    "                        GetMethod<ResourceBarrierDelegate>(commandList, 26)(commandList, 1, new D3D12_RESOURCE_BARRIER[] { barrierToPresent });",
    "                        hr = GetMethod<CloseCommandListDelegate>(commandList, 9)(commandList);",
    "                        IntPtr[] lists = new IntPtr[] { commandList };",
    "                        GetMethod<ExecuteCommandListsDelegate>(commandQueue, 10)(commandQueue, 1, lists);",
    "                        hr = GetMethod<PresentDelegate>(swapChain, 8)(swapChain, 1, 0);",
    "                        fenceValue++;",
    "                        hr = GetMethod<SignalDelegate>(commandQueue, 14)(commandQueue, fence, fenceValue);",
    "                        if (GetMethod<GetCompletedValueDelegate>(fence, 8)(fence) < fenceValue) {",
    "                            hr = GetMethod<SetEventOnCompletionDelegate>(fence, 9)(fence, fenceValue, fenceEvent);",
    "                            WaitForSingleObject(fenceEvent, 0xFFFFFFFF);",
    "                        }",
    "                        frameCount++;",
    "                        if (frameCount == 1) Log(\"First frame rendered\");",
    "                    }",
    "                }",
    "            } finally {",
    "                Marshal.FreeHGlobal(semanticNamePos);",
    "                Marshal.FreeHGlobal(semanticNameCol);",
    "            }",
    "            Log(\"Exiting...\");",
    "            CloseHandle(fenceEvent);",
    "        } catch (Exception ex) {",
    "            Log(\"EXCEPTION: \" + ex.ToString());",
    "        }",
    "    }",
    "}"
].join("\n");

Main();
