[package]
name = "hello"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.79"
web-sys = {"version" = "0.3.56", features=['console']}
js-sys = "0.3.56"
